package main

import (
	"bytes"
	"fmt"
	"go/token"
	"io"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/michelangelo-ai/michelangelo/go/kubeproto/pboptions"
	"github.com/michelangelo-ai/michelangelo/go/kubeproto/tags"
	"github.com/michelangelo-ai/michelangelo/go/kubeproto/templates"
	"github.com/michelangelo-ai/michelangelo/go/kubeproto/util"
	"github.com/michelangelo-ai/michelangelo/go/kubeproto/yaml"

	"github.com/dave/dst"
	"github.com/dave/dst/decorator"
	"github.com/gogo/protobuf/proto"
	"github.com/gogo/protobuf/protoc-gen-gogo/generator"
	plugingo "github.com/gogo/protobuf/protoc-gen-gogo/plugin"
	"github.com/gogo/protobuf/vanity"
	"github.com/gogo/protobuf/vanity/command"
	"google.golang.org/protobuf/compiler/protogen"
	golangproto "google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoregistry"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/pluginpb"
)

var _reProtoFileName = regexp.MustCompile(`\.pb\.go$`)
var reGogoTypeRemapPath = regexp.MustCompile(`github\.com\/gogo\/protobuf\/types`)
var snakeCaseSeparators = regexp.MustCompile("-\\.")

var logger = log.New(os.Stderr, "", 0)

const _testProtoImportPath = "michelangelo/tools/kubeproto/unittest/pb"

// Call gogo proto to generate go code from protobuf
// The options are chosen to make the generated go code to be compatible
// with k8s "k8s.io/apimachinery/pkg/apis/meta/v1" library (e.g. no Equal function)
func gogoproto(reqData []byte) *plugingo.CodeGeneratorResponse {
	g := generator.New()

	if err := proto.Unmarshal(reqData, g.Request); err != nil {
		g.Error(err, "parsing input proto")
	}

	if len(g.Request.FileToGenerate) == 0 {
		g.Fail("no files to generate")
	}

	req := g.Request

	files := req.GetProtoFile()
	files = vanity.FilterFiles(files, vanity.NotGoogleProtobufDescriptorProto)

	vanity.ForEachFile(files, vanity.TurnOnMarshalerAll)
	vanity.ForEachFile(files, vanity.TurnOnSizerAll)
	vanity.ForEachFile(files, vanity.TurnOnUnmarshalerAll)

	vanity.ForEachFieldInFilesExcludingExtensions(vanity.OnlyProto2(files), vanity.TurnOffNullableForNativeTypesWithoutDefaultsOnly)
	vanity.ForEachFile(files, vanity.TurnOffGoUnrecognizedAll)
	vanity.ForEachFile(files, vanity.TurnOffGoUnkeyedAll)
	vanity.ForEachFile(files, vanity.TurnOffGoSizecacheAll)

	vanity.ForEachFile(files, vanity.TurnOffGoEnumPrefixAll)
	vanity.ForEachFile(files, vanity.TurnOffGoEnumStringerAll)
	vanity.ForEachFile(files, vanity.TurnOnEnumStringerAll)

	vanity.ForEachFile(files, vanity.TurnOnGoStringAll)
	vanity.ForEachFile(files, vanity.TurnOffGoStringerAll)
	vanity.ForEachFile(files, vanity.TurnOnStringerAll)

	return command.Generate(req)
}

// Recursively load message definitions from protobuf.
// In addition to the top level messages provided by the protoMsgs parameter,
// we also need to load the nested messages
// As go does not support nested messages, all the nested protobuf messages are
// translated into package level go structs. So, the go indent names (w/o package
// names) are enough to identify each struct in the file.
func loadProtoMsgs(msgs []*protogen.Message, protoMsgs *map[string]*protogen.Message) {
	for _, msg := range msgs {
		loaded := *protoMsgs
		if _, found := loaded[msg.GoIdent.GoName]; found {
			continue
		} else {
			(*protoMsgs)[msg.GoIdent.GoName] = msg
			loadProtoMsgs(msg.Messages, protoMsgs)
		}
	}
}

// copy the "leading detached comments" from protobuf file to go structs and fields
func copyComments(goDecs *dst.NodeDecs, protoComments *protogen.CommentSet) {
	if len(protoComments.LeadingDetached) > 0 {
		goDecs.Start.Clear()

		for _, comment := range protoComments.LeadingDetached {
			goDecs.Start.Append(comment.String())
			goDecs.Start.Append("\n")
			goDecs.Start.Append("\n")
		}
		goDecs.Start.Append("\n")

		if len(protoComments.Leading) != 0 {
			goDecs.Start.Append(protoComments.Leading.String())
		}
	}
}

func intContains(s []int, e int) bool {
	for _, a := range s {
		if a == e {
			return true
		}
	}
	return false
}

func strContains(s []string, e string) bool {
	for _, a := range s {
		if a == e {
			return true
		}
	}
	return false
}

// Remove the functions of a CRD or CRD-list type generated by gogoproto
// returns the indices of the Decls to be removed in the dstFile
func strip(dstFile *dst.File, name string) []int {
	functions := []string{"GetTypeMeta", "GetMetadata", "GoString", "MarshalToSizedBuffer", "Size", "String", "Unmarshal"}

	var remove []int
	for i, decl := range dstFile.Decls {
		funcDecl, isFuncDecl := decl.(*dst.FuncDecl)
		if !isFuncDecl {
			continue
		}
		receiver := funcDecl.Recv
		if receiver == nil {
			continue
		}
		starType, isStarExpr := receiver.List[0].Type.(*dst.StarExpr)
		if !isStarExpr {
			continue
		}
		if starType.X.(*dst.Ident).Name == name {
			if strContains(functions, funcDecl.Name.Name) || strings.HasPrefix(funcDecl.Name.Name, "Get") {
				remove = append(remove, i)
			}
		}
	}

	return remove
}

// Generate go code for a CRD or CRD list type
func genCRD(crdBuf *bytes.Buffer, filename string, name string, protoComments *protogen.CommentSet, options *pboptions.Options) {
	detachedComments := strings.Builder{}
	for i, c := range protoComments.LeadingDetached {
		if i > 0 {
			detachedComments.WriteString("\n")
		}
		detachedComments.WriteString(c.String())
	}

	if options.Bool("has_resource") {
		typeInfo := struct {
			Name             string
			FileName         string
			DetachedComments string
			Comments         string
		}{name, filename, detachedComments.String(), protoComments.Leading.String()}
		templates.CRD.Execute(crdBuf, typeInfo)
	} else { // crd list
		typeInfo := struct {
			Name             string
			FileName         string
			DetachedComments string
			Comments         string
		}{strings.TrimSuffix(name, "List"), filename, detachedComments.String(), protoComments.Leading.String()}
		templates.CRDList.Execute(crdBuf, typeInfo)
	}
}

// Modify the go file generated by gogoproto:
//  1. Append the "detached leading comments" to structs and fields. These comments are ignored by gogoproto,
//     but are important for controller-gen
//  2. Copy json names from protobufs tag to json tags. Gogoproto does not support json tags for protobuf-3,
//     as the developers of gogoproto think it's impossible to implement the full protobuf-3-to-json spec with
//     json tags. However, k8s controller runtime and k8s client still depend on json tags rather than the new
//     jsonpb API.
//  3. Replace protobuf generated k8s types (gogoproto/github.com/k8s.io/apimachinery/pkg/apis/meta/v1) with
//     genuine k8s types (k8s.io/apimachinery/pkg/apis/meta/v1)
//  4. For CRD and CRD list types, rewrite the structs (embed TypeMetadata and use reference instead of pointers),
//     generate deep copy functions, add controller-tools markers, and register the type to k8s runtime scheme
//  5. If the input file contains michelangelo.api.k8s_api_group_name option, generate group-version info for k8s runtime
func updateGoFile(gofile *plugingo.CodeGeneratorResponse_File, protofile *protogen.File,
	extTypes *protoregistry.Types, gInfo *yaml.GroupInfo) {
	dstFile, err := decorator.Parse(*gofile.Content)
	if err != nil {
		logger.Panicf("failed to parse gogoproto generated file %v: %v", gofile.GetName(), err)
	}

	// file name in camel case, this string is used by gogo proto in the generated go code
	fileName := strings.TrimSuffix(filepath.Base(protofile.Proto.GetName()), ".proto")
	fileName = generator.CamelCase(snakeCaseSeparators.ReplaceAllString(fileName, "_"))

	// if option group_info set, generate k8s groupversion info file
	options, err := pboptions.ReadOptions(extTypes, protofile.Proto.Options)
	if options != nil && options.Bool("has_group_info") {
		group := options.String("group_info.name")
		version := options.String("group_info.version")

		if group != "" && version != "" {
			var buf bytes.Buffer
			templates.GroupVersion.Execute(&buf, struct {
				Group     string
				Version   string
				GoPackage string
			}{group, version, dstFile.Name.Name})
			updatedContent := buf.String()
			gofile.Content = &updatedContent

			return
		}
	}

	protoMsgs := make(map[string]*protogen.Message)
	loadProtoMsgs(protofile.Messages, &protoMsgs)

	// By default, gogoproto uses the last part of the package path as the package alias. But if multiple packages
	// having the same last part, gogoproto will assign unique names to the packages.
	// For example, if there is another package ends with '/v1', the alias of "k8s.io/apimachinery/pkg/apis/meta/v1"
	// package may become "vv1". This will cause the go code generated from our template to be invalid, if we referred
	// the package as "v1".
	// To avoid this, we explicitly set the alias of "k8s.io/apimachinery/pkg/apis/meta/v1" to "metav1" and set the
	// alias of "github.com/michelangelo-ai/proto/michelangelo/api" to "apipb". The new aliases "metav1" and "apipb"
	// are less likely to conflict with other package aliases
	util.SetPackageAlias(dstFile, "k8s.io/apimachinery/pkg/apis/meta/v1", "metav1")
	util.SetPackageAlias(dstFile, "github.com/michelangelo-ai/proto/michelangelo/api", "apipb")

	var crdFunctionsBuf bytes.Buffer
	hasCRD := false
	var remove []int
	for i, decl := range dstFile.Decls {
		genDecl, isGenDecl := decl.(*dst.GenDecl)
		if isGenDecl {
			// for each "type" declaration
			if genDecl.Tok == token.TYPE {
				typeSpec := genDecl.Specs[0].(*dst.TypeSpec)
				typeName := typeSpec.Name.Name
				protoMsg := protoMsgs[typeName]

				// type struct declaration
				structType, isStruct := typeSpec.Type.(*dst.StructType)
				if isStruct && protoMsg != nil {
					// copy the "leading detached comments" from protobuf file to go structs
					copyComments(genDecl.Decorations(), &protoMsg.Comments)

					// for each field
					for i, field := range structType.Fields.List {
						protoField := protoMsg.Fields[i]

						// copy the "leading detached comments" from protobuf file to go fields
						copyComments(genDecl.Decorations(), &protoField.Comments)

						// copy json names from protobuf tag to json tag
						tag := field.Tag.Value
						jsonTag := tags.GetJSONTag(tag)
						pbTag := tags.GetPBTag(tag)
						if pbTag != nil && jsonTag != nil && jsonTag.Name != "" {
							jsonTag.Name = pbTag.GetJSONName()
						}
						if jsonTag == nil {
							logger.Printf("Empty jsonTag in tag: %v, type %s, field: %v", tag, typeName, field)
						} else {
							tags.SetJSONTag(&field.Tag.Value, jsonTag)
						}
					}

					pbOptions := protoMsg.Desc.Options().(*descriptorpb.MessageOptions)
					options, err := pboptions.ReadOptions(extTypes, pbOptions)
					if err != nil {
						logger.Panicf("Failed to parse the options of message %v: %v", typeName, err)
					}

					if options.Bool("has_resource") || options.Bool("has_resource_list") {
						hasCRD = true

						if gInfo == nil {
							logger.Panic("Found CRD definition in message " + typeName +
								", but cannot find groupversion_info.proto file in the same directory")
						}

						remove = append(remove, i)
						remove = append(remove, strip(dstFile, typeName)...)

						genCRD(&crdFunctionsBuf, fileName, typeName, &protoMsg.Comments, options)
						if options.Bool("has_resource") {
							genImmutability(typeName, &crdFunctionsBuf, options)
							genCRDObject(typeName, gInfo, &crdFunctionsBuf)
							genCRDBlobFields(typeName, protoMsg, &crdFunctionsBuf, extTypes)
							crdFunctionsBuf.Write([]byte("func init() {\n\tYamlSchemas[\"" + typeName + "\"] = `"))
							yamlStr := string(yaml.GenerateCRDYaml(protofile, extTypes, *gInfo))
							crdFunctionsBuf.Write([]byte(strings.Replace(yamlStr, "`", "`+\"`\"+`", -1)))
							crdFunctionsBuf.Write([]byte("`\n"))
							crdFunctionsBuf.Write([]byte("}"))
						}
					}
				}
			}
		}
	}

	// Remove structs / functions that we don't need or have replaced
	var newDecls []dst.Decl
	for i, d := range dstFile.Decls {
		if !intContains(remove, i) {
			newDecls = append(newDecls, d)
		}
	}
	dstFile.Decls = newDecls

	var buf bytes.Buffer
	decorator.Fprint(&buf, dstFile)
	buf.Write(crdFunctionsBuf.Bytes())
	updatedContent := buf.String()

	if hasCRD {
		updatedContent = strings.Replace(updatedContent, `import (`, "import ("+templates.CRDImports, 1)
	}

	gofile.Content = &updatedContent
}

func genCRDObject(crdName string, gInfo *yaml.GroupInfo, crdBuf *bytes.Buffer) {
	typeInfo := struct {
		Group   string
		Version string
		Kind    string
	}{gInfo.Name, gInfo.Version, crdName}
	templates.RegisterCRDObject.Execute(crdBuf, typeInfo)
	crdBuf.Write([]byte("\n"))
}

func genImmutability(crdName string, crdBuf *bytes.Buffer, crdOptions *pboptions.Options) {
	crdIsImmutable := false
	if crdOptions.Bool("resource.immutable") == true {
		crdIsImmutable = true
	}
	typeInfo := struct {
		Name      string
		Immutable bool
	}{crdName, crdIsImmutable}
	templates.CRDImmutability.Execute(crdBuf, typeInfo)
	crdBuf.Write([]byte("\n"))
}

func findBlobFields(curMsg *protogen.Message, pathPrefix string, blobFields *[]string,
	processedMessageTypes *map[protogen.GoIdent]bool, extTypes *protoregistry.Types) {
	for _, field := range curMsg.Fields {
		options, err := util.GetFieldOptions(field, extTypes)
		if err != nil {
			logger.Panicf("Failed to parse the options for field %s: %v", field.Desc.TextName(), err)
		}

		newPrefix := strings.Trim(pathPrefix+"."+field.GoName, ".")
		if options.Bool("external_storage") {
			*blobFields = append(*blobFields, newPrefix)
		}

		// Only find blob fields in messages that are declared in the same package (e.g. michelangelo.api.v2)
		if field.Message != nil && field.Message.GoIdent.GoImportPath == curMsg.GoIdent.GoImportPath {
			// Maintain processed message types along the recursion path to avoid getting into infinite recursion
			if _, found := (*processedMessageTypes)[field.Message.GoIdent]; !found {
				(*processedMessageTypes)[field.Message.GoIdent] = true
				findBlobFields(field.Message, newPrefix, blobFields, processedMessageTypes, extTypes)
				delete(*processedMessageTypes, field.Message.GoIdent)
			}
		}
	}
}

func genCRDBlobFields(crdName string, crdMsg *protogen.Message, crdBuf *bytes.Buffer, extTypes *protoregistry.Types) {
	var blobFields []string
	processedMessageTypes := make(map[protogen.GoIdent]bool)
	findBlobFields(crdMsg, "", &blobFields, &processedMessageTypes, extTypes)

	hasBlobFields := len(blobFields) > 0
	typeInfo := struct {
		Name          string
		HasBlobFields bool
	}{crdName, hasBlobFields}
	templates.CRDHasBlobFields.Execute(crdBuf, typeInfo)
	crdBuf.Write([]byte("\n"))
	genClearCrdFields(crdName, blobFields, crdBuf)
	templates.CRDFillBlobFields.Execute(crdBuf, typeInfo)
	crdBuf.Write([]byte("\n"))
}

func genClearCrdFields(crdName string, blobFields []string, crdBuf *bytes.Buffer) {
	typeInfo := struct {
		Name string
	}{crdName}
	templates.CRDClearBlobFieldsHeader.Execute(crdBuf, typeInfo)

	for _, blobFieldName := range blobFields {
		crdBuf.Write([]byte(fmt.Sprintf("\tif %s {\n", getIfNestedFieldsNotNil(blobFieldName))))
		statement := fmt.Sprintf("\t\tm.%s = nil\n", blobFieldName)
		crdBuf.Write([]byte(statement))
		crdBuf.Write([]byte("\t}\n"))
	}

	crdBuf.Write([]byte("}\n\n"))
}

func getIfNestedFieldsNotNil(blobFieldName string) string {
	paths := strings.Split(blobFieldName, ".")
	statement := ""
	cur := fmt.Sprintf("m.%s", paths[0])
	for i := 1; i < len(paths); i++ {
		cur += fmt.Sprintf(".%s", paths[i])
		// `Spec` and `Status` are not pointer type so we should skip generating `!= nil` statement
		if paths[i] == "Spec" || paths[i] == "Status" {
			continue
		}
		if len(statement) > 0 {
			statement += " && "
		}
		statement += fmt.Sprintf("%s != nil", cur)
	}
	return statement
}

func protoFileName(goFileName string) string {
	return string(_reProtoFileName.ReplaceAll([]byte(goFileName), []byte(".proto")))
}

func generate(reqData []byte) *plugingo.CodeGeneratorResponse {
	// generate go code with gogoproto
	resp := gogoproto(reqData)

	gofiles := make(map[string]*plugingo.CodeGeneratorResponse_File)
	for _, f := range resp.File {
		gofiles[protoFileName(f.GetName())] = f
	}

	// parse protoc request with golang proto
	// golang proto api is easier to use than gogo proto api
	var req pluginpb.CodeGeneratorRequest
	golangproto.Unmarshal(reqData, &req)
	util.ReplaceImportPath(&req)

	// initialize golang proto generator
	gen, err := protogen.Options{}.New(&req)
	if err != nil {
		logger.Panicf("failed to initialize golang proto generator %v", err)
	}

	// Load protobuf extensions from all the imported protobuf files
	extTypes := pboptions.LoadPBExtensions(gen.Files)

	// Load group info
	gInfo := yaml.LoadGroupInfo(gen, extTypes, false)

	for _, f := range gen.Files {
		// skip the proto file that don't need to generate go code,
		// such as imported proto files
		if !f.Generate {
			continue
		}
		updateGoFile(gofiles[f.Proto.GetName()], f, extTypes, gInfo)
	}
	return resp
}

func main() {
	// read protoc request from stdin
	reqData, err := io.ReadAll(os.Stdin)
	if err != nil {
		logger.Panicf("reading input %v", err)
	}

	resp := generate(reqData)
	command.Write(resp)
}
