package plugins

const (
	// ValidationActorType ...
	ValidationActorType = "RolloutValidated"
	// ResourceAcquisitionActorType ...
	ResourceAcquisitionActorType = "ResourceAcquired"
	// PlacementActorType ...
	PlacementActorType = "RolloutComplete"
	// RollbackActorType ...
	RollbackActorType = "RollbackComplete"
	// CleanupActorType ...
	CleanupActorType = "CleanupComplete"
	// SteadyStateActor ...
	SteadyStateActor = "StateSteady"
)
