apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - apiserver/
  - controllermgr/
  - worker/
  - michelangelo-ui/

labels:
- pairs:
    app.kubernetes.io/part-of: michelangelo