kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30001
    hostPort: 3306
  - containerPort: 30002
    hostPort: 7833
  - containerPort: 30003
    hostPort: 7933
  - containerPort: 30004
    hostPort: 8088
  - containerPort: 30005
    hostPort: 8090
  - containerPort: 30006
    hostPort: 8091
  - containerPort: 30007 # minio
    hostPort: 9090
  - containerPort: 30008 # minio
    hostPort: 9091
