---
apiVersion: v1
kind: ConfigMap
metadata:
  name: michelangelo-config
data:
  MA_FILE_SYSTEM: s3://default
  MA_FILE_SYSTEM_S3_SCHEME: http
  MA_FILE_SYSTEM_S3_ENDPOINT: localhost:9090
  MA_FILE_SYSTEM_S3_ACCESS_KEY: 1inaX9pX7vIeaJf3
  MA_FILE_SYSTEM_S3_SECRET_KEY: 2OuOk0lGBLM1W9lrRzEBPiOoxZZBq6o0
  AWS_ACCESS_KEY_ID: 1inaX9pX7vIeaJf3
  AWS_SECRET_ACCESS_KEY: 2OuOk0lGBLM1W9lrRzEBPiOoxZZBq6o0
  AWS_ENDPOINT_URL: http://10.96.117.50:9001
