apiVersion: michelangelo.api/v2
kind: RayCluster
metadata:
  name: ray-cluster-v2
  namespace: default
spec:
  rayVersion: "2.2.0"
#  termination:
#    type: TERMINATION_TYPE_FAILED
#    reason: "killed by user"
#  termination:
#    type: TERMINATION_TYPE_SUCCEEDED
#    reason: "job succeeded"
  head:
    serviceType: "ClusterIP"
    pod:
      spec:
        containers:
          - name: head
            image: rayproject/ray:2.5.0
            lifecycle:
              postStart:
                exec:
                  command: [ "/bin/sh","-c", "echo","'Initializing Ray Head'" ]
            env:
              - name: RAY_HEAD_ENV
                value: "true"
              - name: DEBUG
                value: "false"
  workers:
    - minInstances: 1
      maxInstances: 1
      pod:
        spec:
          containers:
            - name: worker
              resources:
                requests:
                  cpu: 1
                  memory: 2Gi
              image: rayproject/ray:2.5.0
              lifecycle:
                postStart:
                  exec:
                    command: [ "/bin/sh","-c", "echo","'Initializing Ray Worker'" ]
              env:
                - name: RAY_WORKER_ENV
                  value: "true"
                - name: DEBUG
                  value: "false"
