apiVersion: michelangelo.api/v2
kind: RayCluster
metadata:
  name: ray-cluster-v2
  namespace: default
spec:
  rayVersion: "2.2.0"
#  termination:
#    type: TERMINATION_TYPE_FAILED
#    reason: "killed by user"
#  termination:
#    type: TERMINATION_TYPE_SUCCEEDED
#    reason: "job succeeded"
  head:
    serviceType: "ClusterIP"
    rayStartParams:
      block: "true"
      dashboard-host: "0.0.0.0"
    pod:
      spec:
        containers:
          - name: head
            image: docker.io/library/bert-cola-nv:latest
            imagePullPolicy: Never
            lifecycle:
              postStart:
                exec:
                  command: [ "/bin/sh","-c", "echo","'Initializing Ray Head'" ]
            envFrom:
              - configMapRef:
                  localObjectReference:
                    name: michelangelo-config
            env:
              - name: RAY_HEAD_ENV
                value: "true"
              - name: DEBUG
                value: "false"
  workers:
    - minInstances: 1
      maxInstances: 1
      rayStartParams:
        block: "true"
        dashboard-host: "0.0.0.0"
      pod:
        spec:
          volumes:
            - name: dshm
              volumeSource:
                emptyDir:
                  medium: Memory
                  sizeLimit: 1Gi
          containers:
            - name: worker
              volumeMounts:
                - mountPath: /dev/shm
                  name: dshm
              resources:
                requests:
                  cpu: 1
                  memory: 1Gi
              image: docker.io/library/bert-cola-nv:latest
              imagePullPolicy: Never
              lifecycle:
                postStart:
                  exec:
                    command: [ "/bin/sh","-c", "echo","'Initializing Ray Worker'" ]
              envFrom:
                - configMapRef:
                    localObjectReference:
                      name: michelangelo-config
              env:
                - name: RAY_WORKER_ENV
                  value: "true"
                - name: DEBUG
                  value: "false"
