apiVersion: michelangelo.api/v2
kind: Deployment
metadata:
  name: sentiment-mobile-deployment
  namespace: ma-dev-test
  labels:
    stage: canary
spec:
  desiredRevision:
    name: sentiment-model-v1
    namespace: ma-dev-test
  mobileSpec:
    level: DEVICE_INTEGRITY_LEVEL_STANDARD
  definition:
    type: TARGET_TYPE_MOBILE
  strategy:
    rolling:
      incrementPercentage: 10
  owner:
    name: craig.marker
