apiVersion: michelangelo.api/v2
kind: Deployment
metadata:
  name: sentiment-offline-deployment
  namespace: ma-dev-test
  annotations:
    deployment.michelangelo/last-prediction-timestamp: "1745798400"
  labels:
    stage: staging
spec:
  desiredRevision:
    name: sentiment-model-v1
    namespace: ma-dev-test
  inferenceServer:
    name: inference-server-example
    namespace: default
  definition:
    type: TARGET_TYPE_OFFLINE
  strategy:
    blast:
      withRollbackTrigger: false
  owner:
    name: craig.marker
