apiVersion: michelangelo.api/v2
kind: Pipeline
metadata:
  namespace: "ma-dev-test"
  name: "bert-cola-test"
  annotations:
    michelangelo/uniflow-image: docker.io/library/examples:latest
spec:
  type: "PIPELINE_TYPE_EVAL"
  manifest:
    filePath: examples.bert_cola.bert_cola_eval
