repos:
  - repo: local
    hooks:
      - id: ruff-lint
        name: ruff linter
        entry: poetry run ruff check --config python/pyproject.toml
        language: system
        types: [python]
      - id: ruff-format
        name: ruff formatter
        entry: poetry run ruff format --config python/pyproject.toml
        language: system
        types: [python]
