controllermgr:
  metricsBindAddress: ${METRICS_ADDRESS::8080}
  healthProbeBindAddress: ${HEALTH_ADDRESS::8081}
  leaderElection: false
  leaderElectionID: decaf1259.michelangelo.uber.com
  port: 9443

workflowClient:
  service: cadence-frontend
  host: michelangelo-worker:7833
  transport: grpc
  domain: default
    
k8s:
  qps: 300
  burst: 600
metadataStorage:
  enableMetadataStorage: false

controllers:
  rayCluster:
    k8sQps: 300
    k8sBurst: 600
