controllermgr:
  metricsBindAddress: localhost:8084
  healthProbeBindAddress: localhost:8083
  leaderElection: false
  leaderElectionID: decaf1259.michelangelo.uber.com
  port: 9443

controllers:
  rayCluster:
    k8sQps: 300
    k8sBurst: 600
