controllermgr:
  metricsBindAddress: localhost:8082
  healthProbeBindAddress: localhost:8083
  leaderElection: false
  leaderElectionID: decaf1259.michelangelo.uber.com
  port: 9443

k8s:
  qps: 300
  burst: 600
metadataStorage:
  enableMetadataStorage: false

controllers:
  rayCluster:
    k8sQps: 300
    k8sBurst: 600
