load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "go_default_library",
    srcs = [
        "compose.go",
        "config.go",
        "oidc.go",
        "serviceaccount.go",
    ],
    importpath = "github.com/michelangelo-ai/michelangelo/go/auth/oidc",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_coreos_go_oidc_v3//oidc:go_default_library",
        "@io_k8s_api//authentication/v1:go_default_library",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:go_default_library",
        "@io_k8s_apiserver//pkg/authentication/authenticator:go_default_library",
        "@io_k8s_apiserver//pkg/authentication/token/cache:go_default_library",
        "@io_k8s_apiserver//pkg/authentication/token/union:go_default_library",
        "@io_k8s_apiserver//pkg/authentication/user:go_default_library",
        "@io_k8s_client_go//kubernetes:go_default_library",
    ],
)

go_test(
    name = "go_default_test",
    srcs = [
        "compose_test.go",
        "oidc_test.go",
        "serviceaccount_test.go",
    ],
    embed = [":go_default_library"],
    deps = [
        "@com_github_go_jose_go_jose_v4//:go_default_library",
        "@com_github_stretchr_testify//assert:go_default_library",
        "@com_github_stretchr_testify//require:go_default_library",
        "@io_k8s_api//authentication/v1:go_default_library",
        "@io_k8s_apimachinery//pkg/runtime:go_default_library",
        "@io_k8s_client_go//kubernetes/fake:go_default_library",
        "@io_k8s_client_go//testing:go_default_library",
    ],
)
