workflow_function: examples.canvasflex_pipeline.workflow.canvasflex_pipeline_example
workflow_config:
  experiment_name: canvasflex-yaml-demo
task_configs:
  prepare_data:
    config:
      dataset: cats-vs-dogs
  train:
    config:
      learning_rate: 0.01
      epochs: 5
