apiVersion: michelangelo.api/v2
kind: InferenceServer
metadata:
  name: dynamo-inference-server
  namespace: default
  labels:
    app: dynamo-inference-server
spec:
  tenancyType: TENANCY_TYPE_DEDICATED
  backendType: BACKEND_TYPE_DYNAMO
  ownerSpec:
    tier: 1
  initSpec:
    resourceSpec:
      # CPU/memory for the frontend and workers
      # Keep requests low to fit on GPU nodes (~4 CPU, ~13Gi allocatable)
      # todo: ghosharitra: revisit this.
      cpu: 2
      memory: "4Gi"
      # GPU is required for vLLM inference
      gpu: 1
    servingSpec:
      version: "latest"
    numInstances: 1
  decomSpec:
    decommission: false
  owner:
    name: "user-example"
