apiVersion: v1
kind: Service
metadata:
  name: michelangelo-controllermgr
  labels:
    app: michelangelo-controllermgr
spec:
  selector:
    app: michelangelo-controllermgr
  ports:
  - name: metrics
    port: 8091
    targetPort: 8091
  - name: health
    port: 8081
    targetPort: 8081