{{- if .Values.apiserver.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "michelangelo.componentFullname" (dict "context" . "component" "apiserver-config") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "michelangelo.componentLabels" (dict "context" . "component" "apiserver") | nindent 4 }}
data:
  base.yaml: |
    apiserver:
      yarpc:
        host: 0.0.0.0
        port: {{ .Values.apiserver.port }}
      k8s:
        qps: {{ .Values.apiserver.k8s.qps }}
        burst: {{ .Values.apiserver.k8s.burst }}
      crdSync:
        enableCRDUpdate: {{ .Values.apiserver.crdSync.enableUpdate }}
      pipelineRunDefaults:
        environment: {{ .Values.apiserver.pipelineRunDefaults.environment | default "" | quote }}
      {{- if ne .Values.apiserver.auth.mode "dummy" }}
      auth:
        mode: {{ .Values.apiserver.auth.mode | quote }}
        {{- if .Values.apiserver.auth.oidc.issuerUrl }}
        oidc:
          issuerUrl: {{ .Values.apiserver.auth.oidc.issuerUrl | quote }}
          audiences:
            {{- range .Values.apiserver.auth.oidc.audiences }}
            - {{ . | quote }}
            {{- end }}
          usernameClaim: {{ .Values.apiserver.auth.oidc.usernameClaim | quote }}
          groupsClaim: {{ .Values.apiserver.auth.oidc.groupsClaim | quote }}
          clockSkewLeeway: {{ .Values.apiserver.auth.oidc.clockSkewLeeway }}
        {{- end }}
        {{- if .Values.apiserver.auth.serviceAccounts.enabled }}
        serviceAccounts:
          enabled: true
          {{- with .Values.apiserver.auth.serviceAccounts.audiences }}
          audiences:
            {{- range . }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
        {{- end }}
        sarCache:
          allowTTL: {{ .Values.apiserver.auth.sarCache.allowTTL }}
          denyTTL: {{ .Values.apiserver.auth.sarCache.denyTTL }}
      {{- end }}
    metadataStorage:
      enableMetadataStorage: {{ .Values.apiserver.metadataStorage.enable }}
    mysql:
      host: {{ .Values.metadataStorage.host | default "" | quote }}
      port: {{ .Values.metadataStorage.port | default 3306 }}
      user: {{ .Values.metadataStorage.user | default "root" | quote }}
      password: ${MYSQL_PASSWORD}
      database: {{ .Values.metadataStorage.database | default "" | quote }}
{{- end }}
