{{- if and .Values.cadence.enabled (eq .Values.workflow.engine "cadence") -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadence
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "michelangelo.labels" . | nindent 4 }}
    app.kubernetes.io/component: cadence
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cadence
  template:
    metadata:
      labels:
        app: cadence
    spec:
      {{- with .Values.gpuTolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: cadence
        image: {{ .Values.cadence.image }}
        env:
        - name: DB
          value: mysql
        - name: DB_PORT
          value: "3306"
        - name: MYSQL_SEEDS
          value: mysql
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PWD
          value: {{ .Values.mysql.rootPassword }}
        - name: STATSD_ENDPOINT
          value: "localhost:8125"
        # Bind to all interfaces so port-forward works
        # TODO: Revisit this
        - name: BIND_ON_IP
          value: "0.0.0.0"
        ports:
        - name: grpc
          containerPort: 7833
        - name: tchannel
          containerPort: 7933
        resources:
          {{- toYaml .Values.cadence.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: cadence
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "michelangelo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: {{ .Values.cadence.service.grpc.port }}
    targetPort: grpc
  - name: tchannel
    port: {{ .Values.cadence.service.tchannel.port }}
    targetPort: tchannel
  selector:
    app: cadence
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadence-web
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "michelangelo.labels" . | nindent 4 }}
    app.kubernetes.io/component: cadence-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cadence-web
  template:
    metadata:
      labels:
        app: cadence-web
    spec:
      {{- with .Values.gpuTolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: cadence-web
        image: {{ .Values.cadence.webImage }}
        env:
        - name: CADENCE_TCHANNEL_PEERS
          value: cadence:7933
        ports:
        - name: http
          containerPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  name: cadence-web
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "michelangelo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.cadence.service.web.port }}
    targetPort: http
  selector:
    app: cadence-web
{{- end }}

