{{- if .Values.minio.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "michelangelo.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.minio.persistence.size }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "michelangelo.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: {{ .Values.minio.image }}
        args:
        - server
        - /data
        - --console-address
        - ":9090"
        env:
        - name: MINIO_ROOT_USER
          value: {{ .Values.storage.s3.accessKeyId }}
        - name: MINIO_ROOT_PASSWORD
          value: {{ .Values.storage.s3.secretAccessKey }}
        ports:
        - name: api
          containerPort: 9000
        - name: console
          containerPort: 9090
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          {{- toYaml .Values.minio.resources | nindent 10 }}
      volumes:
      - name: data
        {{- if .Values.minio.persistence.enabled }}
        persistentVolumeClaim:
          claimName: minio-pvc
        {{- else }}
        emptyDir: {}
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "michelangelo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: api
    port: 9091
    targetPort: 9000
  - name: console
    port: 9090
    targetPort: 9090
  selector:
    app: minio
{{- end }}

