apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: envoy
  name: envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy
  template:
    metadata:
      labels:
        app: envoy
    spec:
      containers:
      - args:
        - -c
        - /etc/envoy/envoy.yaml
        image: envoyproxy/envoy:v1.29-latest
        imagePullPolicy: IfNotPresent
        name: envoy
        ports:
        - containerPort: 8081
          protocol: TCP