// Code generated by MockGen. DO NOT EDIT.
// Source: localqueues.go

// Package kueuemocks is a generated GoMock package.
package kueuemocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v2 "github.com/michelangelo-ai/michelangelo/proto-go/api/v2"
)

// MockLocalQueues is a mock of LocalQueues interface.
type MockLocalQueues struct {
	ctrl     *gomock.Controller
	recorder *MockLocalQueuesMockRecorder
}

// MockLocalQueuesMockRecorder is the mock recorder for MockLocalQueues.
type MockLocalQueuesMockRecorder struct {
	mock *MockLocalQueues
}

// NewMockLocalQueues creates a new mock instance.
func NewMockLocalQueues(ctrl *gomock.Controller) *MockLocalQueues {
	mock := &MockLocalQueues{ctrl: ctrl}
	mock.recorder = &MockLocalQueuesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocalQueues) EXPECT() *MockLocalQueuesMockRecorder {
	return m.recorder
}

// Exists mocks base method.
func (m *MockLocalQueues) Exists(ctx context.Context, cluster *v2.Cluster, namespace, name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, cluster, namespace, name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockLocalQueuesMockRecorder) Exists(ctx, cluster, namespace, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockLocalQueues)(nil).Exists), ctx, cluster, namespace, name)
}
