apiVersion: v1
kind: ServiceAccount
metadata:
  name: michelangelo-controllermgr
  labels:
    app: michelangelo-controllermgr
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: michelangelo-controllermgr
  labels:
    app: michelangelo-controllermgr
rules:
- apiGroups: ["michelangelo.api"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["ray.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets", "events"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: michelangelo-controllermgr
  labels:
    app: michelangelo-controllermgr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: michelangelo-controllermgr
subjects:
- kind: ServiceAccount
  name: michelangelo-controllermgr
  namespace: michelangelo