apiVersion: michelangelo.api/v2
kind: Project
metadata:
  name: ingester-test
  namespace: ingester-test
  labels:
    test: ingester
spec:
  description: Ingester test project
  owner:
    owningTeam: "michelangelo"
    owners:
      - hkriplani
  tier: 4
  gitRepo: https://github.com/uber/michelangelo
  rootDir: scripts/ingester-test-crs
