apiVersion: michelangelo.api/v2
kind: PipelineRun
metadata:
  name: ingester-test-pipelinerun
  namespace: ingester-test
  labels:
    test: ingester
spec:
  pipeline:
    name: ingester-test-pipeline
    namespace: ingester-test
  input:
    kw_args:
      path: glue
      name: sst2
