apiVersion: michelangelo.api/v2
kind: Revision
metadata:
  name: ingester-test-revision
  namespace: ingester-test
  labels:
    test: ingester
spec:
  baseType:
    kind: Pipeline
    apiVersion: michelangelo.api/v2
  baseResource:
    name: ingester-test-pipeline
    namespace: ingester-test
  owner:
    name: hkriplani
