apiVersion: michelangelo.api/v2
kind: SparkJob
metadata:
  name: ingester-test-sparkjob
  namespace: ingester-test
  labels:
    test: ingester
spec:
  user:
    name: hkriplani
  driver:
    pod:
      name: ingester-test-driver
  executor:
    instances: 1
  mainApplicationFile: s3://default/spark-test.jar
  mainClass: com.example.SparkTest
  sparkVersion: "3.3.0"
