apiVersion: michelangelo.api/v2
kind: TriggerRun
metadata:
  name: ingester-test-triggerrun
  namespace: ingester-test
  labels:
    test: ingester
spec:
  pipeline:
    name: ingester-test-pipeline
    namespace: ingester-test
  trigger:
    cronSchedule:
      cron: "0 * * * *"
