apiVersion: michelangelo.api/v2
kind: Deployment
metadata:
  name: ingester-test-deployment
  namespace: ingester-test
  labels:
    test: ingester
spec:
  inferenceServer:
    name: ingester-test-inferenceserver
    namespace: ingester-test
