apiVersion: michelangelo.api/v2
kind: RayCluster
metadata:
  name: ingester-test-raycluster
  namespace: ingester-test
  labels:
    test: ingester
spec:
  user:
    name: hkriplani
  rayVersion: "2.9.0"
  head:
    rayStartParams:
      dashboard-host: "0.0.0.0"
  workers:
    - nodeType: default-worker
      minInstances: 1
      maxInstances: 2
