meta:
  workflow_version: 'v2'
  app: 'data.michelangelo.asl.app.retrain.RetrainModelPipeline'
  # params_file: 'params.yaml'
  params:
    default:
      base_deployment_name: 'exp-test'
      deployment_name: 'retrain-test'
      source_table: "michelangelo.dl_example_datasets_boston_housing_fp64_label"
      # Example DSL for dates
      # Check here : https://engwiki.uberinternal.com/display/TE0MICHELANGELO/Built-In+Functions
      # training_end_date: "{{DS(-30d)}}"
      # training_start_date: "{{DS(-60d)}}"
      training_end_date: "2016-01-02"
      training_start_date: "2016-01-01"

# data.michelangelo.asl.compile.TriggerConfig
triggers:
  weekly-01:
    cron: '0 05 * * *'
    batch_size: 2
    batch_interval: '50m'
    # Can add selected parameter keys to schedule. e.g. ['us']
    # If multiple keys are selected, then will be triggered considering batch_size and interval.
    # 2 retrain piepline runs every hour when 2 batch_size and 1 hr batch_interval.
    params: ['default']
    # params_exclude: ['default']  # Include all the rest except default

# data.michelangelo.asl.module.data_validation.DataValidationSpec
data_validation:
  meta:
    module: 'data.michelangelo.asl.module.data_validation.DataValidationModule'
  spec:
    sensor:
      - state_id: "data_sensor"
        table: '{{source_table}}'
        min_partition_count: 1
        partition_filter: "datestr >= '{{training_start_date}}' AND datestr < '{{training_end_date}}'"
        # Please use team's dedicated consumer service name to not stuck on the shared service (michelangelo_pipeline).
        # If not, see https://engwiki.uberinternal.com/display/TE0MICHELANGELO/Orchestration+Pipeline#OrchestrationPipeline-CreatingQueryRunnerConsumer
        qr_consumer: "michelangelo_pipeline"
        retry:
          interval: '31m'
          attempts: 3
    validation:
      - state_id: "data_validation_train"
        datasource_name: "presto"
        query_file_name: 'data_validation_query.sql'
        # Please use team's dedicated consumer service name to not stuck on the shared service (michelangelo_pipeline).
        # If not, see https://engwiki.uberinternal.com/display/TE0MICHELANGELO/Orchestration+Pipeline#OrchestrationPipeline-CreatingQueryRunnerConsumer
        qr_consumer: "michelangelo_pipeline"
        retry:
          interval: '30m'
          attempts: 1

# data.michelangelo.asl.module.retrain.TrainSpec.
retrainer:
  meta:
    module: 'data.michelangelo.asl.module.retrain.TrainModule'
  spec:
    - state_id: 'retrainer'
      pipeline:
        name: 'boston-housing-train-keras'
        # Use this to pin the specific revision. This only needs, emergency case with an issue with recent master train pipeline.
        # Here's an example
        # revision: '9445ca5bf50ee0c6857ac33999d707636fdeac4e'
        constant_overrides:
          feature_prep_spec.source.dataset.start_date: '{{training_start_date}}T00:00:00Z'
          feature_prep_spec.source.dataset.end_date: '{{training_end_date}}T00:00:00Z'
        # Default is 48 hours, tune to fit your expected timeout including waiting time for the compute resource
        timeout: '24h'

# data.michelangelo.asl.module.experiment.ExperimentSpec
offline_experiment:
  meta:
    module: 'data.michelangelo.asl.module.offline_experiment.OfflineExperimentModule'
  spec:
    - state_id: 'offline_experiment'
      pipeline:
        name: 'boston-housing-offline-experiment'
        # Use this to pin the specific revision. This only needs, emergency case with an issue with recent master train pipeline.
        # Here's an example
        # revision: '9445ca5bf50ee0c6857ac33999d707636fdeac4e'
        constant_overrides:
          feature_prep_spec_base_fp.source.dataset.start_date: '{{training_start_date}}T00:00:00Z'
          feature_prep_spec_base_fp.source.dataset.end_date: '{{training_end_date}}T00:00:00Z'
          scorer_spec_base_scorer.model_eval_specs:
            - deployment_name: '{{base_deployment_name}}'
          scorer_spec_exp_scorer.model_eval_specs:
            - model_name: '{{retrainer.pipeline.model.metadata.name}}'
          comparator_spec.baseline_deployment_names:
            - '{{base_deployment_name}}'
          comparator_spec.report_title: '{{base_deployment_name}}_{{training_start_date}}~{{training_end_date}}'
      hitl:
        reviewers: ['hwamin@uber.com']
        default_action: "PROCEED"
        timeout: '48h'

online_experiment:
  meta:
    module: 'data.michelangelo.asl.module.online_experiment.OnlineExperimentModule'
  spec:
    - state_id: 'online_experiment'
      deployment:
        deployment_name: retrain-xp
        model_name: '{{retrainer.pipeline.model.metadata.name}}'
        retry:
          interval: '5m'
          attempts: 4
        timeout: '24h'
      citrus_pipeline:
        name: citrus-example
        parameter_id: 'default'
        params:
          template_id: "test_experiment_template"
          experiment_id_prefix: "orchestration_test"
      experiment_pipeline:
        name: "boston-housing-online-experiment"
        constant_overrides: {}
        timeout: '6h'
      hitl:
        reviewers: ['yeqing@uber.com']
        timeout: '12h'
        default_action: "PROCEED"

# data.michelangelo.asl.module.deploy.DeploySpec
deployment:
  meta:
    module: 'data.michelangelo.asl.module.deploy.DeployModule'
  spec:
    - state_id: 'deployment'
      deployment_name: '{{deployment_name}}'
      # If you use deployment template,
      # template_name: 'retrain-prod-template'

# data.michelangelo.asl.module.post_processing.PostProcessingSpec
post_processing:
  meta:
    module: 'data.michelangelo.asl.module.post_processing.PostProcessingModule'
  spec:
    - state_id: 'post_processing'
      pipeline:
        name: 'boston-housing-post-processing'
        # Use this to pin the specific revision. This only needs, emergency case with an issue with recent master train pipeline.
        # Here's an example
        # revision: '9445ca5bf50ee0c6857ac33999d707636fdeac4e'
        constant_overrides:
          feature_prep_spec.source.spark_sql.params:
            datestr: '{{training_start_date}}'
