default:
  base_deployment_name: 'exp-test'
  deployment_name: 'retrain-test'
  source_table: "michelangelo.dl_example_datasets_boston_housing_fp64_label"
  # Example DSL for dates
  # Check here : https://engwiki.uberinternal.com/display/TE0MICHELANGELO/Built-In+Functions
  # training_end_date: "{{DS(-30d)}}"
  # training_start_date: "{{DS(-60d)}}"
  training_end_date: "2016-01-02"
  training_start_date: "2016-01-01"

# Can overrides subset of parameters that is defined in default
usa:
  deployment_name: 'retrain-usa'
  training_end_date: "{{DS(-2d)}}"
  training_start_date: "{{DS(-30d)}}"
