apiVersion: michelangelo.api/v2
kind: TriggerRun
metadata:
  name: training-pipeline-cron-trigger
  namespace: ma-dev-test
  annotations:
    description: "Test training pipeline execution via cron trigger"
spec:
  pipeline:
    name: training-pipeline
    namespace: ma-dev-test
  trigger:
    cronSchedule:
      cron: "0 8 * * *"  # Run every day at 8am
    # batchPolicy:
    #   batchSize: 1
    #   wait: "60s"
    maxConcurrency: 1
