apiVersion: michelangelo.api/v2
kind: Pipeline
metadata:
  name: training-pipeline
  namespace: ma-dev-test
  annotations:
   michelangelo/uniflow-image: ghcr.io/michelangelo-ai/examples:main
spec:
  description: Training pipeline for my ML project
  owner:
    name: craig.marker
  type: PIPELINE_TYPE_TRAIN
  manifest:
    type: PIPELINE_MANIFEST_TYPE_UNIFLOW
    uniflowTar: s3://default/bert_local.tar
  commit:
    gitRef: "main"
    branch: "main"
