apiVersion: v1
kind: Secret
metadata:
  name: storage-config
  namespace: default
type: Opaque
stringData:
  localMinIO: |
    {
      "access_key_id": "minioadmin",
      "secret_access_key": "minioadmin",
      "endpoint_url": "http://minio:9091",
      "region": "us-east-1"
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: inference-server-bert-cola-model-config
  namespace: default
  labels:
    app: inference-server
    inference-server: inference-server-bert-cola
data:
  model-list.json: "[]"