# this file is not in use
---
apiVersion: v1
kind: Secret
metadata:
  name: storage-config
  namespace: default
stringData:
  localMinIO: |
    {
      "type": "s3",
      "access_key_id": "minioadmin",
      "secret_access_key": "minioadmin",
      "endpoint_url": "http://minio:9091",
      "bucket": "deploy-models",
      "region": "us-south"
    }
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: triton-models
  namespace: default
data:
  model-list.json: |
    [
      {
        "name": "bert-cola-6",
        "s3_path": "s3://deploy-models/bert-cola-6"
      }
    ]
