apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: "fluent-bit"
  labels:
    k8s-app: "fluent-bit"
spec:
  selector:
    matchLabels:
      k8s-app: "fluent-bit"
  template:
    metadata:
      labels:
        k8s-app: "fluent-bit"
    spec:
      serviceAccountName: "fluent-bit"
      initContainers:
        - name: "fix-perms"
          image: "busybox"
          command: ["sh", "-c", "mkdir -p /tmp/ray /tmp/spark && chown -R 1000:1000 /tmp/ray /tmp/spark"]
          volumeMounts:
            - name: "ray"
              mountPath: "/tmp/ray"
            - name: "spark"
              mountPath: "/tmp/spark"
      containers:
        - name: "fluent-bit"
          image: "fluent/fluent-bit:3.2.7"
          args: ["-c", "/fluent-bit/etc/fluent-bit.conf"]
          env:
            - name: "AWS_ENDPOINT_URL"
              value: "http://minio:9091"
          volumeMounts:
            - name: "fluent-bit-plugins-volume"
              mountPath: "/fluent-bit/plugins"
            - name: "fluent-bit-config-volume"
              mountPath: "/fluent-bit/etc"
            - name: "aws-credentials-volume"
              mountPath: "/root/.aws"
            - name: "ray"
              mountPath: "/tmp/ray"
            - name: "spark"
              mountPath: "/tmp/spark"
            - name: "var-log"
              mountPath: "/var/log"
              readOnly: true
            - name: "var-lib-docker"
              mountPath: "/var/lib/docker/containers"
              readOnly: true
      volumes:
        - name: "fluent-bit-plugins-volume"
          emptyDir: { }
        - name: "fluent-bit-config-volume"
          configMap:
            name: "fluent-bit-config"
        - name: "aws-credentials-volume"
          secret:
            secretName: "aws-credentials"
        - name: "ray"
          hostPath:
            path: "/tmp/ray"
        - name: "spark"
          hostPath:
            path: "/tmp/spark"
        - name: "var-log"
          hostPath:
            path: "/var/log"
        - name: "var-lib-docker"
          hostPath:
            path: "/var/lib/docker/containers"
