apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "fluent-bit-config"
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush 1
        Log_Level info
        Daemon off

    # Ray job logs
    [INPUT]
        Name tail
        Path /tmp/ray/session_*/logs/job*.log
        Tag raylogs
        Refresh_Interval 5
        Read_from_Head true

    # Spark logs
    [INPUT]
        Name tail
        Path /tmp/spark/*.log
        Tag sparklogs
        Refresh_Interval 5
        Read_from_Head true

    # Spark event logs
    [INPUT]
        Name tail
        Path /tmp/spark/eventlogs/*
        Tag sparkevents
        Refresh_Interval 5
        Read_from_Head true

    # Output to S3/Minio
    [OUTPUT]
        Name s3
        Match *
        bucket logs
        region us-east-1
        endpoint http://minio:9091
        use_put_object On
        s3_key_format /fluent-bit-logs/%Y/%m/%d/%H/%M/%S
        auto_retry_requests true
