apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: default
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush 1
        Log_Level info
        Daemon off

    [INPUT]
        Name tail
        Path /tmp/ray/session_*/logs/job*.log
        Tag raylogs
        Refresh_Interval 5
        Read_from_Head true

    [OUTPUT]
        name                  loki
        Host                  loki.kube-system.svc.cluster.local
        Port                  3100
        labels                job=michelangelo
        auto_kubernetes_labels false
        line_format           json
