apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: "fluent-bit"
  labels:
    k8s-app: "fluent-bit"
spec:
  selector:
    matchLabels:
      k8s-app: "fluent-bit"
  template:
    metadata:
      labels:
        k8s-app: "fluent-bit"
    spec:
      serviceAccountName: "fluent-bit"
      containers:
        - name: "fluent-bit"
          image: "fluent/fluent-bit:3.2.7"
          args: ["-c", "/fluent-bit/etc/fluent-bit.yaml"]
          securityContext:
            runAsUser: 0
          env:
            - name: "AWS_ENDPOINT_URL"
              value: "http://minio:9091"
            - name: "AWS_ACCESS_KEY_ID"
              value: "minioadmin"
            - name: "AWS_SECRET_ACCESS_KEY"
              value: "minioadmin"
            - name: "AWS_DEFAULT_REGION"
              value: "us-east-1"
          volumeMounts:
            - name: "fluent-bit-config-volume"
              mountPath: "/fluent-bit/etc"
            - name: "aws-credentials-volume"
              mountPath: "/root/.aws"
            - name: "var-log-containers"
              mountPath: "/var/log/containers"
              readOnly: true
            - name: "var-log-pods"
              mountPath: "/var/log/pods"
              readOnly: true
      volumes:
        - name: "fluent-bit-config-volume"
          configMap:
            name: "fluent-bit-config"
        - name: "aws-credentials-volume"
          secret:
            secretName: "aws-credentials"
        - name: "var-log-containers"
          hostPath:
            path: "/var/log/containers"
        - name: "var-log-pods"
          hostPath:
            path: "/var/log/pods"
