apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: "fluent-bit"
  labels:
    k8s-app: "fluent-bit"
spec:
  selector:
    matchLabels:
      k8s-app: "fluent-bit"
  template:
    metadata:
      labels:
        k8s-app: "fluent-bit"
    spec:
      serviceAccountName: "fluent-bit"
      initContainers:
        # This will no longer be necessary once the plugin is merged with fluent-bit OSS project
        - name: "download-fluent-bit-plugin"
          image: "busybox"
          command: [
            "sh",
            "-c",
"wget -O /fluent-bit/plugins/out_clp_s3_v2_linux_amd64.so https://github.com/uber/michelangelo/raw/main/plugins/out_clp_s3_v2_linux_amd64.so && chmod 755 /fluent-bit/plugins/out_clp_s3_v2_linux_amd64.so && ls -lh /fluent-bit/plugins/"
          ]
          volumeMounts:
            - name: "fluent-bit-plugins-volume"
              mountPath: "/fluent-bit/plugins"
        - name: "fix-perms"
          image: "busybox"
          command: ["sh", "-c", "chown -R 1000:1000 /tmp/ray"]
          volumeMounts:
            - name: "ray"
              mountPath: "/tmp/ray"
      containers:
        - name: "fluent-bit"
          image: "fluent/fluent-bit:3.2.7"
          args: ["-c", "/fluent-bit/etc/fluent-bit.yaml"]
          env:
            - name: "AWS_ENDPOINT_URL"
              value: "http://minio:9091"
          volumeMounts:
            - name: "fluent-bit-plugins-volume"
              mountPath: "/fluent-bit/plugins"
            - name: "fluent-bit-config-volume"
              mountPath: "/fluent-bit/etc"
            - name: "aws-credentials-volume"
              mountPath: "/root/.aws"
            - name: "ray"
              mountPath: "/tmp/ray"
      volumes:
        - name: "fluent-bit-plugins-volume"
          emptyDir: { }
        - name: "fluent-bit-config-volume"
          configMap:
            name: "fluent-bit-config"
        - name: "aws-credentials-volume"
          secret:
            secretName: "aws-credentials"
        - name: "ray"
          hostPath:
            path: "/tmp/ray"
