apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "fluent-bit-config"
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        false

    [INPUT]
        Name              tail
        Path              /tmp/spark-logs/*.log
        Tag               spark-logs
        Refresh_Interval  5
        Read_from_Head    true

    [INPUT]
        Name              tail
        Path              /tmp/spark/eventlogs/*
        Tag               spark-events
        Refresh_Interval  5
        Read_from_Head    true

    [OUTPUT]
        Name                  s3
        Match                 *
        bucket                logs
        region                us-east-1
        endpoint              http://minio:9091
        use_put_object        true
        s3_key_format         /${JOB_NAME}/spark.log
        auto_retry_requests   true
