apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: triton-cpu-model
  namespace: default
spec:
  predictor:
    annotations:
      model: "bert-cola"
    triton:
      runtimeVersion: 24.04-py3
      resources:
        requests:
          cpu: "1"
          memory: "2Gi"
        limits:
          cpu: "1"
          memory: "2Gi"

#      storageUri: "s3://deploy-models/bert-cola"
      storage:
        key: localMinIO
        path: bert_cola/revision2
        parameters:
          bucket: deploy-models
