---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: michelangelo-worker
  labels:
    app: michelangelo-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: michelangelo-worker
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::095116963143:role/chimera/michelangelo_role
      labels:
        app: michelangelo-worker
    spec:
      containers:
        - name: app
          image: 095116963143.dkr.ecr.ap-southeast-1.amazonaws.com/michelangelo-ai/worker:grab-poc
          volumeMounts:
            - name: worker-config-volume
              mountPath: /config
      volumes:
        - name: worker-config-volume
          configMap:
            name: michelangelo-worker-config
      nodeSelector:
        node.kubernetes.io/scaling-group: nodes
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: michelangelo-worker-config
  labels:
    app: michelangelo-worker
data:
  base.yaml: |
    worker:
      address: michelangelo-apiserver:14566
      maApiServiceName: ma-apiserver
      rayHttp:
        baseUrl: https://compute.cauldron.myteksi.net  # Base URL for Ray HTTP API
        workspace: cauldron-test
        environment: dev

    logging:
      level: info
      development: true
      encoding: console

    workflow-engine:
      # for temporal
        host: temporal.stg-myteksi.com:7233
        transport: grpc
        # for temporal
        provider: temporal
        workers:
          - domain: default
            taskList: zhou-xian
        client:
          domain: uniflow

    minio:
      awsRegion: ap-southeast-1
      awsEndpointUrl: s3.ap-southeast-1.amazonaws.com
      useIam: true
