apiVersion: apps/v1
kind: Deployment
metadata:
  name: michelangelo-apiserver
  labels:
    app: michelangelo-apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: michelangelo-apiserver
  template:
    metadata:
      labels:
        app: michelangelo-apiserver
    spec:
      containers:
        - name: michelangelo-apiserver
          image: 095116963143.dkr.ecr.ap-southeast-1.amazonaws.com/michelangelo-ai/apiserver:main
          ports:
            - containerPort: 14566
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: michelangelo-apiserver-config
      nodeSelector:
        node.kubernetes.io/scaling-group: nodes
---
apiVersion: v1
kind: Service
metadata:
  name: michelangelo-apiserver
  labels:
    app: michelangelo-apiserver
spec:
  type: NodePort
  selector:
    app: michelangelo-apiserver
  ports:
    - name: "14566"
      port: 14566 # port export to the k8s cluster
      nodePort: 30009 # port export to the external world
      targetPort: 14566 # port inside the container
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: michelangelo-apiserver-config
  labels:
    app: michelangelo-apiserver
data:
  base.yaml: |
    apiserver:
      yarpc:
        host: 0.0.0.0
        port: 14566
      k8s:
        qps: 300
        burst: 600
      metadataStorage:
        enableMetadataStorage: false
      crdSync:
        enableCRDUpdate: true
        enableIncompatibleUpdate: false
