---
apiVersion: v1
kind: Pod
metadata:
  name: michelangelo-controllermgr
  labels:
    app: michelangelo-controllermgr
spec:
  containers:
    - name: app
      image: ghcr.io/michelangelo-ai/controllermgr:main
      volumeMounts:
        - name: config-volume
          mountPath: /config
  volumes:
    - name: config-volume
      configMap:
        name: michelangelo-controllermgr-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: michelangelo-controllermgr-config
  labels:
    app: michelangelo-controllermgr
data:
  base.yaml: |
    controllermgr:
      metricsBindAddress: ${METRICS_ADDRESS::8080}
      healthProbeBindAddress: ${HEALTH_ADDRESS::8081}
      leaderElection: false
      leaderElectionID: decaf1259.michelangelo.uber.com
      port: 9443

    crdSync:
      syncInterval: 5m

    controllers:
      rayCluster:
        k8sQps: 300
        k8sBurst: 600

    minio:
      awsRegion: us-east-1
      awsAccessKeyId: minioadmin
      awsSecretAccessKey: minioadmin
      awsEndpointUrl: minio:9091

    workflowClient:
      service: cadence-frontend
      host: cadence:7833
      transport: grpc
      domain: default
