apiVersion: v1
kind: Pod
metadata:
  name: michelangelo-apiserver
  labels:
    app: michelangelo-apiserver
spec:
  containers:
    - name: michelangelo-apiserver
      image: ghcr.io/michelangelo-ai/apiserver:main
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 14566
      volumeMounts:
        - name: config-volume
          mountPath: /config
  volumes:
    - name: config-volume
      configMap:
        name: michelangelo-apiserver-config
---
apiVersion: v1
kind: Service
metadata:
  name: michelangelo-apiserver
  labels:
    app: michelangelo-apiserver
spec:
  type: NodePort
  selector:
    app: michelangelo-apiserver
  ports:
    - name: "14566"
      port: 14566 # port export to the k8s cluster
      nodePort: 30009 # port export to the external world
      targetPort: 14566 # port inside the container
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: michelangelo-apiserver-config
  labels:
    app: michelangelo-apiserver
data:
  base.yaml: |
    apiserver:
      yarpc:
        host: 0.0.0.0
        port: 14566
      k8s:
        qps: 300
        burst: 600
      metadataStorage:
        enableMetadataStorage: false
      crdSync:
        enableCRDUpdate: true
