---
apiVersion: v1
kind: ConfigMap
metadata:
  name: michelangelo-config
data:
  MA_FILE_SYSTEM: s3://default
  MA_FILE_SYSTEM_S3_SCHEME: http
  AWS_ACCESS_KEY_ID: ma-minio
  AWS_SECRET_ACCESS_KEY: g0Sfr9hRcsfRXuBS
  AWS_ENDPOINT_URL: http://minio:9091
