---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: michelangelo-controllermgr
  labels:
    app: michelangelo-controllermgr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: michelangelo-controllermgr
  template:
    metadata:
      labels:
        app: michelangelo-controllermgr
    spec:
      containers:
        - name: app
          image: 095116963143.dkr.ecr.ap-southeast-1.amazonaws.com/michelangelo-ai/controllermgr:main
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: michelangelo-controllermgr-config
      nodeSelector:
        node.kubernetes.io/scaling-group: nodes
---
apiVersion: v1
kind: Service
metadata:
  name: michelangelo-controllermgr
  labels:
    app: michelangelo-controllermgr
spec:
  selector:
    app: michelangelo-controllermgr
  ports:
  - name: metrics
    port: 8091
    targetPort: 8091
  - name: health
    port: 8081
    targetPort: 8081
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: michelangelo-controllermgr-config
  labels:
    app: michelangelo-controllermgr
data:
  base.yaml: |
    controllermgr:
      metricsBindAddress: ${METRICS_ADDRESS::8091}
      healthProbeBindAddress: ${HEALTH_ADDRESS::8081}
      leaderElection: false
      leaderElectionID: decaf1259.michelangelo.uber.com
      port: 9443

    controllers:
      rayCluster:
        k8sQps: 300
        k8sBurst: 600

    minio:
      awsRegion: ap-southeast-1
      awsAccessKeyId: ASIARMJLJVVD4CDUUBT2
      awsSecretAccessKey: hFK6a1OVUwzGw2D8XTX8hyMOb7VpUBOT9EjOCxsU
    #  awsSessionToken: IQoJb3JpZ2luX2VjELH//////////wEaDmFwLXNvdXRoZWFzdC0xIkgwRgIhAKnA1erEJat7QV/bRdnu80+680quunN32hvBqfVe6lNQAiEA3aI+sul1kDhIrshkIDXufhOmh2L5BrKC/gpB20vfUNUqtAMIuv//////////ARAEGgwwOTUxMTY5NjMxNDMiDGFckSkE1+BFPvndBiqIAw7oaHoB7eEhO2clVwvkhzR9402Zwvvn6B0Cj3VM1zOXMjjjeGMU6GrejqK+YjmoWPSJRlxFWAyU4SdWQUOExikYQdZeI5RNIJYPLOmXUF1mrl3yUA125iMBq2wGzBcnWYnjNBObbIoHRkPH7rsCyCI04l6KQtya9q6StP62NM2jd/7m/f6Eu3Kp30fPbVRBzdAowY4rkRlc3gbnYkzUZUabD57txKzZoLj9zy71XHFuJShiY4MZ5Z1Stt9jJGKeDIA8YjXOdmVSuvPbVBYTfkWfptYMAKHjgU8KjrqPNscr54Paq6zCstA1RTBrLup6cK0X+GyzfsTmHtKh0VhHmW6DAvxUx+E9+XyEckpqM7ExXZEvp12vyfvL90jo7bWmUoB2Q/y3kEA5NQqDxE/GYimMCutbnbYs3H7AwYCC3UziMFt0nwcA79YEWlB2Wuoc/L2sFf+2xh4eM1VOEKq3i/G+EdFFqKgjwn0VzkQ2GdKDOKAKpRuC2B9SPNDyS0dtL0OLIMmAEAOSMI2KvsMGOqUBv7JG0MdUon+DJDwuQRtGE7+plXmeiFO/CeY5i3B+jq/ONunlOx4/bQm3EkvWQyj/2nUzOzw7MLvTNEdIuaiYuVjVQ7hlRDuGJo8X7atiPRA5FGDHee9elr2fV/j+Px52Eui09lq8s+ZOQqbsL2boSnTk3iwCnz3EbV7CNxPAPrZjiiH+zbaGIIaulT3wIrlT8aV8v1oecedXcxlgBZa6qizg7xEB
      awsEndpointUrl: chimeracli-gate
    
    workflowClient:
      service: cadence-frontend
      host: cadence:7833
      transport: grpc
      domain: default
