---
apiVersion: v1
kind: Pod
metadata:
  name: michelangelo-controllermgr
  labels:
    app: michelangelo-controllermgr
spec:
  containers:
    - name: app
      image: ghcr.io/michelangelo-ai/controllermgr:npuppala-per-task-status-tracking
      volumeMounts:
        - name: config-volume
          mountPath: /config
  volumes:
    - name: config-volume
      configMap:
        name: michelangelo-controllermgr-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: michelangelo-controllermgr-config
  labels:
    app: michelangelo-controllermgr
data:
  base.yaml: |
    controllermgr:
      metricsBindAddress: ${METRICS_ADDRESS::8080}
      healthProbeBindAddress: ${HEALTH_ADDRESS::8081}
      leaderElection: false
      leaderElectionID: decaf1259.michelangelo.uber.com
      port: 9443

    controllers:
      rayCluster:
        k8sQps: 300
        k8sBurst: 600

    minio:
      awsRegion: us-east-1
      awsAccessKeyId: minioadmin
      awsSecretAccessKey: minioadmin
      awsEndpointUrl: minio:9091
    
    workflowClient:
      service: temporal-frontend
      host: 127.0.0.1:7233
      transport: grpc
      domain: default
