apiVersion: v1
kind: ConfigMap
metadata:
  name: bert-cola-inference-server-config
data:
  model-list.json: |
    [
      {
        "name": "bert-cola-6",
        "s3_path": "s3://deploy-models/bert-cola-6"
      },
      {
        "name": "bert-cola-6",
        "s3_path": "s3://deploy-models/bert-cola-6"
      }
    ]