apiVersion: v1
kind: ServiceAccount
metadata:
  name: ray-manager
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
# ClusterRole for Spark/Ray jobs across namespaces; one federated client uses a single ServiceAccount secret to create jobs in multiple namespaces.
kind: ClusterRole
metadata:
  name: ray-manager
rules:
- apiGroups: ["ray.io"]
  resources: ["rayclusters", "rayjobs"]
  verbs: ["create","get","list","watch","update","patch","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ray-manager-binding
subjects:
- kind: ServiceAccount
  name: ray-manager
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ray-manager
