apiVersion: v1
kind: ConfigMap
metadata:
  name: seaweedfs-s3-config
data:
  s3_config.json: |
    {
      "identities": [
        {
          "name": "michelangeloadmin",
          "credentials": [
            {
              "accessKey": "minioadmin",
              "secretKey": "minioadmin"
            }
          ],
          "actions": ["Admin", "Read", "Write"]
        }
      ]
    }
