apiVersion: v1
stringData:
  localMinIO: |
    {
      "type": "s3",
      "access_key_id": "minioadmin",
      "secret_access_key": "minioadmin",
      "endpoint_url": "http://minio:9091",
      "bucket": "deploy-models",
      "region": "us-south"
    }
kind: Secret
metadata:
  name: storage-config
type: Opaque