apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: staging-

replicas:
  - name: michelangelo-apiserver
    count: 2
  - name: michelangelo-controllermgr
    count: 1
  - name: michelangelo-worker
    count: 2

images:
  - name: ghcr.io/michelangelo-ai/apiserver
    newTag: v1.0.0-rc
  - name: ghcr.io/michelangelo-ai/controller-manager
    newTag: v1.0.0-rc
  - name: ghcr.io/michelangelo-ai/worker
    newTag: v1.0.0-rc
  - name: ghcr.io/michelangelo-ai/ui
    newTag: v1.0.0-rc

commonLabels:
  environment: staging