// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: michelangelo/test/api/v2alpha1/project.proto

package v2alpha1

import (
	"bytes"
	"encoding/json"
	"github.com/gogo/protobuf/jsonpb"
	"github.com/michelangelo-ai/michelangelo/go/kubeproto/util"
	"github.com/michelangelo-ai/michelangelo/go/storage"
	k8sruntime "k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"

	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_sortkeys "github.com/gogo/protobuf/sortkeys"
	types "github.com/gogo/protobuf/types"
	_ "github.com/michelangelo-ai/michelangelo/proto-go/api"
	_ "github.com/michelangelo-ai/michelangelo/proto-go/api/v2"
	io "io"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strconv "strconv"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type NotificationControl int32

const (
	NOTIFICATION_CONTROL_INVALID                     NotificationControl = 0
	NOTIFICATION_CONTROL_PROJECT_OWNER_AND_USER_TEAM NotificationControl = 1
	NOTIFICATION_CONTROL_PROJECT_OWNER_ONLY          NotificationControl = 2
	NOTIFICATION_CONTROL_NOTIFICATION_OFF            NotificationControl = 3
)

var NotificationControl_name = map[int32]string{
	0: "NOTIFICATION_CONTROL_INVALID",
	1: "NOTIFICATION_CONTROL_PROJECT_OWNER_AND_USER_TEAM",
	2: "NOTIFICATION_CONTROL_PROJECT_OWNER_ONLY",
	3: "NOTIFICATION_CONTROL_NOTIFICATION_OFF",
}

var NotificationControl_value = map[string]int32{
	"NOTIFICATION_CONTROL_INVALID":                     0,
	"NOTIFICATION_CONTROL_PROJECT_OWNER_AND_USER_TEAM": 1,
	"NOTIFICATION_CONTROL_PROJECT_OWNER_ONLY":          2,
	"NOTIFICATION_CONTROL_NOTIFICATION_OFF":            3,
}

func (NotificationControl) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c473e22d54a76aa7, []int{0}
}

type ProjectState int32

const (
	PROJECT_STATE_INVALID           ProjectState = 0
	PROJECT_STATE_PROVISIONING      ProjectState = 1
	PROJECT_STATE_PROVISION_PENDING ProjectState = 2
	PROJECT_STATE_READY             ProjectState = 3
	PROJECT_STATE_ERROR             ProjectState = 4
)

var ProjectState_name = map[int32]string{
	0: "PROJECT_STATE_INVALID",
	1: "PROJECT_STATE_PROVISIONING",
	2: "PROJECT_STATE_PROVISION_PENDING",
	3: "PROJECT_STATE_READY",
	4: "PROJECT_STATE_ERROR",
}

var ProjectState_value = map[string]int32{
	"PROJECT_STATE_INVALID":           0,
	"PROJECT_STATE_PROVISIONING":      1,
	"PROJECT_STATE_PROVISION_PENDING": 2,
	"PROJECT_STATE_READY":             3,
	"PROJECT_STATE_ERROR":             4,
}

func (ProjectState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c473e22d54a76aa7, []int{1}
}

type ProjectPhase int32

const (
	PROJECT_PHASE_INVALID      ProjectPhase = 0
	PROJECT_PHASE_DEVELOPMENT  ProjectPhase = 1
	PROJECT_PHASE_STAGING      ProjectPhase = 2
	PROJECT_PHASE_PRODUCTION   ProjectPhase = 3
	PROJECT_PHASE_DECOMMISSION ProjectPhase = 4
)

var ProjectPhase_name = map[int32]string{
	0: "PROJECT_PHASE_INVALID",
	1: "PROJECT_PHASE_DEVELOPMENT",
	2: "PROJECT_PHASE_STAGING",
	3: "PROJECT_PHASE_PRODUCTION",
	4: "PROJECT_PHASE_DECOMMISSION",
}

var ProjectPhase_value = map[string]int32{
	"PROJECT_PHASE_INVALID":      0,
	"PROJECT_PHASE_DEVELOPMENT":  1,
	"PROJECT_PHASE_STAGING":      2,
	"PROJECT_PHASE_PRODUCTION":   3,
	"PROJECT_PHASE_DECOMMISSION": 4,
}

func (ProjectPhase) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c473e22d54a76aa7, []int{2}
}

type OwnerInfo struct {
	OwningTeam  string   `protobuf:"bytes,1,opt,name=owning_team,json=owningTeam,proto3" json:"owningTeam,omitempty"`
	Owners      []string `protobuf:"bytes,2,rep,name=owners,proto3" json:"owners,omitempty"`
	OwnerGroups []string `protobuf:"bytes,3,rep,name=owner_groups,json=ownerGroups,proto3" json:"ownerGroups,omitempty"`
}

func (m *OwnerInfo) Reset()      { *m = OwnerInfo{} }
func (*OwnerInfo) ProtoMessage() {}
func (*OwnerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c473e22d54a76aa7, []int{0}
}
func (m *OwnerInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OwnerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OwnerInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OwnerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OwnerInfo.Merge(m, src)
}
func (m *OwnerInfo) XXX_Size() int {
	return m.Size()
}
func (m *OwnerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OwnerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OwnerInfo proto.InternalMessageInfo

func (m *OwnerInfo) GetOwningTeam() string {
	if m != nil {
		return m.OwningTeam
	}
	return ""
}

func (m *OwnerInfo) GetOwners() []string {
	if m != nil {
		return m.Owners
	}
	return nil
}

func (m *OwnerInfo) GetOwnerGroups() []string {
	if m != nil {
		return m.OwnerGroups
	}
	return nil
}

type Retention struct {
	RetentionInDays int32 `protobuf:"varint,1,opt,name=retention_in_days,json=retentionInDays,proto3" json:"retentionInDays,omitempty"`
}

func (m *Retention) Reset()      { *m = Retention{} }
func (*Retention) ProtoMessage() {}
func (*Retention) Descriptor() ([]byte, []int) {
	return fileDescriptor_c473e22d54a76aa7, []int{1}
}
func (m *Retention) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Retention) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Retention.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Retention) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Retention.Merge(m, src)
}
func (m *Retention) XXX_Size() int {
	return m.Size()
}
func (m *Retention) XXX_DiscardUnknown() {
	xxx_messageInfo_Retention.DiscardUnknown(m)
}

var xxx_messageInfo_Retention proto.InternalMessageInfo

func (m *Retention) GetRetentionInDays() int32 {
	if m != nil {
		return m.RetentionInDays
	}
	return 0
}

type RetentionConfig struct {
	OnlineDeploymentRetention  *Retention          `protobuf:"bytes,1,opt,name=online_deployment_retention,json=onlineDeploymentRetention,proto3" json:"onlineDeploymentRetention,omitempty"`
	OfflineDeploymentRetention *Retention          `protobuf:"bytes,2,opt,name=offline_deployment_retention,json=offlineDeploymentRetention,proto3" json:"offlineDeploymentRetention,omitempty"`
	EndpointRetention          *Retention          `protobuf:"bytes,3,opt,name=endpoint_retention,json=endpointRetention,proto3" json:"endpointRetention,omitempty"`
	ModelRetention             *Retention          `protobuf:"bytes,4,opt,name=model_retention,json=modelRetention,proto3" json:"modelRetention,omitempty"`
	NotificationControl        NotificationControl `protobuf:"varint,10,opt,name=notification_control,json=notificationControl,proto3,enum=michelangelo.api.v2alpha1.NotificationControl" json:"notificationControl,omitempty"`
}

func (m *RetentionConfig) Reset()      { *m = RetentionConfig{} }
func (*RetentionConfig) ProtoMessage() {}
func (*RetentionConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_c473e22d54a76aa7, []int{2}
}
func (m *RetentionConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RetentionConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RetentionConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RetentionConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetentionConfig.Merge(m, src)
}
func (m *RetentionConfig) XXX_Size() int {
	return m.Size()
}
func (m *RetentionConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_RetentionConfig.DiscardUnknown(m)
}

var xxx_messageInfo_RetentionConfig proto.InternalMessageInfo

func (m *RetentionConfig) GetOnlineDeploymentRetention() *Retention {
	if m != nil {
		return m.OnlineDeploymentRetention
	}
	return nil
}

func (m *RetentionConfig) GetOfflineDeploymentRetention() *Retention {
	if m != nil {
		return m.OfflineDeploymentRetention
	}
	return nil
}

func (m *RetentionConfig) GetEndpointRetention() *Retention {
	if m != nil {
		return m.EndpointRetention
	}
	return nil
}

func (m *RetentionConfig) GetModelRetention() *Retention {
	if m != nil {
		return m.ModelRetention
	}
	return nil
}

func (m *RetentionConfig) GetNotificationControl() NotificationControl {
	if m != nil {
		return m.NotificationControl
	}
	return NOTIFICATION_CONTROL_INVALID
}

type ProjectTypeInfo struct {
	IsCoreMl       bool `protobuf:"varint,1,opt,name=is_core_ml,json=isCoreMl,proto3" json:"isCoreMl,omitempty"`
	IsGenerativeAi bool `protobuf:"varint,2,opt,name=is_generative_ai,json=isGenerativeAi,proto3" json:"isGenerativeAi,omitempty"`
}

func (m *ProjectTypeInfo) Reset()      { *m = ProjectTypeInfo{} }
func (*ProjectTypeInfo) ProtoMessage() {}
func (*ProjectTypeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c473e22d54a76aa7, []int{3}
}
func (m *ProjectTypeInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProjectTypeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProjectTypeInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProjectTypeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectTypeInfo.Merge(m, src)
}
func (m *ProjectTypeInfo) XXX_Size() int {
	return m.Size()
}
func (m *ProjectTypeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectTypeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectTypeInfo proto.InternalMessageInfo

func (m *ProjectTypeInfo) GetIsCoreMl() bool {
	if m != nil {
		return m.IsCoreMl
	}
	return false
}

func (m *ProjectTypeInfo) GetIsGenerativeAi() bool {
	if m != nil {
		return m.IsGenerativeAi
	}
	return false
}

type ProjectSpec struct {
	ProjectDescription string            `protobuf:"bytes,1,opt,name=project_description,json=projectDescription,proto3" json:"projectDescription,omitempty"`
	Owner              *OwnerInfo        `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Tier               int32             `protobuf:"varint,3,opt,name=tier,proto3" json:"tier,omitempty"`
	GitRepo            string            `protobuf:"bytes,4,opt,name=git_repo,json=gitRepo,proto3" json:"gitRepo,omitempty"`
	RootDir            string            `protobuf:"bytes,5,opt,name=root_dir,json=rootDir,proto3" json:"rootDir,omitempty"`
	LegacyAlphaConfig  string            `protobuf:"bytes,20,opt,name=legacy_alpha_config,json=legacyAlphaConfig,proto3" json:"legacyAlphaConfig,omitempty"`
	Commit             *CommitInfo       `protobuf:"bytes,7,opt,name=commit,proto3" json:"commit,omitempty"`
	SupportingLinks    map[string]string `protobuf:"bytes,8,rep,name=supporting_links,json=supportingLinks,proto3" json:"supportingLinks,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	RetentionConfig    *RetentionConfig  `protobuf:"bytes,9,opt,name=retention_config,json=retentionConfig,proto3" json:"retentionConfig,omitempty"`
}

func (m *ProjectSpec) Reset()      { *m = ProjectSpec{} }
func (*ProjectSpec) ProtoMessage() {}
func (*ProjectSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_c473e22d54a76aa7, []int{4}
}
func (m *ProjectSpec) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProjectSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProjectSpec.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProjectSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectSpec.Merge(m, src)
}
func (m *ProjectSpec) XXX_Size() int {
	return m.Size()
}
func (m *ProjectSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectSpec proto.InternalMessageInfo

func (m *ProjectSpec) GetProjectDescription() string {
	if m != nil {
		return m.ProjectDescription
	}
	return ""
}

func (m *ProjectSpec) GetOwner() *OwnerInfo {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *ProjectSpec) GetTier() int32 {
	if m != nil {
		return m.Tier
	}
	return 0
}

func (m *ProjectSpec) GetGitRepo() string {
	if m != nil {
		return m.GitRepo
	}
	return ""
}

func (m *ProjectSpec) GetRootDir() string {
	if m != nil {
		return m.RootDir
	}
	return ""
}

func (m *ProjectSpec) GetLegacyAlphaConfig() string {
	if m != nil {
		return m.LegacyAlphaConfig
	}
	return ""
}

func (m *ProjectSpec) GetCommit() *CommitInfo {
	if m != nil {
		return m.Commit
	}
	return nil
}

func (m *ProjectSpec) GetSupportingLinks() map[string]string {
	if m != nil {
		return m.SupportingLinks
	}
	return nil
}

func (m *ProjectSpec) GetRetentionConfig() *RetentionConfig {
	if m != nil {
		return m.RetentionConfig
	}
	return nil
}

type ProjectStatus struct {
	State          ProjectState     `protobuf:"varint,1,opt,name=state,proto3,enum=michelangelo.api.v2alpha1.ProjectState" json:"state,omitempty"`
	Phase          ProjectPhase     `protobuf:"varint,2,opt,name=phase,proto3,enum=michelangelo.api.v2alpha1.ProjectPhase" json:"phase,omitempty"`
	ErrorMessage   string           `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"errorMessage,omitempty"`
	LastUpdateTime *types.Timestamp `protobuf:"bytes,4,opt,name=last_update_time,json=lastUpdateTime,proto3" json:"lastUpdateTime,omitempty"`
}

func (m *ProjectStatus) Reset()      { *m = ProjectStatus{} }
func (*ProjectStatus) ProtoMessage() {}
func (*ProjectStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_c473e22d54a76aa7, []int{5}
}
func (m *ProjectStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProjectStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProjectStatus.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProjectStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectStatus.Merge(m, src)
}
func (m *ProjectStatus) XXX_Size() int {
	return m.Size()
}
func (m *ProjectStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectStatus proto.InternalMessageInfo

func (m *ProjectStatus) GetState() ProjectState {
	if m != nil {
		return m.State
	}
	return PROJECT_STATE_INVALID
}

func (m *ProjectStatus) GetPhase() ProjectPhase {
	if m != nil {
		return m.Phase
	}
	return PROJECT_PHASE_INVALID
}

func (m *ProjectStatus) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *ProjectStatus) GetLastUpdateTime() *types.Timestamp {
	if m != nil {
		return m.LastUpdateTime
	}
	return nil
}

func (m *Project) Reset()      { *m = Project{} }
func (*Project) ProtoMessage() {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_c473e22d54a76aa7, []int{6}
}
func (m *Project) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Project.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(m, src)
}
func (m *Project) XXX_Size() int {
	return m.Size()
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *ProjectList) Reset()      { *m = ProjectList{} }
func (*ProjectList) ProtoMessage() {}
func (*ProjectList) Descriptor() ([]byte, []int) {
	return fileDescriptor_c473e22d54a76aa7, []int{7}
}
func (m *ProjectList) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProjectList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProjectList.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProjectList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectList.Merge(m, src)
}
func (m *ProjectList) XXX_Size() int {
	return m.Size()
}
func (m *ProjectList) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectList.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectList proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("michelangelo.api.v2alpha1.NotificationControl", NotificationControl_name, NotificationControl_value)
	proto.RegisterEnum("michelangelo.api.v2alpha1.ProjectState", ProjectState_name, ProjectState_value)
	proto.RegisterEnum("michelangelo.api.v2alpha1.ProjectPhase", ProjectPhase_name, ProjectPhase_value)
	proto.RegisterType((*OwnerInfo)(nil), "michelangelo.api.v2alpha1.OwnerInfo")
	proto.RegisterType((*Retention)(nil), "michelangelo.api.v2alpha1.Retention")
	proto.RegisterType((*RetentionConfig)(nil), "michelangelo.api.v2alpha1.RetentionConfig")
	proto.RegisterType((*ProjectTypeInfo)(nil), "michelangelo.api.v2alpha1.ProjectTypeInfo")
	proto.RegisterType((*ProjectSpec)(nil), "michelangelo.api.v2alpha1.ProjectSpec")
	proto.RegisterMapType((map[string]string)(nil), "michelangelo.api.v2alpha1.ProjectSpec.SupportingLinksEntry")
	proto.RegisterType((*ProjectStatus)(nil), "michelangelo.api.v2alpha1.ProjectStatus")
	proto.RegisterType((*Project)(nil), "michelangelo.api.v2alpha1.Project")
	proto.RegisterType((*ProjectList)(nil), "michelangelo.api.v2alpha1.ProjectList")
}

func init() {
	proto.RegisterFile("michelangelo/test/api/v2alpha1/project.proto", fileDescriptor_c473e22d54a76aa7)
}

var fileDescriptor_c473e22d54a76aa7 = []byte{
	// 1345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x4f, 0x6f, 0xdb, 0xc6,
	0x12, 0x17, 0x25, 0x4b, 0x96, 0x46, 0x89, 0x4d, 0xaf, 0xfd, 0xde, 0x93, 0xf5, 0xfc, 0x18, 0x47,
	0x79, 0x69, 0x54, 0xb7, 0xa0, 0x62, 0x37, 0x40, 0x03, 0x07, 0x05, 0xa2, 0x7f, 0x76, 0x95, 0x5a,
	0xa2, 0xb0, 0x52, 0x52, 0xa4, 0x87, 0x12, 0x8c, 0xb4, 0xa2, 0xb7, 0x96, 0xb8, 0x04, 0xb9, 0x76,
	0xa0, 0x5b, 0xd1, 0x63, 0xd1, 0x43, 0x3e, 0x42, 0x7b, 0x0b, 0x7a, 0xea, 0x27, 0xe8, 0xad, 0x40,
	0x8f, 0x41, 0x4e, 0x39, 0x36, 0x0e, 0x5a, 0xf8, 0x98, 0x63, 0x91, 0x53, 0xb1, 0x4b, 0x4a, 0x96,
	0x6a, 0x27, 0x51, 0x80, 0xde, 0xb8, 0x33, 0xf3, 0xfb, 0xed, 0xfc, 0xdb, 0x19, 0xc2, 0x87, 0x03,
	0xda, 0xd9, 0x27, 0x7d, 0xcb, 0xb1, 0x49, 0x9f, 0x15, 0x38, 0xf1, 0x79, 0xc1, 0x72, 0x69, 0xe1,
	0x68, 0xcb, 0xea, 0xbb, 0xfb, 0xd6, 0x66, 0xc1, 0xf5, 0xd8, 0x57, 0xa4, 0xc3, 0x75, 0xd7, 0x63,
	0x9c, 0xa1, 0xd5, 0x49, 0x6b, 0xdd, 0x72, 0xa9, 0x3e, 0x32, 0xcc, 0x5e, 0xb2, 0x19, 0xb3, 0xfb,
	0xa4, 0x20, 0x0d, 0x1f, 0x1c, 0xf6, 0x0a, 0x9c, 0x0e, 0x88, 0xcf, 0xad, 0x81, 0x1b, 0x60, 0xb3,
	0x37, 0x0e, 0x6e, 0xfa, 0x3a, 0x65, 0x82, 0x7e, 0x60, 0x75, 0xf6, 0xa9, 0x43, 0xbc, 0x61, 0xc1,
	0x3d, 0xb0, 0x85, 0xc0, 0x2f, 0x0c, 0x08, 0xb7, 0x0a, 0x47, 0x9b, 0x05, 0x9b, 0x38, 0xc4, 0xb3,
	0x38, 0xe9, 0x86, 0x28, 0x6d, 0xca, 0x3f, 0xe1, 0x1a, 0x73, 0x39, 0x65, 0x8e, 0x1f, 0xea, 0xf3,
	0x6f, 0xf1, 0xdf, 0xa6, 0xa1, 0xef, 0xd9, 0xcb, 0x67, 0x98, 0x8e, 0xb6, 0xa6, 0xc3, 0xcb, 0xb9,
	0x90, 0x32, 0x1e, 0x3a, 0xc4, 0xab, 0x39, 0x3d, 0x86, 0xf2, 0x90, 0x66, 0x0f, 0x1d, 0xea, 0xd8,
	0x26, 0x27, 0xd6, 0x20, 0xa3, 0xac, 0x2b, 0xf9, 0x54, 0x69, 0xfe, 0xe9, 0x49, 0x34, 0x76, 0x82,
	0x14, 0x0c, 0x81, 0xae, 0x4d, 0xac, 0x01, 0xfa, 0x37, 0x24, 0x98, 0x80, 0xf9, 0x99, 0xe8, 0x7a,
	0x2c, 0x9f, 0xc2, 0xe1, 0x09, 0x5d, 0x86, 0x0b, 0xf2, 0xcb, 0xb4, 0x3d, 0x76, 0xe8, 0xfa, 0x99,
	0x98, 0xd4, 0xa6, 0xa5, 0x6c, 0x57, 0x8a, 0x72, 0x1f, 0x43, 0x0a, 0x13, 0x4e, 0x1c, 0x11, 0x12,
	0xda, 0x80, 0x25, 0x6f, 0x74, 0x30, 0xa9, 0x63, 0x76, 0xad, 0xa1, 0x2f, 0xef, 0x8d, 0xe3, 0xc5,
	0xb1, 0xa2, 0xe6, 0x54, 0xac, 0xa1, 0x9f, 0xfb, 0x23, 0x06, 0x8b, 0x63, 0x64, 0x99, 0x39, 0x3d,
	0x6a, 0xa3, 0x2e, 0xfc, 0x97, 0x39, 0x7d, 0xea, 0x10, 0xb3, 0x4b, 0xdc, 0x3e, 0x1b, 0x0e, 0x88,
	0xc3, 0xcd, 0x31, 0x50, 0x32, 0xa5, 0xb7, 0xfe, 0xaf, 0xbf, 0xb6, 0x86, 0xfa, 0x98, 0x10, 0xaf,
	0x06, 0x44, 0x95, 0x31, 0xcf, 0xa9, 0x97, 0x3d, 0x58, 0x63, 0xbd, 0xde, 0xeb, 0xaf, 0x89, 0xbe,
	0xc3, 0x35, 0xd9, 0x90, 0xe9, 0xbc, 0x7b, 0x5a, 0x80, 0x88, 0xd3, 0x75, 0x19, 0x9d, 0x62, 0x8f,
	0xbd, 0x03, 0xfb, 0xd2, 0x08, 0x7f, 0x4a, 0x5a, 0x87, 0xc5, 0x01, 0xeb, 0x92, 0xfe, 0x04, 0xe3,
	0xdc, 0x3b, 0x30, 0x2e, 0x48, 0xf0, 0x29, 0x9d, 0x05, 0x2b, 0x0e, 0xe3, 0xb4, 0x47, 0x3b, 0x96,
	0x2c, 0x5a, 0x87, 0x39, 0xdc, 0x63, 0xfd, 0x0c, 0xac, 0x2b, 0xf9, 0x85, 0x2d, 0xfd, 0x0d, 0x9c,
	0x8d, 0x09, 0x58, 0x39, 0x40, 0xe1, 0x65, 0xe7, 0xac, 0x30, 0x77, 0x1f, 0x16, 0x9b, 0x41, 0x93,
	0xb6, 0x87, 0x2e, 0x91, 0x9d, 0xb9, 0x06, 0x40, 0x7d, 0xb3, 0xc3, 0x3c, 0x62, 0x0e, 0xfa, 0xb2,
	0xac, 0x49, 0x9c, 0xa4, 0x7e, 0x99, 0x79, 0xa4, 0xde, 0x47, 0x79, 0x50, 0xa9, 0x6f, 0x86, 0xef,
	0x88, 0x1e, 0x11, 0xd3, 0xa2, 0xb2, 0x26, 0x49, 0xbc, 0x40, 0xfd, 0xdd, 0xb1, 0xb8, 0x48, 0x73,
	0xdf, 0xc5, 0x21, 0x1d, 0x72, 0xb7, 0x5c, 0xd2, 0x41, 0xb7, 0x61, 0x39, 0x7c, 0x0f, 0x66, 0x97,
	0xf8, 0x1d, 0x8f, 0xba, 0xe3, 0xbe, 0x49, 0x95, 0x16, 0x5f, 0x9d, 0x44, 0xd3, 0x13, 0x62, 0x8c,
	0x42, 0xdb, 0xca, 0xa9, 0x0c, 0x6d, 0x43, 0x5c, 0x76, 0xf7, 0x0c, 0x4d, 0x30, 0x7e, 0x68, 0x38,
	0x80, 0x20, 0x0d, 0xe6, 0x38, 0x25, 0x9e, 0xac, 0x70, 0xbc, 0x04, 0x4f, 0x4f, 0xa2, 0x09, 0x50,
	0x36, 0x91, 0x72, 0x03, 0x4b, 0x39, 0x5a, 0x85, 0xa4, 0x4d, 0x45, 0x2b, 0xb8, 0x4c, 0xd6, 0x2c,
	0x85, 0xe7, 0x6d, 0xca, 0x31, 0x71, 0x99, 0x50, 0x79, 0x8c, 0x71, 0xb3, 0x4b, 0xbd, 0x4c, 0x3c,
	0x50, 0x89, 0x73, 0x85, 0x7a, 0xe8, 0x16, 0x2c, 0xf7, 0x89, 0x6d, 0x75, 0x86, 0xa6, 0xbc, 0x57,
	0x54, 0xa8, 0x47, 0xed, 0xcc, 0x8a, 0x8c, 0x29, 0x2d, 0x5e, 0xf3, 0xe3, 0x84, 0xf2, 0xf2, 0x24,
	0xaa, 0xe0, 0xa5, 0xc0, 0xae, 0x28, 0xcc, 0xc2, 0x07, 0xb5, 0x03, 0x89, 0x0e, 0x1b, 0x0c, 0x28,
	0xcf, 0xcc, 0xcb, 0x78, 0xae, 0xbe, 0x21, 0x9e, 0xb2, 0x34, 0x14, 0x01, 0x05, 0x43, 0xe2, 0x71,
	0x42, 0xc1, 0x21, 0x1a, 0x31, 0x50, 0xfd, 0x43, 0xd7, 0x65, 0x1e, 0x17, 0xe3, 0xa4, 0x4f, 0x9d,
	0x03, 0x3f, 0x93, 0x5c, 0x8f, 0xe5, 0xd3, 0x5b, 0xb7, 0xde, 0xc0, 0x38, 0x51, 0x1a, 0xbd, 0x35,
	0x86, 0xef, 0x09, 0x74, 0xd5, 0xe1, 0xde, 0xf0, 0xf4, 0x9e, 0x45, 0x7f, 0x5a, 0x8d, 0xbe, 0x04,
	0xf5, 0x74, 0x92, 0x84, 0x21, 0xa7, 0x64, 0x08, 0x1b, 0xb3, 0xf4, 0x79, 0x10, 0xfe, 0x04, 0xbf,
	0x37, 0xad, 0xc9, 0x96, 0x60, 0xe5, 0x3c, 0x8f, 0x90, 0x0a, 0xb1, 0x03, 0x32, 0x0c, 0x3a, 0x06,
	0x8b, 0x4f, 0xb4, 0x02, 0xf1, 0x23, 0xab, 0x7f, 0x48, 0x64, 0x47, 0xa4, 0x70, 0x70, 0xd8, 0x8e,
	0xde, 0x54, 0xb6, 0x17, 0x1f, 0x95, 0x94, 0x1f, 0x4b, 0x29, 0x3e, 0x74, 0x89, 0x49, 0x9d, 0x1e,
	0xcb, 0xfd, 0xa9, 0xc0, 0xc5, 0x51, 0xcc, 0xdc, 0xe2, 0x87, 0x3e, 0xfa, 0x04, 0xe2, 0x3e, 0xb7,
	0x38, 0x91, 0x84, 0x0b, 0x5b, 0xd7, 0x66, 0x48, 0x96, 0x30, 0xc7, 0x01, 0x4a, 0xc0, 0xdd, 0x7d,
	0xcb, 0x0f, 0xee, 0x9e, 0x09, 0xde, 0x14, 0xe6, 0x38, 0x40, 0xa1, 0x2b, 0x70, 0x91, 0x78, 0x1e,
	0xf3, 0xcc, 0x01, 0xf1, 0x7d, 0xcb, 0x26, 0xb2, 0x33, 0x53, 0xf8, 0x82, 0x14, 0xd6, 0x03, 0x19,
	0xaa, 0x80, 0xda, 0xb7, 0x7c, 0x6e, 0x1e, 0xba, 0x5d, 0x8b, 0x13, 0x53, 0x2c, 0xbd, 0x70, 0xa2,
	0x64, 0xf5, 0x60, 0x23, 0xea, 0xa3, 0x8d, 0xa8, 0xb7, 0x47, 0x1b, 0x11, 0x2f, 0x08, 0xcc, 0x5d,
	0x09, 0x11, 0xc2, 0xdc, 0xcf, 0x51, 0x98, 0x0f, 0x5d, 0x40, 0x9f, 0x41, 0x90, 0x13, 0xb1, 0x11,
	0xc3, 0x99, 0xad, 0xeb, 0xc1, 0xee, 0xd4, 0x27, 0x77, 0xa7, 0xee, 0x1e, 0xd8, 0x42, 0xe0, 0xeb,
	0xc2, 0x52, 0x3f, 0xda, 0xd4, 0xc5, 0x80, 0xa8, 0x13, 0x6e, 0xe1, 0x24, 0x0f, 0xbf, 0xd0, 0x1e,
	0x24, 0x85, 0xb6, 0x6b, 0x71, 0x2b, 0x7c, 0x93, 0xd7, 0x67, 0xe3, 0x32, 0x1e, 0x08, 0x67, 0x02,
	0xb6, 0x11, 0x03, 0xda, 0x86, 0x39, 0xdf, 0x25, 0x9d, 0x70, 0x08, 0xbf, 0x37, 0x5b, 0xef, 0x62,
	0x89, 0x41, 0xb7, 0x21, 0xe1, 0xcb, 0xaa, 0x86, 0xe9, 0xc9, 0xcf, 0x56, 0xcc, 0x43, 0x1f, 0x87,
	0xb8, 0xed, 0xec, 0x37, 0xa5, 0xd8, 0x4f, 0x09, 0xe5, 0xdb, 0xd2, 0x12, 0xa4, 0x04, 0xa5, 0x2e,
	0xc7, 0x82, 0x1c, 0x0e, 0xb9, 0xdf, 0x95, 0xf1, 0x28, 0xdb, 0xa3, 0xfe, 0x3f, 0x9c, 0xc4, 0x3b,
	0x67, 0x92, 0x38, 0x23, 0x97, 0x70, 0xe5, 0x6f, 0x29, 0xbc, 0x09, 0x71, 0xca, 0xc9, 0x20, 0xf8,
	0x19, 0x48, 0x6f, 0xe5, 0xde, 0x9e, 0x05, 0x1c, 0x00, 0xb6, 0x63, 0xaf, 0x8a, 0x91, 0x8d, 0x5f,
	0x14, 0x58, 0x3e, 0x67, 0x75, 0xa0, 0x75, 0x58, 0x6b, 0x18, 0xed, 0xda, 0x4e, 0xad, 0x5c, 0x6c,
	0xd7, 0x8c, 0x86, 0x59, 0x36, 0x1a, 0x6d, 0x6c, 0xec, 0x99, 0xb5, 0xc6, 0xbd, 0xe2, 0x5e, 0xad,
	0xa2, 0x46, 0xd0, 0x0d, 0xb8, 0x7e, 0xae, 0x45, 0x13, 0x1b, 0x77, 0xaa, 0xe5, 0xb6, 0x69, 0x7c,
	0xde, 0xa8, 0x62, 0xb3, 0xd8, 0xa8, 0x98, 0x77, 0x5b, 0x55, 0x6c, 0xb6, 0xab, 0xc5, 0xba, 0xaa,
	0xa0, 0x0f, 0xe0, 0xda, 0x0c, 0x28, 0xa3, 0xb1, 0x77, 0x5f, 0x8d, 0xa2, 0xf7, 0xe1, 0xea, 0xb9,
	0xc6, 0x53, 0x42, 0x63, 0x67, 0x47, 0x8d, 0x6d, 0x7c, 0xaf, 0xc0, 0x85, 0xc9, 0x27, 0x8b, 0x56,
	0xe1, 0x5f, 0x23, 0xce, 0x56, 0xbb, 0xd8, 0xae, 0x4e, 0x78, 0xae, 0x41, 0x76, 0x5a, 0xd5, 0xc4,
	0xc6, 0xbd, 0x5a, 0xab, 0x66, 0x34, 0x6a, 0x8d, 0x5d, 0x55, 0x41, 0x57, 0xe0, 0xd2, 0x6b, 0xf4,
	0x66, 0xb3, 0xda, 0xa8, 0x08, 0xa3, 0x28, 0xfa, 0x0f, 0x2c, 0x4f, 0x1b, 0xe1, 0x6a, 0xb1, 0x72,
	0x5f, 0x8d, 0x9d, 0x55, 0x54, 0x31, 0x36, 0xb0, 0x3a, 0xb7, 0xf1, 0xc3, 0xa9, 0x8b, 0x72, 0x2c,
	0x4c, 0xba, 0xd8, 0xfc, 0xb4, 0xd8, 0x9a, 0x74, 0xf1, 0x7f, 0xb0, 0x3a, 0xad, 0xaa, 0x54, 0xef,
	0x55, 0xf7, 0x8c, 0x66, 0xbd, 0xda, 0x68, 0xab, 0xca, 0x59, 0x64, 0xab, 0x5d, 0xdc, 0x0d, 0xfc,
	0x5a, 0x83, 0xcc, 0xb4, 0xaa, 0x89, 0x8d, 0xca, 0xdd, 0xb2, 0x48, 0x95, 0x1a, 0x9b, 0x0c, 0x7d,
	0xc4, 0x5b, 0x36, 0xea, 0xf5, 0x5a, 0x4b, 0x44, 0xa7, 0xce, 0x95, 0xb6, 0x9f, 0x3c, 0xd7, 0x22,
	0xcf, 0x9e, 0x6b, 0x91, 0x97, 0xcf, 0x35, 0xe5, 0xeb, 0x63, 0x4d, 0xf9, 0xf5, 0x58, 0x53, 0x9e,
	0x1c, 0x6b, 0xca, 0x6f, 0xc7, 0x9a, 0x72, 0x72, 0xac, 0x45, 0x5e, 0x1e, 0x6b, 0xca, 0xa3, 0x17,
	0x5a, 0xe4, 0xc9, 0x0b, 0x2d, 0xf2, 0xec, 0x85, 0x16, 0xf9, 0x22, 0x39, 0x6a, 0xaf, 0x07, 0x09,
	0x39, 0x97, 0x3e, 0xfa, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x5e, 0xc8, 0x0a, 0xbf, 0x02, 0x0c, 0x00,
	0x00,
}

func (x NotificationControl) String() string {
	s, ok := NotificationControl_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x ProjectState) String() string {
	s, ok := ProjectState_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x ProjectPhase) String() string {
	s, ok := ProjectPhase_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *OwnerInfo) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&v2alpha1.OwnerInfo{")
	s = append(s, "OwningTeam: "+fmt.Sprintf("%#v", this.OwningTeam)+",\n")
	s = append(s, "Owners: "+fmt.Sprintf("%#v", this.Owners)+",\n")
	s = append(s, "OwnerGroups: "+fmt.Sprintf("%#v", this.OwnerGroups)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Retention) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&v2alpha1.Retention{")
	s = append(s, "RetentionInDays: "+fmt.Sprintf("%#v", this.RetentionInDays)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *RetentionConfig) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 9)
	s = append(s, "&v2alpha1.RetentionConfig{")
	if this.OnlineDeploymentRetention != nil {
		s = append(s, "OnlineDeploymentRetention: "+fmt.Sprintf("%#v", this.OnlineDeploymentRetention)+",\n")
	}
	if this.OfflineDeploymentRetention != nil {
		s = append(s, "OfflineDeploymentRetention: "+fmt.Sprintf("%#v", this.OfflineDeploymentRetention)+",\n")
	}
	if this.EndpointRetention != nil {
		s = append(s, "EndpointRetention: "+fmt.Sprintf("%#v", this.EndpointRetention)+",\n")
	}
	if this.ModelRetention != nil {
		s = append(s, "ModelRetention: "+fmt.Sprintf("%#v", this.ModelRetention)+",\n")
	}
	s = append(s, "NotificationControl: "+fmt.Sprintf("%#v", this.NotificationControl)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ProjectTypeInfo) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&v2alpha1.ProjectTypeInfo{")
	s = append(s, "IsCoreMl: "+fmt.Sprintf("%#v", this.IsCoreMl)+",\n")
	s = append(s, "IsGenerativeAi: "+fmt.Sprintf("%#v", this.IsGenerativeAi)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ProjectSpec) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 13)
	s = append(s, "&v2alpha1.ProjectSpec{")
	s = append(s, "ProjectDescription: "+fmt.Sprintf("%#v", this.ProjectDescription)+",\n")
	if this.Owner != nil {
		s = append(s, "Owner: "+fmt.Sprintf("%#v", this.Owner)+",\n")
	}
	s = append(s, "Tier: "+fmt.Sprintf("%#v", this.Tier)+",\n")
	s = append(s, "GitRepo: "+fmt.Sprintf("%#v", this.GitRepo)+",\n")
	s = append(s, "RootDir: "+fmt.Sprintf("%#v", this.RootDir)+",\n")
	s = append(s, "LegacyAlphaConfig: "+fmt.Sprintf("%#v", this.LegacyAlphaConfig)+",\n")
	if this.Commit != nil {
		s = append(s, "Commit: "+fmt.Sprintf("%#v", this.Commit)+",\n")
	}
	keysForSupportingLinks := make([]string, 0, len(this.SupportingLinks))
	for k, _ := range this.SupportingLinks {
		keysForSupportingLinks = append(keysForSupportingLinks, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForSupportingLinks)
	mapStringForSupportingLinks := "map[string]string{"
	for _, k := range keysForSupportingLinks {
		mapStringForSupportingLinks += fmt.Sprintf("%#v: %#v,", k, this.SupportingLinks[k])
	}
	mapStringForSupportingLinks += "}"
	if this.SupportingLinks != nil {
		s = append(s, "SupportingLinks: "+mapStringForSupportingLinks+",\n")
	}
	if this.RetentionConfig != nil {
		s = append(s, "RetentionConfig: "+fmt.Sprintf("%#v", this.RetentionConfig)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ProjectStatus) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&v2alpha1.ProjectStatus{")
	s = append(s, "State: "+fmt.Sprintf("%#v", this.State)+",\n")
	s = append(s, "Phase: "+fmt.Sprintf("%#v", this.Phase)+",\n")
	s = append(s, "ErrorMessage: "+fmt.Sprintf("%#v", this.ErrorMessage)+",\n")
	if this.LastUpdateTime != nil {
		s = append(s, "LastUpdateTime: "+fmt.Sprintf("%#v", this.LastUpdateTime)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringProject(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *OwnerInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OwnerInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OwnerInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OwnerGroups) > 0 {
		for iNdEx := len(m.OwnerGroups) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.OwnerGroups[iNdEx])
			copy(dAtA[i:], m.OwnerGroups[iNdEx])
			i = encodeVarintProject(dAtA, i, uint64(len(m.OwnerGroups[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Owners) > 0 {
		for iNdEx := len(m.Owners) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Owners[iNdEx])
			copy(dAtA[i:], m.Owners[iNdEx])
			i = encodeVarintProject(dAtA, i, uint64(len(m.Owners[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.OwningTeam) > 0 {
		i -= len(m.OwningTeam)
		copy(dAtA[i:], m.OwningTeam)
		i = encodeVarintProject(dAtA, i, uint64(len(m.OwningTeam)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Retention) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Retention) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Retention) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RetentionInDays != 0 {
		i = encodeVarintProject(dAtA, i, uint64(m.RetentionInDays))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *RetentionConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RetentionConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RetentionConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NotificationControl != 0 {
		i = encodeVarintProject(dAtA, i, uint64(m.NotificationControl))
		i--
		dAtA[i] = 0x50
	}
	if m.ModelRetention != nil {
		{
			size, err := m.ModelRetention.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintProject(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.EndpointRetention != nil {
		{
			size, err := m.EndpointRetention.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintProject(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.OfflineDeploymentRetention != nil {
		{
			size, err := m.OfflineDeploymentRetention.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintProject(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.OnlineDeploymentRetention != nil {
		{
			size, err := m.OnlineDeploymentRetention.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintProject(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ProjectTypeInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProjectTypeInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProjectTypeInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IsGenerativeAi {
		i--
		if m.IsGenerativeAi {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.IsCoreMl {
		i--
		if m.IsCoreMl {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ProjectSpec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProjectSpec) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProjectSpec) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.LegacyAlphaConfig) > 0 {
		i -= len(m.LegacyAlphaConfig)
		copy(dAtA[i:], m.LegacyAlphaConfig)
		i = encodeVarintProject(dAtA, i, uint64(len(m.LegacyAlphaConfig)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa2
	}
	if m.RetentionConfig != nil {
		{
			size, err := m.RetentionConfig.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintProject(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x4a
	}
	if len(m.SupportingLinks) > 0 {
		for k := range m.SupportingLinks {
			v := m.SupportingLinks[k]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintProject(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintProject(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintProject(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x42
		}
	}
	if m.Commit != nil {
		{
			size, err := m.Commit.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintProject(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	if len(m.RootDir) > 0 {
		i -= len(m.RootDir)
		copy(dAtA[i:], m.RootDir)
		i = encodeVarintProject(dAtA, i, uint64(len(m.RootDir)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.GitRepo) > 0 {
		i -= len(m.GitRepo)
		copy(dAtA[i:], m.GitRepo)
		i = encodeVarintProject(dAtA, i, uint64(len(m.GitRepo)))
		i--
		dAtA[i] = 0x22
	}
	if m.Tier != 0 {
		i = encodeVarintProject(dAtA, i, uint64(m.Tier))
		i--
		dAtA[i] = 0x18
	}
	if m.Owner != nil {
		{
			size, err := m.Owner.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintProject(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ProjectDescription) > 0 {
		i -= len(m.ProjectDescription)
		copy(dAtA[i:], m.ProjectDescription)
		i = encodeVarintProject(dAtA, i, uint64(len(m.ProjectDescription)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ProjectStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProjectStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProjectStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastUpdateTime != nil {
		{
			size, err := m.LastUpdateTime.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintProject(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.ErrorMessage) > 0 {
		i -= len(m.ErrorMessage)
		copy(dAtA[i:], m.ErrorMessage)
		i = encodeVarintProject(dAtA, i, uint64(len(m.ErrorMessage)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Phase != 0 {
		i = encodeVarintProject(dAtA, i, uint64(m.Phase))
		i--
		dAtA[i] = 0x10
	}
	if m.State != 0 {
		i = encodeVarintProject(dAtA, i, uint64(m.State))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Project) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Project) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProjectList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProjectList) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func encodeVarintProject(dAtA []byte, offset int, v uint64) int {
	offset -= sovProject(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *OwnerInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OwningTeam)
	if l > 0 {
		n += 1 + l + sovProject(uint64(l))
	}
	if len(m.Owners) > 0 {
		for _, s := range m.Owners {
			l = len(s)
			n += 1 + l + sovProject(uint64(l))
		}
	}
	if len(m.OwnerGroups) > 0 {
		for _, s := range m.OwnerGroups {
			l = len(s)
			n += 1 + l + sovProject(uint64(l))
		}
	}
	return n
}

func (m *Retention) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RetentionInDays != 0 {
		n += 1 + sovProject(uint64(m.RetentionInDays))
	}
	return n
}

func (m *RetentionConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.OnlineDeploymentRetention != nil {
		l = m.OnlineDeploymentRetention.Size()
		n += 1 + l + sovProject(uint64(l))
	}
	if m.OfflineDeploymentRetention != nil {
		l = m.OfflineDeploymentRetention.Size()
		n += 1 + l + sovProject(uint64(l))
	}
	if m.EndpointRetention != nil {
		l = m.EndpointRetention.Size()
		n += 1 + l + sovProject(uint64(l))
	}
	if m.ModelRetention != nil {
		l = m.ModelRetention.Size()
		n += 1 + l + sovProject(uint64(l))
	}
	if m.NotificationControl != 0 {
		n += 1 + sovProject(uint64(m.NotificationControl))
	}
	return n
}

func (m *ProjectTypeInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IsCoreMl {
		n += 2
	}
	if m.IsGenerativeAi {
		n += 2
	}
	return n
}

func (m *ProjectSpec) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ProjectDescription)
	if l > 0 {
		n += 1 + l + sovProject(uint64(l))
	}
	if m.Owner != nil {
		l = m.Owner.Size()
		n += 1 + l + sovProject(uint64(l))
	}
	if m.Tier != 0 {
		n += 1 + sovProject(uint64(m.Tier))
	}
	l = len(m.GitRepo)
	if l > 0 {
		n += 1 + l + sovProject(uint64(l))
	}
	l = len(m.RootDir)
	if l > 0 {
		n += 1 + l + sovProject(uint64(l))
	}
	if m.Commit != nil {
		l = m.Commit.Size()
		n += 1 + l + sovProject(uint64(l))
	}
	if len(m.SupportingLinks) > 0 {
		for k, v := range m.SupportingLinks {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovProject(uint64(len(k))) + 1 + len(v) + sovProject(uint64(len(v)))
			n += mapEntrySize + 1 + sovProject(uint64(mapEntrySize))
		}
	}
	if m.RetentionConfig != nil {
		l = m.RetentionConfig.Size()
		n += 1 + l + sovProject(uint64(l))
	}
	l = len(m.LegacyAlphaConfig)
	if l > 0 {
		n += 2 + l + sovProject(uint64(l))
	}
	return n
}

func (m *ProjectStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.State != 0 {
		n += 1 + sovProject(uint64(m.State))
	}
	if m.Phase != 0 {
		n += 1 + sovProject(uint64(m.Phase))
	}
	l = len(m.ErrorMessage)
	if l > 0 {
		n += 1 + l + sovProject(uint64(l))
	}
	if m.LastUpdateTime != nil {
		l = m.LastUpdateTime.Size()
		n += 1 + l + sovProject(uint64(l))
	}
	return n
}

func sovProject(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozProject(x uint64) (n int) {
	return sovProject(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *OwnerInfo) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&OwnerInfo{`,
		`OwningTeam:` + fmt.Sprintf("%v", this.OwningTeam) + `,`,
		`Owners:` + fmt.Sprintf("%v", this.Owners) + `,`,
		`OwnerGroups:` + fmt.Sprintf("%v", this.OwnerGroups) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Retention) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Retention{`,
		`RetentionInDays:` + fmt.Sprintf("%v", this.RetentionInDays) + `,`,
		`}`,
	}, "")
	return s
}
func (this *RetentionConfig) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&RetentionConfig{`,
		`OnlineDeploymentRetention:` + strings.Replace(this.OnlineDeploymentRetention.String(), "Retention", "Retention", 1) + `,`,
		`OfflineDeploymentRetention:` + strings.Replace(this.OfflineDeploymentRetention.String(), "Retention", "Retention", 1) + `,`,
		`EndpointRetention:` + strings.Replace(this.EndpointRetention.String(), "Retention", "Retention", 1) + `,`,
		`ModelRetention:` + strings.Replace(this.ModelRetention.String(), "Retention", "Retention", 1) + `,`,
		`NotificationControl:` + fmt.Sprintf("%v", this.NotificationControl) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ProjectTypeInfo) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ProjectTypeInfo{`,
		`IsCoreMl:` + fmt.Sprintf("%v", this.IsCoreMl) + `,`,
		`IsGenerativeAi:` + fmt.Sprintf("%v", this.IsGenerativeAi) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ProjectSpec) String() string {
	if this == nil {
		return "nil"
	}
	keysForSupportingLinks := make([]string, 0, len(this.SupportingLinks))
	for k, _ := range this.SupportingLinks {
		keysForSupportingLinks = append(keysForSupportingLinks, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForSupportingLinks)
	mapStringForSupportingLinks := "map[string]string{"
	for _, k := range keysForSupportingLinks {
		mapStringForSupportingLinks += fmt.Sprintf("%v: %v,", k, this.SupportingLinks[k])
	}
	mapStringForSupportingLinks += "}"
	s := strings.Join([]string{`&ProjectSpec{`,
		`ProjectDescription:` + fmt.Sprintf("%v", this.ProjectDescription) + `,`,
		`Owner:` + strings.Replace(this.Owner.String(), "OwnerInfo", "OwnerInfo", 1) + `,`,
		`Tier:` + fmt.Sprintf("%v", this.Tier) + `,`,
		`GitRepo:` + fmt.Sprintf("%v", this.GitRepo) + `,`,
		`RootDir:` + fmt.Sprintf("%v", this.RootDir) + `,`,
		`Commit:` + strings.Replace(fmt.Sprintf("%v", this.Commit), "CommitInfo", "CommitInfo", 1) + `,`,
		`SupportingLinks:` + mapStringForSupportingLinks + `,`,
		`RetentionConfig:` + strings.Replace(this.RetentionConfig.String(), "RetentionConfig", "RetentionConfig", 1) + `,`,
		`LegacyAlphaConfig:` + fmt.Sprintf("%v", this.LegacyAlphaConfig) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ProjectStatus) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ProjectStatus{`,
		`State:` + fmt.Sprintf("%v", this.State) + `,`,
		`Phase:` + fmt.Sprintf("%v", this.Phase) + `,`,
		`ErrorMessage:` + fmt.Sprintf("%v", this.ErrorMessage) + `,`,
		`LastUpdateTime:` + strings.Replace(fmt.Sprintf("%v", this.LastUpdateTime), "Timestamp", "types.Timestamp", 1) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringProject(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *OwnerInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProject
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OwnerInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OwnerInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwningTeam", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProject
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProject
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OwningTeam = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owners", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProject
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProject
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owners = append(m.Owners, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerGroups", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProject
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProject
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OwnerGroups = append(m.OwnerGroups, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProject(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProject
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Retention) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProject
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Retention: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Retention: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RetentionInDays", wireType)
			}
			m.RetentionInDays = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RetentionInDays |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipProject(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProject
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RetentionConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProject
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RetentionConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RetentionConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OnlineDeploymentRetention", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProject
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProject
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.OnlineDeploymentRetention == nil {
				m.OnlineDeploymentRetention = &Retention{}
			}
			if err := m.OnlineDeploymentRetention.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OfflineDeploymentRetention", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProject
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProject
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.OfflineDeploymentRetention == nil {
				m.OfflineDeploymentRetention = &Retention{}
			}
			if err := m.OfflineDeploymentRetention.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndpointRetention", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProject
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProject
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.EndpointRetention == nil {
				m.EndpointRetention = &Retention{}
			}
			if err := m.EndpointRetention.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModelRetention", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProject
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProject
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ModelRetention == nil {
				m.ModelRetention = &Retention{}
			}
			if err := m.ModelRetention.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NotificationControl", wireType)
			}
			m.NotificationControl = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NotificationControl |= NotificationControl(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipProject(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProject
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProjectTypeInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProject
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProjectTypeInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProjectTypeInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsCoreMl", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsCoreMl = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsGenerativeAi", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsGenerativeAi = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipProject(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProject
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProjectSpec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProject
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProjectSpec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProjectSpec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectDescription", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProject
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProject
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProjectDescription = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProject
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProject
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Owner == nil {
				m.Owner = &OwnerInfo{}
			}
			if err := m.Owner.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tier", wireType)
			}
			m.Tier = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Tier |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GitRepo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProject
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProject
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GitRepo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RootDir", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProject
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProject
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RootDir = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Commit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProject
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProject
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Commit == nil {
				m.Commit = &CommitInfo{}
			}
			if err := m.Commit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SupportingLinks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProject
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProject
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SupportingLinks == nil {
				m.SupportingLinks = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowProject
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowProject
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthProject
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthProject
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowProject
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthProject
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthProject
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipProject(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthProject
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.SupportingLinks[mapkey] = mapvalue
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RetentionConfig", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProject
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProject
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RetentionConfig == nil {
				m.RetentionConfig = &RetentionConfig{}
			}
			if err := m.RetentionConfig.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 20:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LegacyAlphaConfig", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProject
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProject
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LegacyAlphaConfig = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProject(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProject
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProjectStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProject
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProjectStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProjectStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			m.State = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.State |= ProjectState(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Phase", wireType)
			}
			m.Phase = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Phase |= ProjectPhase(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrorMessage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProject
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProject
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ErrorMessage = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastUpdateTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProject
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProject
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LastUpdateTime == nil {
				m.LastUpdateTime = &types.Timestamp{}
			}
			if err := m.LastUpdateTime.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProject(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProject
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipProject(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowProject
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProject
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProject
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthProject
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupProject
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthProject
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthProject        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowProject          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupProject = fmt.Errorf("proto: unexpected end of group")
)

type Project struct {
	metav1.TypeMeta   `protobuf:"bytes,1,opt,name=type_meta,json=typeMeta,proto3,embedded=type_meta" json:",inline"`
	metav1.ObjectMeta `protobuf:"bytes,2,opt,name=metadata,proto3,embedded=metadata" json:"metadata,omitempty"`
	// Spec of the desired behavior of the Project.
	Spec ProjectSpec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	// Most recently observed status of the Project.
	Status ProjectStatus `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
}

func (m *Project) GetTypeMeta() *metav1.TypeMeta {
	return &m.TypeMeta
}

func (m *Project) GetMetadata() *metav1.ObjectMeta {
	return &m.ObjectMeta
}

func (m *Project) GetSpec() ProjectSpec {
	if m != nil {
		return m.Spec
	}
	return ProjectSpec{}
}

func (m *Project) GetStatus() ProjectStatus {
	if m != nil {
		return m.Status
	}
	return ProjectStatus{}
}

func (m *Project) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Status.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintProject(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size, err := m.Spec.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintProject(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.ObjectMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintProject(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.TypeMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintProject(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Project) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TypeMeta.Size()
	n += 1 + l + sovProject(uint64(l))
	l = m.ObjectMeta.Size()
	n += 1 + l + sovProject(uint64(l))
	l = m.Spec.Size()
	n += 1 + l + sovProject(uint64(l))
	l = m.Status.Size()
	n += 1 + l + sovProject(uint64(l))
	return n
}

func (this *Project) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Project{`,
		`TypeMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.TypeMeta), "TypeMeta", "metav1.TypeMeta", 1), `&`, ``, 1) + `,`,
		`ObjectMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ObjectMeta), "ObjectMeta", "metav1.ObjectMeta", 1), `&`, ``, 1) + `,`,
		`Spec:` + strings.Replace(strings.Replace(this.Spec.String(), "ProjectSpec", "ProjectSpec", 1), `&`, ``, 1) + `,`,
		`Status:` + strings.Replace(strings.Replace(this.Status.String(), "ProjectStatus", "ProjectStatus", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}

func (m *Project) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProject
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Project: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Project: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TypeMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProject
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProject
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TypeMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProject
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProject
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObjectMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spec", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProject
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProject
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Spec.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProject
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProject
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProject(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthProject
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthProject
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

/* As gogo proto's jsonpb library does not support marshal and unmarshal for
   inline field (TypeMeta), we work around this by implementing the
   marshal and unmarshal functions for Spec and Status respectively. */
func (m *ProjectSpec) MarshalJSON() ([]byte,error) {
	var buf bytes.Buffer
	err := (&jsonpb.Marshaler{
	  EnumsAsInts: false,
	  EmitDefaults: false,
	  OrigName: false,
	  AnyResolver: &util.GenericResolver{},
	}).Marshal(&buf, m)
	return buf.Bytes(), err
}

func (m *ProjectSpec) UnmarshalJSON(b []byte) error {
	err := (&jsonpb.Unmarshaler{
	  AllowUnknownFields: getAllowUnknownFieldsEnvVar(),
	  AnyResolver: &util.GenericResolver{},
	}).Unmarshal(bytes.NewReader(b), m)
	if err == nil {
        return nil
	}

    if !(strings.Contains(err.Error(), "cannot unmarshal string into Go value of type map[string]json.RawMessage") ||
         strings.Contains(err.Error(), "cannot unmarshal number into Go value of type map[string]json.RawMessage")) {
        return err
    }

	visited := make(map[reflect.Type]bool)
    var paths []util.InlineFieldMapping
	util.RemoveInlineFields(reflect.TypeOf(m), "", visited, &paths)
	if len(paths) > 0 {
	    b, err = util.ApplyInlineFields(b, paths)
	}
    type Alias ProjectSpec
    aux := (*Alias)(m)

    return json.Unmarshal(b, aux)
}

func (m *ProjectStatus) MarshalJSON() ([]byte,error) {
	var buf bytes.Buffer
	err := (&jsonpb.Marshaler{
	  EnumsAsInts: false,
	  EmitDefaults: false,
	  OrigName: false,
	  AnyResolver: &util.GenericResolver{},
	}).Marshal(&buf, m)
	return buf.Bytes(), err
}

func (m *ProjectStatus) UnmarshalJSON(b []byte) error {
    err := (&jsonpb.Unmarshaler{
      AllowUnknownFields: getAllowUnknownFieldsEnvVar(),
      AnyResolver: &util.GenericResolver{},
    }).Unmarshal(bytes.NewReader(b), m)
    if err == nil {
        return nil
    }
    if !(strings.Contains(err.Error(), "cannot unmarshal string into Go value of type map[string]json.RawMessage") ||
         strings.Contains(err.Error(), "cannot unmarshal number into Go value of type map[string]json.RawMessage")) {
        return err
    }

    visited := make(map[reflect.Type]bool)
    var paths []util.InlineFieldMapping
    util.RemoveInlineFields(reflect.TypeOf(m), "", visited, &paths)
    if len(paths) > 0 {
        b, err = util.ApplyInlineFields(b, paths)
    }
    type Alias ProjectStatus
    aux := (*Alias)(m)

    return json.Unmarshal(b, aux)
}

func (in *Project) DeepCopy() *Project {
	if in == nil {
		return nil
	}
	out := new(Project)
	in.DeepCopyInto(out)
	return out
}

func (in *Project) DeepCopyObject() k8sruntime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *Project) DeepCopyInto(out *Project) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = *proto.Clone(&in.Spec).(*ProjectSpec)
	out.Status = *proto.Clone(&in.Status).(*ProjectStatus)
}

func init() {
	SchemeBuilder.Register(&Project{})
}

func (m *Project) GetIndexedKeyValuePairs() ([]storage.IndexedField){
	var indexedFields []storage.IndexedField
	var indexedField storage.IndexedField

	indexedField.Key = "tier"
	if m != nil {
		indexedField.Value = m.Spec.Tier
	} else {
		indexedField.Value = nil
	}
	indexedFields = append(indexedFields, indexedField)

	return indexedFields
}


func init() {
	gvk := schema.GroupVersionKind{
		Group: "michelangelo.api",
		Version: "v2alpha1",
		Kind: "Project",
	}
	IndexesPathToKeyMap[gvk] = make(map[string]string)

	// default index
	IndexesPathToKeyMap[gvk]["metadata.namespace"] = "namespace"
	IndexesPathToKeyMap[gvk]["metadata.name"] = "name"
	IndexesPathToKeyMap[gvk]["spec.tier"] = "tier"
}

func (m *Project) IsImmutableKind() bool {

	return false
}

func init() {
	CrdObjects["Project"] = &Project{
		TypeMeta: metav1.TypeMeta{
			APIVersion: "michelangelo.api/v2alpha1",
			Kind: "Project",
		},
	}
}

func (m *Project) HasBlobFields() bool {
	return false
}

func (m *Project) ClearBlobFields() {
}

func (m *Project) FillBlobFields(object k8sruntime.Object) {
	other := object.(*Project)
	m.Spec = other.Spec
	m.Status = other.Status
}

// UnmarshalJSON unmarshals a JSON value into a NotificationControl.
// Since NotificationControl is an integer in go, the standard JSON encoder marshals it as a number.
// But as a protobuf enum, it is marshaled as a string. In different situations, a NotificationControl value
// may be marshaled as either a number or a string. This function allows unmarshalling from both formats.
func (m *NotificationControl) UnmarshalJSON(b []byte) error {
	var num int32
	err := json.Unmarshal(b, &num)
	if err == nil {
		*m = NotificationControl(num)
		return nil
	}
	var s string
	err = json.Unmarshal(b, &s)
	if err != nil {
		return err
	}
	// Check if the string exists in the map
	val, exists := NotificationControl_value[s]
	if !exists {
		return fmt.Errorf("invalid DataType: %s", s)
	}

	*m = NotificationControl(val)
	return nil
}

// UnmarshalJSON unmarshals a JSON value into a ProjectState.
// Since ProjectState is an integer in go, the standard JSON encoder marshals it as a number.
// But as a protobuf enum, it is marshaled as a string. In different situations, a ProjectState value
// may be marshaled as either a number or a string. This function allows unmarshalling from both formats.
func (m *ProjectState) UnmarshalJSON(b []byte) error {
	var num int32
	err := json.Unmarshal(b, &num)
	if err == nil {
		*m = ProjectState(num)
		return nil
	}
	var s string
	err = json.Unmarshal(b, &s)
	if err != nil {
		return err
	}
	// Check if the string exists in the map
	val, exists := ProjectState_value[s]
	if !exists {
		return fmt.Errorf("invalid DataType: %s", s)
	}

	*m = ProjectState(val)
	return nil
}

// UnmarshalJSON unmarshals a JSON value into a ProjectPhase.
// Since ProjectPhase is an integer in go, the standard JSON encoder marshals it as a number.
// But as a protobuf enum, it is marshaled as a string. In different situations, a ProjectPhase value
// may be marshaled as either a number or a string. This function allows unmarshalling from both formats.
func (m *ProjectPhase) UnmarshalJSON(b []byte) error {
	var num int32
	err := json.Unmarshal(b, &num)
	if err == nil {
		*m = ProjectPhase(num)
		return nil
	}
	var s string
	err = json.Unmarshal(b, &s)
	if err != nil {
		return err
	}
	// Check if the string exists in the map
	val, exists := ProjectPhase_value[s]
	if !exists {
		return fmt.Errorf("invalid DataType: %s", s)
	}

	*m = ProjectPhase(val)
	return nil
}

func init() {
	YamlSchemas["Project"] = `apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: projects.michelangelo.api
spec:
  group: michelangelo.api
  names:
    kind: Project
    listKind: ProjectList
    plural: projects
    singular: project
  scope: Namespaced
  versions:
  - name: v2alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              commit:
                properties:
                  branch:
                    type: string
                  gitRef:
                    type: string
                type: object
              gitRepo:
                type: string
              legacyAlphaConfig:
                type: string
              owner:
                properties:
                  ownerGroups:
                    items:
                      type: string
                    type: array
                  owners:
                    items:
                      type: string
                    type: array
                  owningTeam:
                    type: string
                type: object
              projectDescription:
                type: string
              retentionConfig:
                properties:
                  endpointRetention:
                    properties:
                      retentionInDays:
                        format: int32
                        type: integer
                    type: object
                  modelRetention:
                    properties:
                      retentionInDays:
                        format: int32
                        type: integer
                    type: object
                  notificationControl:
                    enum:
                    - NOTIFICATION_CONTROL_INVALID
                    - NOTIFICATION_CONTROL_PROJECT_OWNER_AND_USER_TEAM
                    - NOTIFICATION_CONTROL_PROJECT_OWNER_ONLY
                    - NOTIFICATION_CONTROL_NOTIFICATION_OFF
                    type: string
                  offlineDeploymentRetention:
                    properties:
                      retentionInDays:
                        format: int32
                        type: integer
                    type: object
                  onlineDeploymentRetention:
                    properties:
                      retentionInDays:
                        format: int32
                        type: integer
                    type: object
                type: object
              rootDir:
                type: string
              supportingLinks:
                additionalProperties:
                  type: string
                type: object
              tier:
                format: int32
                type: integer
            type: object
          status:
            properties:
              errorMessage:
                type: string
              lastUpdateTime:
                format: date-time
                type: string
              phase:
                enum:
                - PROJECT_PHASE_INVALID
                - PROJECT_PHASE_DEVELOPMENT
                - PROJECT_PHASE_STAGING
                - PROJECT_PHASE_PRODUCTION
                - PROJECT_PHASE_DECOMMISSION
                type: string
              state:
                enum:
                - PROJECT_STATE_INVALID
                - PROJECT_STATE_PROVISIONING
                - PROJECT_STATE_PROVISION_PENDING
                - PROJECT_STATE_READY
                - PROJECT_STATE_ERROR
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
`
}

type ProjectList struct {
	metav1.TypeMeta `protobuf:"bytes,1,opt,name=type_meta,json=typeMeta,proto3,embedded=type_meta" json:",inline"`
	metav1.ListMeta `protobuf:"bytes,2,opt,name=metadata,proto3,embedded=metadata" json:"metadata,omitempty"`
	// A list of Project
	Items []Project `protobuf:"bytes,3,rep,name=items,proto3" json:"items"`
}

func (m *ProjectList) GetTypeMeta() *metav1.TypeMeta {
	return &m.TypeMeta
}

func (m *ProjectList) GetMetadata() *metav1.ListMeta {
	return &m.ListMeta
}

func (m *ProjectList) GetItems() []Project {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ProjectList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Items) > 0 {
		for iNdEx := len(m.Items) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Items[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintProject(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	{
		size, err := m.ListMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintProject(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.TypeMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintProject(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *ProjectList) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TypeMeta.Size()
	n += 1 + l + sovProject(uint64(l))
	l = m.ListMeta.Size()
	n += 1 + l + sovProject(uint64(l))
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovProject(uint64(l))
		}
	}
	return n
}

func (this *ProjectList) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForItems := "[]Project{"
	for _, f := range this.Items {
		repeatedStringForItems += strings.Replace(strings.Replace(f.String(), "Project", "Project", 1), `&`, ``, 1) + ","
	}
	repeatedStringForItems += "}"
	s := strings.Join([]string{`&ProjectList{`,
		`TypeMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.TypeMeta), "TypeMeta", "metav1.TypeMeta", 1), `&`, ``, 1) + `,`,
		`ListMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ListMeta), "ListMeta", "metav1.ListMeta", 1), `&`, ``, 1) + `,`,
		`Items:` + repeatedStringForItems + `,`,
		`}`,
	}, "")
	return s
}

func (m *ProjectList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProject
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProjectList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProjectList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TypeMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProject
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProject
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TypeMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProject
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProject
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ListMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProject
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProject
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProject
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, Project{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProject(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthProject
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthProject
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (in *ProjectList) DeepCopy() *ProjectList {
	if in == nil {
		return nil
	}
	out := new(ProjectList)
	in.DeepCopyInto(out)
	return out
}

func (in *ProjectList) DeepCopyObject() k8sruntime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ProjectList) DeepCopyInto(out *ProjectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Project, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func init() {
	SchemeBuilder.Register(&ProjectList{})
}
