apiserver:
  yarpc:
    host: "localhost"
    port: 14566
    transport: "http"
    httpPort: 14567
  crdSync:
    enableCRDUpdate: true
    enableIncompatibleUpdate: false

k8s:
  qps: 300
  burst: 600
metadataStorage:
  enableMetadataStorage: false
