apiserver:
  yarpc:
    host: "localhost"
    port: 15566
  crdSync:
    enableCRDUpdate: true
    enableCRDDeletion: true
    skipIncompatibleCheck: false
    crdVersions:
      project:
        versions: [v2]
        storageVersion: v2

k8s:
  qps: 300
  burst: 600
metadataStorage:
  enableMetadataStorage: false
