apiserver:
  yarpc:
    host: "localhost"
    port: 50051 # grpc port
  k8s:
    qps: 300
    burst: 600
  metadataStorage:
    enableMetadataStorage: false
  crdSync:
    enableCRDUpdate: true
    enableIncompatibleUpdate: false