worker:
  address: localhost:14566
  httpAddress: http://localhost:8080
  maApiServiceName: ma-apiserver
  transport: grpc  # Options: "grpc" or "http"
  rayHttp:
    baseUrl: https://compute.cauldron.myteksi.net  # Base URL for Ray HTTP API
    workspace: cauldron-test
    environment: dev

logging:
  level: info
  development: true
  encoding: console

workflow-engine:
  # for cadence
  host: 127.0.0.1:7833
  # for temporal
#  host: 127.0.0.1:7233
  transport: grpc
  # for cadence
  provider: cadence
    # for temporal
#  provider: temporal
  workers:
    - domain: default
      taskList: default
  client:
    domain: default

minio:
  awsRegion: us-east-1
  awsAccessKeyId: minioadmin
  awsSecretAccessKey: minioadmin
  awsEndpointUrl: localhost:9091
