worker:
  address: 127.0.0.1:14566
  maApiServiceName: ma-apiserver
  rayHttp:
    baseUrl: https://compute.cauldron.myteksi.net  # Base URL for Ray HTTP API
    workspace: cauldron-test
    environment: dev

logging:
  level: info
  development: true
  encoding: console

workflow-engine:
  # for cadence
#  host: 127.0.0.1:7833
  # for temporal
  host: temporal.stg-myteksi.com:7233
  transport: grpc
  # for cadence
#  provider: cadence
    # for temporal
  provider: temporal
  workers:
    - domain: default
      taskList: zhou-xian
  client:
    domain: uniflow

minio:
  awsRegion: ap-southeast-1
  awsEndpointUrl: s3.ap-southeast-1.amazonaws.com
  useEnvAws: true
