worker:
  address: localhost:14567
  maApiServiceName: ma-apiserver

logging:
  level: info
  development: true
  encoding: console

workflow-engine:
#  host: 127.0.0.1:7833
  host: 127.0.0.1:7233
  transport: grpc
  provider: temporal
  workers:
    - domain: default
      taskList: default
  client:
    domain: default

minio:
  awsRegion: us-east-1
  awsAccessKeyId: minioadmin
  awsSecretAccessKey: minioadmin
  awsEndpointUrl: localhost:9091
