package tools

// This file is to force "go mod tidy" to download Go modules that we need but are not imported
// in the Go code.
import (
	_ "github.com/golang/protobuf/ptypes/any"
	_ "github.com/google/uuid" // for go code generated by protoc-gen-validation
	_ "google.golang.org/genproto/protobuf/api"
	_ "k8s.io/api/core/v1"
)
