apiVersion: michelangelo.api/v2
kind: Pipeline
metadata:
  name: demo-pipeline
  namespace: default
  annotations:
    michelangelo/uniflow-image: docker.io/library/examples:latest
spec:
  type: "PIPELINE_TYPE_TRAIN"
  manifest:
    uniflowTar: s3://default/bert_local.tar
