load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "go_default_library",
    srcs = [
        "middleware.go",
        "runnertoken.go",
    ],
    importpath = "github.com/michelangelo-ai/michelangelo/go/worker/runnertoken",
    visibility = ["//visibility:public"],
    deps = [
        "@io_k8s_api//authentication/v1:go_default_library",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:go_default_library",
        "@io_k8s_client_go//kubernetes:go_default_library",
        "@org_uber_go_yarpc//api/middleware:go_default_library",
        "@org_uber_go_yarpc//api/transport:go_default_library",
        "@org_uber_go_yarpc//yarpcerrors:go_default_library",
    ],
)

go_test(
    name = "go_default_test",
    srcs = [
        "middleware_test.go",
        "runnertoken_test.go",
    ],
    embed = [":go_default_library"],
    deps = [
        "@com_github_stretchr_testify//assert:go_default_library",
        "@com_github_stretchr_testify//require:go_default_library",
        "@io_k8s_api//authentication/v1:go_default_library",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:go_default_library",
        "@io_k8s_apimachinery//pkg/runtime:go_default_library",
        "@io_k8s_client_go//kubernetes/fake:go_default_library",
        "@io_k8s_client_go//testing:go_default_library",
        "@org_uber_go_yarpc//api/transport:go_default_library",
        "@org_uber_go_yarpc//yarpcerrors:go_default_library",
    ],
)
