apiVersion: michelangelo.api/v2
kind: Project
metadata:
  name:  svc-aip-chimeratest
  namespace:  svc-aip-chimeratest
spec:
  description: My ML Project
  owner:
    owningTeam: "cauldron"
    owners:
      - eric.w
  tier: 4
  gitRepo: https://github.com/uber/michelangelo
  rootDir: python/michelangelo/cli/sandbox/crds
