apiVersion: michelangelo.api/v2
kind: Project
metadata:
  name: ma-dev-test
  namespace: ma-dev-test
  annotations:
    michelangelo/worker_queue: default
spec:
  description: My ML Project
  owner:
    owningTeam: "d4580776-3af1-4347-ac74-0a5936bed11c"
    owners:
      - craig.marker
  tier: 4
  gitRepo: https://github.com/uber/michelangelo
  rootDir: python/michelangelo/cli/sandbox/crds
