apiVersion: michelangelo.api/v2
kind: Project
metadata:
  name: ma-dev-test
  namespace: ma-dev-test
  annotations:
    michelangelo/worker_queue: default
spec:
  description: My ML Project
  owner:
    owningTeam: "60eb5b33-03a3-4bc8-a24e-7a4ae4d8513a"
    owners:
      - craig.marker
  tier: 4
  gitRepo: https://github.com/uber/michelangelo
  rootDir: python/michelangelo/cli/sandbox/crds
