apiVersion: michelangelo.api/v2
kind: TriggerRun
metadata:
  name: training-pipeline-cron-trigger-batch-policy-1
  namespace: ma-dev-test
  annotations:
    description: "Test training pipeline execution via cron trigger"
spec:
  pipeline:
    name: training-pipeline
    namespace: ma-dev-test
  trigger:
    cronSchedule:
      cron: "* * * * *"  # Run every minute for testing, every 10 minutes using */10 * * * *
    batchPolicy:
      batchSize: 1
      wait: "60s"
    #maxConcurrency: 1
