#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

BAZEL="${WORKSPACE_ROOT}/tools/bazel"
OUT_DIR="${WORKSPACE_ROOT}/proto-go"
IMPORT_PREFIX="github.com/michelangelo-ai/michelangelo/proto-go"

if [[ ! -x "${BAZEL}" ]]; then
  echo "ERROR: bazel wrapper not found at ${BAZEL}"
  exit 1
fi

echo "Building proto targets with generated Go sources..."
"${BAZEL}" build //proto/... --output_groups=go_generated_srcs

echo "Cleaning existing generated files under ${OUT_DIR}..."
mkdir -p "${OUT_DIR}"
find "${OUT_DIR}" -type f -name "*.go" -delete

echo "Copying generated files into ${OUT_DIR}..."
while IFS= read -r file; do
  rel_path="${file#*${IMPORT_PREFIX}/}"
  dest="${OUT_DIR}/${rel_path}"
  mkdir -p "$(dirname "${dest}")"
  cp "${file}" "${dest}"
done < <(find "${WORKSPACE_ROOT}/bazel-bin/proto" -type f -name "*.go" | grep "/${IMPORT_PREFIX}/")

echo "Generating alias BUILD.bazel files under ${OUT_DIR}..."
find "${OUT_DIR}" -name BUILD.bazel -delete
WORKSPACE_ROOT="${WORKSPACE_ROOT}" python3 - <<'PY'
import os
from pathlib import Path

root = Path(os.environ["WORKSPACE_ROOT"])
out_dir = root / "proto-go"

for dirpath, _, filenames in os.walk(out_dir):
    if not any(name.endswith(".go") for name in filenames):
        continue
    dir_path = Path(dirpath)
    rel = dir_path.relative_to(out_dir)
    actual = f"//proto/{rel.as_posix()}:go_default_library"
    build_path = dir_path / "BUILD.bazel"
    build_path.write_text(
        "# Generated by tools/gen-proto-go.sh. Do not edit.\n"
        "package(default_visibility = [\"//visibility:public\"])\n\n"
        "alias(\n"
        "    name = \"go_default_library\",\n"
        f"    actual = \"{actual}\",\n"
        ")\n"
    )
PY

echo "Syncing proto-go dependency versions with go/go.mod..."
WORKSPACE_ROOT="${WORKSPACE_ROOT}" python3 - <<'PY'
import os
import pathlib
import re
import sys

root = pathlib.Path(os.environ["WORKSPACE_ROOT"])
go_mod = root / "go" / "go.mod"
proto_mod = root / "proto-go" / "go.mod"

go_text = go_mod.read_text()
proto_text = proto_mod.read_text()

versions = {}
for line in go_text.splitlines():
    line = line.strip()
    if not line or line.startswith("//"):
        continue
    # TODO(#2066): this doubled-backslash pattern never matches. Because this
    # heredoc is single-quoted (<<'PY'), bash passes it through to Python
    # literally -- "\\w" here is a two-character escaped backslash followed
    # by "w", not a \w character class. As a result `versions` is always
    # empty and the per-dependency sync loop below (using this same dict)
    # never fires.
    m = re.match(r"^([\\w./-]+)\\s+(v\\S+)$", line)
    if m:
        versions[m.group(1)] = m.group(2)


def read_go_sdk_version(module_bazel: pathlib.Path) -> str:
    """Extract the pinned Go SDK version from MODULE.bazel's go_sdk.download()
    call. Raises SystemExit(1) with a clear message if the block or version
    argument cannot be found -- never falls back to a stale/guessed default.
    """
    try:
        text = module_bazel.read_text()
    except FileNotFoundError:
        sys.exit(
            f"ERROR: {module_bazel} does not exist -- cannot determine the "
            "Go SDK version for proto-go/go.mod."
        )
    # Matches:
    #   go_sdk.download(
    #       version = "1.26.5",
    #   )
    # Anchored on the `go_sdk.download(` call specifically (not `go_sdk.nogo(`
    # or any other go_sdk.* call sharing the extension), tolerant of arg order
    # and additional kwargs (e.g. a future `strip_prefix` or `patches` arg)
    # since it only greps for `version = "..."` within that call's parens.
    m = re.search(
        r"go_sdk\.download\s*\((?P<args>[^)]*)\)",
        text,
        flags=re.S,
    )
    if not m:
        sys.exit(
            "ERROR: could not find a go_sdk.download(...) call in "
            f"{module_bazel} -- refusing to guess a Go version for proto-go/go.mod."
        )
    version_match = re.search(r'version\s*=\s*"([^"]+)"', m.group("args"))
    if not version_match:
        sys.exit(
            "ERROR: found go_sdk.download(...) in "
            f"{module_bazel} but no version = \"...\" argument inside it."
        )
    return version_match.group(1)


# MODULE.bazel's go_sdk.download(version=...) pin is the authoritative,
# explicitly-auditable Go toolchain version: it's the one place a security
# response to a Go SDK CVE bumps the version, and that bump should propagate
# here automatically -- do not reintroduce a hardcoded literal.
module_bazel = root / "MODULE.bazel"
go_sdk_version = read_go_sdk_version(module_bazel)
proto_text = re.sub(r"^go\s+\S+", f"go {go_sdk_version}", proto_text, flags=re.M)

out_lines = []
for line in proto_text.splitlines():
    # TODO(#2066): same doubled-backslash issue as above -- this never matches
    # inside this quoted heredoc, so `m` is always None and this branch never
    # fires.
    m = re.match(r"^(\\s*)([\\w./-]+)\\s+(v\\S+)(\\s*//.*)?$", line)
    if m and m.group(2) in versions:
        indent, mod, _ver, trailing = m.group(1), m.group(2), m.group(3), m.group(4) or ""
        line = f"{indent}{mod} {versions[mod]}{trailing}"
    out_lines.append(line)

proto_mod.write_text("\n".join(out_lines) + "\n")
PY

echo "Running go mod tidy in ${OUT_DIR}..."
echo "proto-go go.mod first line: $(head -n 1 "${OUT_DIR}/go.mod")"
GO_BIN="$(command -v go || true)"
if [[ -z "${GO_BIN}" ]]; then
  echo "WARN: system go not found; falling back to tools/go"
  GO_BIN="${WORKSPACE_ROOT}/tools/go"
fi
(cd "${OUT_DIR}" && PATH="${WORKSPACE_ROOT}/tools:${PATH}" GOWORK=off "${GO_BIN}" mod tidy)

echo "Generated Go protobuf files are available under ${OUT_DIR}."
