#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

BAZEL="${WORKSPACE_ROOT}/tools/bazel"
OUT_DIR="${WORKSPACE_ROOT}/proto-go"
IMPORT_PREFIX="github.com/michelangelo-ai/michelangelo/proto-go"

if [[ ! -x "${BAZEL}" ]]; then
  echo "ERROR: bazel wrapper not found at ${BAZEL}"
  exit 1
fi

echo "Building proto targets with generated Go sources..."
"${BAZEL}" build //proto/... --output_groups=go_generated_srcs

echo "Cleaning existing generated files under ${OUT_DIR}..."
mkdir -p "${OUT_DIR}"
find "${OUT_DIR}" -type f -name "*.go" -delete

echo "Copying generated files into ${OUT_DIR}..."
while IFS= read -r file; do
  rel_path="${file#*${IMPORT_PREFIX}/}"
  dest="${OUT_DIR}/${rel_path}"
  mkdir -p "$(dirname "${dest}")"
  cp "${file}" "${dest}"
done < <(find "${WORKSPACE_ROOT}/bazel-bin/proto" -type f -name "*.go" | grep "/${IMPORT_PREFIX}/")

echo "Generating alias BUILD.bazel files under ${OUT_DIR}..."
find "${OUT_DIR}" -name BUILD.bazel -delete
WORKSPACE_ROOT="${WORKSPACE_ROOT}" python3 - <<'PY'
import os
from pathlib import Path

root = Path(os.environ["WORKSPACE_ROOT"])
out_dir = root / "proto-go"

for dirpath, _, filenames in os.walk(out_dir):
    if not any(name.endswith(".go") for name in filenames):
        continue
    dir_path = Path(dirpath)
    rel = dir_path.relative_to(out_dir)
    actual = f"//proto/{rel.as_posix()}:go_default_library"
    build_path = dir_path / "BUILD.bazel"
    build_path.write_text(
        "# Generated by tools/gen-proto-go.sh. Do not edit.\n"
        "package(default_visibility = [\"//visibility:public\"])\n\n"
        "alias(\n"
        "    name = \"go_default_library\",\n"
        f"    actual = \"{actual}\",\n"
        ")\n"
    )
PY

echo "Syncing proto-go dependency versions with go/go.mod..."
WORKSPACE_ROOT="${WORKSPACE_ROOT}" python3 - <<'PY'
import os
import pathlib
import re

root = pathlib.Path(os.environ["WORKSPACE_ROOT"])
go_mod = root / "go" / "go.mod"
proto_mod = root / "proto-go" / "go.mod"

go_text = go_mod.read_text()
proto_text = proto_mod.read_text()

versions = {}
for line in go_text.splitlines():
    line = line.strip()
    if not line or line.startswith("//"):
        continue
    m = re.match(r"^([\\w./-]+)\\s+(v\\S+)$", line)
    if m:
        versions[m.group(1)] = m.group(2)

# Align Go version too.
proto_text = re.sub(r"^go\\s+\\S+", "go 1.23.2", proto_text, flags=re.M)

out_lines = []
for line in proto_text.splitlines():
    m = re.match(r"^(\\s*)([\\w./-]+)\\s+(v\\S+)(\\s*//.*)?$", line)
    if m and m.group(2) in versions:
        indent, mod, _ver, trailing = m.group(1), m.group(2), m.group(3), m.group(4) or ""
        line = f"{indent}{mod} {versions[mod]}{trailing}"
    out_lines.append(line)

proto_mod.write_text("\n".join(out_lines) + "\n")
PY

echo "Running go mod tidy in ${OUT_DIR}..."
echo "proto-go go.mod first line: $(head -n 1 "${OUT_DIR}/go.mod")"
GO_BIN="$(command -v go || true)"
if [[ -z "${GO_BIN}" ]]; then
  echo "WARN: system go not found; falling back to tools/go"
  GO_BIN="${WORKSPACE_ROOT}/tools/go"
fi
(cd "${OUT_DIR}" && PATH="${WORKSPACE_ROOT}/tools:${PATH}" GOWORK=off "${GO_BIN}" mod tidy)

echo "Generated Go protobuf files are available under ${OUT_DIR}."
