#!/bin/bash

set -e

SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"

if [ "$#" -ne 1 ]; then
    echo "Generates the gRPC service definition for a specified CRD type."
    echo "$0 <Crd name>"
    echo "Example: $0 Model"
    exit
fi

CRD=$1

if [[ ! "${CRD}" =~ ^[A-Z].*$ ]]; then
  echo "ERROR: CRD name <${CRD}> does not start with a capital letter"
  exit
fi

# Check if WORKSPACE_ROOT is set
if [ -z "$WORKSPACE_ROOT" ]; then
    echo "WORKSPACE_ROOT is not set. setting to ${SCRIPT_DIR}/.."
    WORKSPACE_ROOT="${SCRIPT_DIR}/.."
else
    echo "WORKSPACE_ROOT is set to: $WORKSPACE_ROOT"
fi

echo "CRD name: ${CRD}"
SNAKE_CRD="$(echo "${CRD}" | sed -r 's/([A-Z])/_\1/g' | sed 's/^_//' | tr '[:upper:]' '[:lower:]')"
echo "CRD name in snake_case: ${SNAKE_CRD}"

PROTO_PATH="${WORKSPACE_ROOT}/proto/api/v2"
OUTPUT="${PROTO_PATH}/${SNAKE_CRD}_svc.proto"

cat > "${OUTPUT}"  << EOF
// This file is automatically generated by the following command:
// '$0 $@'
//
// Important:
// - This file is generated by a script and should not be manually edited.
// - Any manual changes will be overwritten the next time the generation script is run.
//
// If modifications are needed, update the source proto files and re-run the script.
// For more information, refer to the documentation or contact the maintainers.
EOF

sed "s/CRDCamelName/${CRD}/g" "${SCRIPT_DIR}/grpc-svc-gen.tmpl" \
    | sed "s/crd_snake_name/${SNAKE_CRD}/g" \
    >> "${OUTPUT}"

echo "The gRPC service definition for the specified CRD type has been successfully written to: ${OUTPUT}"
