#!/usr/bin/env bash

if [ $# -lt 1 ]; then
    echo "Generate mocks for the specified interfaces"
    echo "Usage: $0 interface1 [interface2 ...]"
    exit 1
fi

if [ -z "GOPACKAGE" ]; then
    echo "Error: GOPACKAGE is not set or is empty. GOPACKAGE environment variable has to be set by //go:generate."
fi

if [ -z "GOFILE" ]; then
    echo "Error: GOFILE is not set or is empty. GOFILE environment variable has to be set by //go:generate."
fi

# e.g. package/abc.go -> packagemocks/abc_mocks.go
DESTINATION=${GOPACKAGE}mocks/${GOFILE%%.*}_mocks.${GOFILE#*.}

bazel run --run_under "cd $(pwd) &&" @com_github_golang_mock//mockgen -- -source=${GOFILE} -destination=${DESTINATION} -package ${GOPACKAGE}mocks "$@"
