apiVersion: michelangelo.uber.com/v2
kind: Pipeline
metadata:
  namespace: ma-dev-test-uber-one
  name: simple-custom-train

spec:
  type: PIPELINE_TYPE_TRAIN
  manifest:
    path: pipeline_conf.yaml
