load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "go_default_library",
    srcs = [
        "auth.go",
        "bearer.go",
        "config.go",
        "mapping.go",
        "module.go",
    ],
    importpath = "github.com/michelangelo-ai/michelangelo/go/auth",
    visibility = ["//visibility:public"],
    deps = [
        "//go/auth/k8srbac:go_default_library",
        "//go/auth/oidc:go_default_library",
        "@io_k8s_apiserver//pkg/authentication/authenticator:go_default_library",
        "@io_k8s_apiserver//pkg/authentication/user:go_default_library",
        "@io_k8s_apiserver//pkg/authorization/authorizer:go_default_library",
        "@io_k8s_apiserver//pkg/authorization/authorizerfactory:go_default_library",
        "@io_k8s_client_go//kubernetes:go_default_library",
        "@io_k8s_client_go//rest:go_default_library",
        "@org_golang_google_grpc//codes:go_default_library",
        "@org_golang_google_grpc//status:go_default_library",
        "@org_uber_go_config//:go_default_library",
        "@org_uber_go_fx//:go_default_library",
        "@org_uber_go_yarpc//:go_default_library",
        "@org_uber_go_zap//:go_default_library",
    ],
)

go_test(
    name = "go_default_test",
    srcs = [
        "allowall_external_test.go",
        "auth_test.go",
        "bearer_test.go",
        "config_test.go",
        "export_test.go",
        "mapping_external_test.go",
        "module_test.go",
    ],
    embed = [":go_default_library"],
    deps = [
        "//go/logging:go_default_library",
        "//proto/api:go_default_library",
        "//proto/api/v2:go_default_library",
        "@com_github_stretchr_testify//assert:go_default_library",
        "@com_github_stretchr_testify//require:go_default_library",
        "@com_github_uber_go_tally//:go_default_library",
        "@io_k8s_apiextensions_apiserver//pkg/apis/apiextensions/v1:go_default_library",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:go_default_library",
        "@io_k8s_apimachinery//pkg/util/yaml:go_default_library",
        "@io_k8s_apiserver//pkg/authentication/authenticator:go_default_library",
        "@io_k8s_apiserver//pkg/authentication/user:go_default_library",
        "@io_k8s_apiserver//pkg/authorization/authorizer:go_default_library",
        "@io_k8s_client_go//rest:go_default_library",
        "@io_k8s_sigs_controller_runtime//pkg/client:go_default_library",
        "@org_golang_google_grpc//codes:go_default_library",
        "@org_golang_google_grpc//status:go_default_library",
        "@org_uber_go_config//:go_default_library",
        "@org_uber_go_fx//:go_default_library",
        "@org_uber_go_fx//fxtest:go_default_library",
        "@org_uber_go_yarpc//yarpctest:go_default_library",
        "@org_uber_go_zap//:go_default_library",
    ],
)
