// Code generated by protoc-gen-validation. DO NOT EDIT.

package v2

import (
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"reflect"
	"regexp"
	"strconv"
	"strings"

	"github.com/google/uuid"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = reflect.ValueOf
var _ = regexp.MatchString
var _ = uuid.Parse
var _ = mail.ParseAddress
var _ = strings.Contains
var _ = net.ParseIP
var _ = mail.ParseAddress
var _ = url.ParseRequestURI
var _ = codes.InvalidArgument
var _ = status.Error
var _ = strconv.Itoa

// createInferenceServerRequestValidateExt is an extension hook for additional validation logic
var createInferenceServerRequestValidateExt func(*CreateInferenceServerRequest, string) error

func (this *CreateInferenceServerRequest) Validate(prefix string) error {

	{
		v := this.GetInferenceServer()
		n := `inference_server`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetCreateOptions()
		n := `create_options`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if createInferenceServerRequestValidateExt != nil {
		if err := createInferenceServerRequestValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterCreateInferenceServerRequestValidateExt registers an extension validation function
func RegisterCreateInferenceServerRequestValidateExt(f func(*CreateInferenceServerRequest, string) error) {
	createInferenceServerRequestValidateExt = f
}

// createInferenceServerResponseValidateExt is an extension hook for additional validation logic
var createInferenceServerResponseValidateExt func(*CreateInferenceServerResponse, string) error

func (this *CreateInferenceServerResponse) Validate(prefix string) error {

	{
		v := this.GetInferenceServer()
		n := `inference_server`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if createInferenceServerResponseValidateExt != nil {
		if err := createInferenceServerResponseValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterCreateInferenceServerResponseValidateExt registers an extension validation function
func RegisterCreateInferenceServerResponseValidateExt(f func(*CreateInferenceServerResponse, string) error) {
	createInferenceServerResponseValidateExt = f
}

// getInferenceServerRequestValidateExt is an extension hook for additional validation logic
var getInferenceServerRequestValidateExt func(*GetInferenceServerRequest, string) error

func (this *GetInferenceServerRequest) Validate(prefix string) error {

	{
		v := this.GetGetOptions()
		n := `get_options`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if getInferenceServerRequestValidateExt != nil {
		if err := getInferenceServerRequestValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterGetInferenceServerRequestValidateExt registers an extension validation function
func RegisterGetInferenceServerRequestValidateExt(f func(*GetInferenceServerRequest, string) error) {
	getInferenceServerRequestValidateExt = f
}

// getInferenceServerResponseValidateExt is an extension hook for additional validation logic
var getInferenceServerResponseValidateExt func(*GetInferenceServerResponse, string) error

func (this *GetInferenceServerResponse) Validate(prefix string) error {

	{
		v := this.GetInferenceServer()
		n := `inference_server`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if getInferenceServerResponseValidateExt != nil {
		if err := getInferenceServerResponseValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterGetInferenceServerResponseValidateExt registers an extension validation function
func RegisterGetInferenceServerResponseValidateExt(f func(*GetInferenceServerResponse, string) error) {
	getInferenceServerResponseValidateExt = f
}

// updateInferenceServerRequestValidateExt is an extension hook for additional validation logic
var updateInferenceServerRequestValidateExt func(*UpdateInferenceServerRequest, string) error

func (this *UpdateInferenceServerRequest) Validate(prefix string) error {

	{
		v := this.GetInferenceServer()
		n := `inference_server`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetUpdateOptions()
		n := `update_options`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if updateInferenceServerRequestValidateExt != nil {
		if err := updateInferenceServerRequestValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterUpdateInferenceServerRequestValidateExt registers an extension validation function
func RegisterUpdateInferenceServerRequestValidateExt(f func(*UpdateInferenceServerRequest, string) error) {
	updateInferenceServerRequestValidateExt = f
}

// updateInferenceServerResponseValidateExt is an extension hook for additional validation logic
var updateInferenceServerResponseValidateExt func(*UpdateInferenceServerResponse, string) error

func (this *UpdateInferenceServerResponse) Validate(prefix string) error {

	{
		v := this.GetInferenceServer()
		n := `inference_server`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if updateInferenceServerResponseValidateExt != nil {
		if err := updateInferenceServerResponseValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterUpdateInferenceServerResponseValidateExt registers an extension validation function
func RegisterUpdateInferenceServerResponseValidateExt(f func(*UpdateInferenceServerResponse, string) error) {
	updateInferenceServerResponseValidateExt = f
}

// deleteInferenceServerRequestValidateExt is an extension hook for additional validation logic
var deleteInferenceServerRequestValidateExt func(*DeleteInferenceServerRequest, string) error

func (this *DeleteInferenceServerRequest) Validate(prefix string) error {

	{
		v := this.GetDeleteOptions()
		n := `delete_options`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if deleteInferenceServerRequestValidateExt != nil {
		if err := deleteInferenceServerRequestValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterDeleteInferenceServerRequestValidateExt registers an extension validation function
func RegisterDeleteInferenceServerRequestValidateExt(f func(*DeleteInferenceServerRequest, string) error) {
	deleteInferenceServerRequestValidateExt = f
}

// deleteInferenceServerResponseValidateExt is an extension hook for additional validation logic
var deleteInferenceServerResponseValidateExt func(*DeleteInferenceServerResponse, string) error

func (this *DeleteInferenceServerResponse) Validate(prefix string) error {

	// Call extension validation if registered
	if deleteInferenceServerResponseValidateExt != nil {
		if err := deleteInferenceServerResponseValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterDeleteInferenceServerResponseValidateExt registers an extension validation function
func RegisterDeleteInferenceServerResponseValidateExt(f func(*DeleteInferenceServerResponse, string) error) {
	deleteInferenceServerResponseValidateExt = f
}

// deleteInferenceServerCollectionRequestValidateExt is an extension hook for additional validation logic
var deleteInferenceServerCollectionRequestValidateExt func(*DeleteInferenceServerCollectionRequest, string) error

func (this *DeleteInferenceServerCollectionRequest) Validate(prefix string) error {

	{
		v := this.GetDeleteOptions()
		n := `delete_options`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetListOptions()
		n := `list_options`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if deleteInferenceServerCollectionRequestValidateExt != nil {
		if err := deleteInferenceServerCollectionRequestValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterDeleteInferenceServerCollectionRequestValidateExt registers an extension validation function
func RegisterDeleteInferenceServerCollectionRequestValidateExt(f func(*DeleteInferenceServerCollectionRequest, string) error) {
	deleteInferenceServerCollectionRequestValidateExt = f
}

// deleteInferenceServerCollectionResponseValidateExt is an extension hook for additional validation logic
var deleteInferenceServerCollectionResponseValidateExt func(*DeleteInferenceServerCollectionResponse, string) error

func (this *DeleteInferenceServerCollectionResponse) Validate(prefix string) error {

	// Call extension validation if registered
	if deleteInferenceServerCollectionResponseValidateExt != nil {
		if err := deleteInferenceServerCollectionResponseValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterDeleteInferenceServerCollectionResponseValidateExt registers an extension validation function
func RegisterDeleteInferenceServerCollectionResponseValidateExt(f func(*DeleteInferenceServerCollectionResponse, string) error) {
	deleteInferenceServerCollectionResponseValidateExt = f
}

// listInferenceServerRequestValidateExt is an extension hook for additional validation logic
var listInferenceServerRequestValidateExt func(*ListInferenceServerRequest, string) error

func (this *ListInferenceServerRequest) Validate(prefix string) error {

	{
		v := this.GetListOptions()
		n := `list_options`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetListOptionsExt()
		n := `list_options_ext`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if listInferenceServerRequestValidateExt != nil {
		if err := listInferenceServerRequestValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterListInferenceServerRequestValidateExt registers an extension validation function
func RegisterListInferenceServerRequestValidateExt(f func(*ListInferenceServerRequest, string) error) {
	listInferenceServerRequestValidateExt = f
}

// listInferenceServerResponseValidateExt is an extension hook for additional validation logic
var listInferenceServerResponseValidateExt func(*ListInferenceServerResponse, string) error

func (this *ListInferenceServerResponse) Validate(prefix string) error {

	{
		v := this.GetInferenceServerList()
		n := `inference_server_list`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if listInferenceServerResponseValidateExt != nil {
		if err := listInferenceServerResponseValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterListInferenceServerResponseValidateExt registers an extension validation function
func RegisterListInferenceServerResponseValidateExt(f func(*ListInferenceServerResponse, string) error) {
	listInferenceServerResponseValidateExt = f
}
