// Code generated by protoc-gen-validation. DO NOT EDIT.

package v2

import (
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"reflect"
	"regexp"
	"strconv"
	"strings"

	"github.com/google/uuid"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = reflect.ValueOf
var _ = regexp.MatchString
var _ = uuid.Parse
var _ = mail.ParseAddress
var _ = strings.Contains
var _ = net.ParseIP
var _ = mail.ParseAddress
var _ = url.ParseRequestURI
var _ = codes.InvalidArgument
var _ = status.Error
var _ = strconv.Itoa

// resourceAffinityValidateExt is an extension hook for additional validation logic
var resourceAffinityValidateExt func(*ResourceAffinity, string) error

func (this *ResourceAffinity) Validate(prefix string) error {

	{
		v := this.GetSelector()
		n := `selector`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if resourceAffinityValidateExt != nil {
		if err := resourceAffinityValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterResourceAffinityValidateExt registers an extension validation function
func RegisterResourceAffinityValidateExt(f func(*ResourceAffinity, string) error) {
	resourceAffinityValidateExt = f
}

// affinityValidateExt is an extension hook for additional validation logic
var affinityValidateExt func(*Affinity, string) error

func (this *Affinity) Validate(prefix string) error {

	{
		v := this.GetResourceAffinity()
		n := `resource_affinity`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if affinityValidateExt != nil {
		if err := affinityValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterAffinityValidateExt registers an extension validation function
func RegisterAffinityValidateExt(f func(*Affinity, string) error) {
	affinityValidateExt = f
}

// assignmentInfoValidateExt is an extension hook for additional validation logic
var assignmentInfoValidateExt func(*AssignmentInfo, string) error

func (this *AssignmentInfo) Validate(prefix string) error {

	// Call extension validation if registered
	if assignmentInfoValidateExt != nil {
		if err := assignmentInfoValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterAssignmentInfoValidateExt registers an extension validation function
func RegisterAssignmentInfoValidateExt(f func(*AssignmentInfo, string) error) {
	assignmentInfoValidateExt = f
}

// terminationSpecValidateExt is an extension hook for additional validation logic
var terminationSpecValidateExt func(*TerminationSpec, string) error

func (this *TerminationSpec) Validate(prefix string) error {

	// Call extension validation if registered
	if terminationSpecValidateExt != nil {
		if err := terminationSpecValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterTerminationSpecValidateExt registers an extension validation function
func RegisterTerminationSpecValidateExt(f func(*TerminationSpec, string) error) {
	terminationSpecValidateExt = f
}

// schedulingSpecValidateExt is an extension hook for additional validation logic
var schedulingSpecValidateExt func(*SchedulingSpec, string) error

func (this *SchedulingSpec) Validate(prefix string) error {

	// Call extension validation if registered
	if schedulingSpecValidateExt != nil {
		if err := schedulingSpecValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterSchedulingSpecValidateExt registers an extension validation function
func RegisterSchedulingSpecValidateExt(f func(*SchedulingSpec, string) error) {
	schedulingSpecValidateExt = f
}

// schedulingInfoValidateExt is an extension hook for additional validation logic
var schedulingInfoValidateExt func(*SchedulingInfo, string) error

func (this *SchedulingInfo) Validate(prefix string) error {

	{
		v := this.GetLastAttemptTime()
		n := `last_attempt_time`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if schedulingInfoValidateExt != nil {
		if err := schedulingInfoValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterSchedulingInfoValidateExt registers an extension validation function
func RegisterSchedulingInfoValidateExt(f func(*SchedulingInfo, string) error) {
	schedulingInfoValidateExt = f
}
