// Code generated by protoc-gen-validation. DO NOT EDIT.

package v2

import (
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"reflect"
	"regexp"
	"strconv"
	"strings"

	"github.com/google/uuid"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = reflect.ValueOf
var _ = regexp.MatchString
var _ = uuid.Parse
var _ = mail.ParseAddress
var _ = strings.Contains
var _ = net.ParseIP
var _ = mail.ParseAddress
var _ = url.ParseRequestURI
var _ = codes.InvalidArgument
var _ = status.Error
var _ = strconv.Itoa

// modelFamilyStatusValidateExt is an extension hook for additional validation logic
var modelFamilyStatusValidateExt func(*ModelFamilyStatus, string) error

func (this *ModelFamilyStatus) Validate(prefix string) error {

	// Call extension validation if registered
	if modelFamilyStatusValidateExt != nil {
		if err := modelFamilyStatusValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterModelFamilyStatusValidateExt registers an extension validation function
func RegisterModelFamilyStatusValidateExt(f func(*ModelFamilyStatus, string) error) {
	modelFamilyStatusValidateExt = f
}

var ModelFamilySpecPattern0 = regexp.MustCompile("^[a-zA-Z0-9][\\w-]*$")

// modelFamilySpecValidateExt is an extension hook for additional validation logic
var modelFamilySpecValidateExt func(*ModelFamilySpec, string) error

func (this *ModelFamilySpec) Validate(prefix string) error {

	{
		v := this.Name
		n := `name`
		if !ModelFamilySpecPattern0.MatchString(v) {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"must be alphanumeric, underscore or dash")
		}
		if !(len(v) <= 40) {
			return status.Error(codes.InvalidArgument, prefix+n+" "+"must be no more than 40 characters long")
		}
	}
	// Call extension validation if registered
	if modelFamilySpecValidateExt != nil {
		if err := modelFamilySpecValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterModelFamilySpecValidateExt registers an extension validation function
func RegisterModelFamilySpecValidateExt(f func(*ModelFamilySpec, string) error) {
	modelFamilySpecValidateExt = f
}

// modelFamilyValidateExt is an extension hook for additional validation logic
var modelFamilyValidateExt func(*ModelFamily, string) error

func (this *ModelFamily) Validate(prefix string) error {

	{
		v := this.GetTypeMeta()
		n := `type_meta`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetMetadata()
		n := `metadata`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetSpec()
		n := `spec`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetStatus()
		n := `status`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if modelFamilyValidateExt != nil {
		if err := modelFamilyValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterModelFamilyValidateExt registers an extension validation function
func RegisterModelFamilyValidateExt(f func(*ModelFamily, string) error) {
	modelFamilyValidateExt = f
}

// modelFamilyListValidateExt is an extension hook for additional validation logic
var modelFamilyListValidateExt func(*ModelFamilyList, string) error

func (this *ModelFamilyList) Validate(prefix string) error {

	{
		v := this.GetTypeMeta()
		n := `type_meta`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetMetadata()
		n := `metadata`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetItems()
		for i, v := range v {
			n := `items[` + strconv.Itoa(i) + `]`

			var i interface{}
			if reflect.ValueOf(v).Kind() == reflect.Ptr {
				i = reflect.ValueOf(v).Interface()
				if reflect.ValueOf(v).IsNil() {
					i = nil
				}
			} else {
				i = reflect.ValueOf(&v).Interface()
			}
			validate, hasValidate := i.(interface{ Validate(string) error })
			if hasValidate {
				if err := validate.Validate(prefix + n + "."); err != nil {
					return err
				}
			}
		}
	}
	// Call extension validation if registered
	if modelFamilyListValidateExt != nil {
		if err := modelFamilyListValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterModelFamilyListValidateExt registers an extension validation function
func RegisterModelFamilyListValidateExt(f func(*ModelFamilyList, string) error) {
	modelFamilyListValidateExt = f
}
