// Code generated by protoc-gen-validation. DO NOT EDIT.

package v2

import (
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"reflect"
	"regexp"
	"strconv"
	"strings"

	"github.com/google/uuid"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = reflect.ValueOf
var _ = regexp.MatchString
var _ = uuid.Parse
var _ = mail.ParseAddress
var _ = strings.Contains
var _ = net.ParseIP
var _ = mail.ParseAddress
var _ = url.ParseRequestURI
var _ = codes.InvalidArgument
var _ = status.Error
var _ = strconv.Itoa

// createModelFamilyRequestValidateExt is an extension hook for additional validation logic
var createModelFamilyRequestValidateExt func(*CreateModelFamilyRequest, string) error

func (this *CreateModelFamilyRequest) Validate(prefix string) error {

	{
		v := this.GetModelFamily()
		n := `model_family`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetCreateOptions()
		n := `create_options`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if createModelFamilyRequestValidateExt != nil {
		if err := createModelFamilyRequestValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterCreateModelFamilyRequestValidateExt registers an extension validation function
func RegisterCreateModelFamilyRequestValidateExt(f func(*CreateModelFamilyRequest, string) error) {
	createModelFamilyRequestValidateExt = f
}

// createModelFamilyResponseValidateExt is an extension hook for additional validation logic
var createModelFamilyResponseValidateExt func(*CreateModelFamilyResponse, string) error

func (this *CreateModelFamilyResponse) Validate(prefix string) error {

	{
		v := this.GetModelFamily()
		n := `model_family`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if createModelFamilyResponseValidateExt != nil {
		if err := createModelFamilyResponseValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterCreateModelFamilyResponseValidateExt registers an extension validation function
func RegisterCreateModelFamilyResponseValidateExt(f func(*CreateModelFamilyResponse, string) error) {
	createModelFamilyResponseValidateExt = f
}

// getModelFamilyRequestValidateExt is an extension hook for additional validation logic
var getModelFamilyRequestValidateExt func(*GetModelFamilyRequest, string) error

func (this *GetModelFamilyRequest) Validate(prefix string) error {

	{
		v := this.GetGetOptions()
		n := `get_options`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if getModelFamilyRequestValidateExt != nil {
		if err := getModelFamilyRequestValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterGetModelFamilyRequestValidateExt registers an extension validation function
func RegisterGetModelFamilyRequestValidateExt(f func(*GetModelFamilyRequest, string) error) {
	getModelFamilyRequestValidateExt = f
}

// getModelFamilyResponseValidateExt is an extension hook for additional validation logic
var getModelFamilyResponseValidateExt func(*GetModelFamilyResponse, string) error

func (this *GetModelFamilyResponse) Validate(prefix string) error {

	{
		v := this.GetModelFamily()
		n := `model_family`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if getModelFamilyResponseValidateExt != nil {
		if err := getModelFamilyResponseValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterGetModelFamilyResponseValidateExt registers an extension validation function
func RegisterGetModelFamilyResponseValidateExt(f func(*GetModelFamilyResponse, string) error) {
	getModelFamilyResponseValidateExt = f
}

// updateModelFamilyRequestValidateExt is an extension hook for additional validation logic
var updateModelFamilyRequestValidateExt func(*UpdateModelFamilyRequest, string) error

func (this *UpdateModelFamilyRequest) Validate(prefix string) error {

	{
		v := this.GetModelFamily()
		n := `model_family`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetUpdateOptions()
		n := `update_options`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if updateModelFamilyRequestValidateExt != nil {
		if err := updateModelFamilyRequestValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterUpdateModelFamilyRequestValidateExt registers an extension validation function
func RegisterUpdateModelFamilyRequestValidateExt(f func(*UpdateModelFamilyRequest, string) error) {
	updateModelFamilyRequestValidateExt = f
}

// updateModelFamilyResponseValidateExt is an extension hook for additional validation logic
var updateModelFamilyResponseValidateExt func(*UpdateModelFamilyResponse, string) error

func (this *UpdateModelFamilyResponse) Validate(prefix string) error {

	{
		v := this.GetModelFamily()
		n := `model_family`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if updateModelFamilyResponseValidateExt != nil {
		if err := updateModelFamilyResponseValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterUpdateModelFamilyResponseValidateExt registers an extension validation function
func RegisterUpdateModelFamilyResponseValidateExt(f func(*UpdateModelFamilyResponse, string) error) {
	updateModelFamilyResponseValidateExt = f
}

// deleteModelFamilyRequestValidateExt is an extension hook for additional validation logic
var deleteModelFamilyRequestValidateExt func(*DeleteModelFamilyRequest, string) error

func (this *DeleteModelFamilyRequest) Validate(prefix string) error {

	{
		v := this.GetDeleteOptions()
		n := `delete_options`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if deleteModelFamilyRequestValidateExt != nil {
		if err := deleteModelFamilyRequestValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterDeleteModelFamilyRequestValidateExt registers an extension validation function
func RegisterDeleteModelFamilyRequestValidateExt(f func(*DeleteModelFamilyRequest, string) error) {
	deleteModelFamilyRequestValidateExt = f
}

// deleteModelFamilyResponseValidateExt is an extension hook for additional validation logic
var deleteModelFamilyResponseValidateExt func(*DeleteModelFamilyResponse, string) error

func (this *DeleteModelFamilyResponse) Validate(prefix string) error {

	// Call extension validation if registered
	if deleteModelFamilyResponseValidateExt != nil {
		if err := deleteModelFamilyResponseValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterDeleteModelFamilyResponseValidateExt registers an extension validation function
func RegisterDeleteModelFamilyResponseValidateExt(f func(*DeleteModelFamilyResponse, string) error) {
	deleteModelFamilyResponseValidateExt = f
}

// deleteModelFamilyCollectionRequestValidateExt is an extension hook for additional validation logic
var deleteModelFamilyCollectionRequestValidateExt func(*DeleteModelFamilyCollectionRequest, string) error

func (this *DeleteModelFamilyCollectionRequest) Validate(prefix string) error {

	{
		v := this.GetDeleteOptions()
		n := `delete_options`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetListOptions()
		n := `list_options`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if deleteModelFamilyCollectionRequestValidateExt != nil {
		if err := deleteModelFamilyCollectionRequestValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterDeleteModelFamilyCollectionRequestValidateExt registers an extension validation function
func RegisterDeleteModelFamilyCollectionRequestValidateExt(f func(*DeleteModelFamilyCollectionRequest, string) error) {
	deleteModelFamilyCollectionRequestValidateExt = f
}

// deleteModelFamilyCollectionResponseValidateExt is an extension hook for additional validation logic
var deleteModelFamilyCollectionResponseValidateExt func(*DeleteModelFamilyCollectionResponse, string) error

func (this *DeleteModelFamilyCollectionResponse) Validate(prefix string) error {

	// Call extension validation if registered
	if deleteModelFamilyCollectionResponseValidateExt != nil {
		if err := deleteModelFamilyCollectionResponseValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterDeleteModelFamilyCollectionResponseValidateExt registers an extension validation function
func RegisterDeleteModelFamilyCollectionResponseValidateExt(f func(*DeleteModelFamilyCollectionResponse, string) error) {
	deleteModelFamilyCollectionResponseValidateExt = f
}

// listModelFamilyRequestValidateExt is an extension hook for additional validation logic
var listModelFamilyRequestValidateExt func(*ListModelFamilyRequest, string) error

func (this *ListModelFamilyRequest) Validate(prefix string) error {

	{
		v := this.GetListOptions()
		n := `list_options`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetListOptionsExt()
		n := `list_options_ext`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if listModelFamilyRequestValidateExt != nil {
		if err := listModelFamilyRequestValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterListModelFamilyRequestValidateExt registers an extension validation function
func RegisterListModelFamilyRequestValidateExt(f func(*ListModelFamilyRequest, string) error) {
	listModelFamilyRequestValidateExt = f
}

// listModelFamilyResponseValidateExt is an extension hook for additional validation logic
var listModelFamilyResponseValidateExt func(*ListModelFamilyResponse, string) error

func (this *ListModelFamilyResponse) Validate(prefix string) error {

	{
		v := this.GetModelFamilyList()
		n := `model_family_list`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if listModelFamilyResponseValidateExt != nil {
		if err := listModelFamilyResponseValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterListModelFamilyResponseValidateExt registers an extension validation function
func RegisterListModelFamilyResponseValidateExt(f func(*ListModelFamilyResponse, string) error) {
	listModelFamilyResponseValidateExt = f
}
