// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: michelangelo/api/v2/notification.proto

package v2

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strconv "strconv"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Notification_NotificationType int32

const (
	NOTIFICATION_TYPE_INVALID Notification_NotificationType = 0
	NOTIFICATION_TYPE_EMAIL   Notification_NotificationType = 1
	NOTIFICATION_TYPE_SLACK   Notification_NotificationType = 2
)

var Notification_NotificationType_name = map[int32]string{
	0: "NOTIFICATION_TYPE_INVALID",
	1: "NOTIFICATION_TYPE_EMAIL",
	2: "NOTIFICATION_TYPE_SLACK",
}

var Notification_NotificationType_value = map[string]int32{
	"NOTIFICATION_TYPE_INVALID": 0,
	"NOTIFICATION_TYPE_EMAIL":   1,
	"NOTIFICATION_TYPE_SLACK":   2,
}

func (Notification_NotificationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_89ac3eaa9d840f74, []int{0, 0}
}

type Notification_EventType int32

const (
	EVENT_TYPE_INVALID                      Notification_EventType = 0
	EVENT_TYPE_PIPELINE_RUN_STATE_SUCCEEDED Notification_EventType = 1
	EVENT_TYPE_PIPELINE_RUN_STATE_KILLED    Notification_EventType = 2
	EVENT_TYPE_PIPELINE_RUN_STATE_FAILED    Notification_EventType = 3
	EVENT_TYPE_PIPELINE_RUN_STATE_SKIPPED   Notification_EventType = 4
	EVENT_TYPE_TRIGGER_RUN_STATE_KILLED     Notification_EventType = 5
	EVENT_TYPE_TRIGGER_RUN_STATE_FAILED     Notification_EventType = 6
	EVENT_TYPE_TRIGGER_RUN_STATE_SUCCEEDED  Notification_EventType = 7
	EVENT_TYPE_PIPELINE_STATE_READY         Notification_EventType = 8
	EVENT_TYPE_PIPELINE_STATE_ERROR         Notification_EventType = 9
	EVENT_TYPE_PIPELINE_RUN_STATE_RUNNING   Notification_EventType = 10 // Deprecated: Do not use.
	EVENT_TYPE_PIPELINE_RUN_STATE_STARTED   Notification_EventType = 11
)

var Notification_EventType_name = map[int32]string{
	0:  "EVENT_TYPE_INVALID",
	1:  "EVENT_TYPE_PIPELINE_RUN_STATE_SUCCEEDED",
	2:  "EVENT_TYPE_PIPELINE_RUN_STATE_KILLED",
	3:  "EVENT_TYPE_PIPELINE_RUN_STATE_FAILED",
	4:  "EVENT_TYPE_PIPELINE_RUN_STATE_SKIPPED",
	5:  "EVENT_TYPE_TRIGGER_RUN_STATE_KILLED",
	6:  "EVENT_TYPE_TRIGGER_RUN_STATE_FAILED",
	7:  "EVENT_TYPE_TRIGGER_RUN_STATE_SUCCEEDED",
	8:  "EVENT_TYPE_PIPELINE_STATE_READY",
	9:  "EVENT_TYPE_PIPELINE_STATE_ERROR",
	10: "EVENT_TYPE_PIPELINE_RUN_STATE_RUNNING",
	11: "EVENT_TYPE_PIPELINE_RUN_STATE_STARTED",
}

var Notification_EventType_value = map[string]int32{
	"EVENT_TYPE_INVALID":                      0,
	"EVENT_TYPE_PIPELINE_RUN_STATE_SUCCEEDED": 1,
	"EVENT_TYPE_PIPELINE_RUN_STATE_KILLED":    2,
	"EVENT_TYPE_PIPELINE_RUN_STATE_FAILED":    3,
	"EVENT_TYPE_PIPELINE_RUN_STATE_SKIPPED":   4,
	"EVENT_TYPE_TRIGGER_RUN_STATE_KILLED":     5,
	"EVENT_TYPE_TRIGGER_RUN_STATE_FAILED":     6,
	"EVENT_TYPE_TRIGGER_RUN_STATE_SUCCEEDED":  7,
	"EVENT_TYPE_PIPELINE_STATE_READY":         8,
	"EVENT_TYPE_PIPELINE_STATE_ERROR":         9,
	"EVENT_TYPE_PIPELINE_RUN_STATE_RUNNING":   10,
	"EVENT_TYPE_PIPELINE_RUN_STATE_STARTED":   11,
}

func (Notification_EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_89ac3eaa9d840f74, []int{0, 1}
}

type Notification_ResourceType int32

const (
	RESOURCE_TYPE_INVALID      Notification_ResourceType = 0
	RESOURCE_TYPE_PIPELINE_RUN Notification_ResourceType = 1
	RESOURCE_TYPE_TRIGGER_RUN  Notification_ResourceType = 2
	RESOURCE_TYPE_PIPELINE     Notification_ResourceType = 3
)

var Notification_ResourceType_name = map[int32]string{
	0: "RESOURCE_TYPE_INVALID",
	1: "RESOURCE_TYPE_PIPELINE_RUN",
	2: "RESOURCE_TYPE_TRIGGER_RUN",
	3: "RESOURCE_TYPE_PIPELINE",
}

var Notification_ResourceType_value = map[string]int32{
	"RESOURCE_TYPE_INVALID":      0,
	"RESOURCE_TYPE_PIPELINE_RUN": 1,
	"RESOURCE_TYPE_TRIGGER_RUN":  2,
	"RESOURCE_TYPE_PIPELINE":     3,
}

func (Notification_ResourceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_89ac3eaa9d840f74, []int{0, 2}
}

type Notification struct {
	NotificationType  Notification_NotificationType `protobuf:"varint,1,opt,name=notification_type,json=notificationType,proto3,enum=michelangelo.api.v2.Notification_NotificationType" json:"notificationType,omitempty"`
	EventTypes        []Notification_EventType      `protobuf:"varint,2,rep,packed,name=event_types,json=eventTypes,proto3,enum=michelangelo.api.v2.Notification_EventType" json:"eventTypes,omitempty"`
	ResourceType      Notification_ResourceType     `protobuf:"varint,3,opt,name=resource_type,json=resourceType,proto3,enum=michelangelo.api.v2.Notification_ResourceType" json:"resourceType,omitempty"`
	Emails            []string                      `protobuf:"bytes,4,rep,name=emails,proto3" json:"emails,omitempty"`
	SlackDestinations []string                      `protobuf:"bytes,5,rep,name=slack_destinations,json=slackDestinations,proto3" json:"slackDestinations,omitempty"`
	CiReproTestField  string                        `protobuf:"bytes,6,opt,name=ci_repro_test_field,json=ciReproTestField,proto3" json:"ciReproTestField,omitempty"`
}

func (m *Notification) Reset()      { *m = Notification{} }
func (*Notification) ProtoMessage() {}
func (*Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_89ac3eaa9d840f74, []int{0}
}
func (m *Notification) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Notification.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notification.Merge(m, src)
}
func (m *Notification) XXX_Size() int {
	return m.Size()
}
func (m *Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_Notification proto.InternalMessageInfo

func (m *Notification) GetNotificationType() Notification_NotificationType {
	if m != nil {
		return m.NotificationType
	}
	return NOTIFICATION_TYPE_INVALID
}

func (m *Notification) GetEventTypes() []Notification_EventType {
	if m != nil {
		return m.EventTypes
	}
	return nil
}

func (m *Notification) GetResourceType() Notification_ResourceType {
	if m != nil {
		return m.ResourceType
	}
	return RESOURCE_TYPE_INVALID
}

func (m *Notification) GetEmails() []string {
	if m != nil {
		return m.Emails
	}
	return nil
}

func (m *Notification) GetSlackDestinations() []string {
	if m != nil {
		return m.SlackDestinations
	}
	return nil
}

func (m *Notification) GetCiReproTestField() string {
	if m != nil {
		return m.CiReproTestField
	}
	return ""
}

func init() {
	proto.RegisterEnum("michelangelo.api.v2.Notification_NotificationType", Notification_NotificationType_name, Notification_NotificationType_value)
	proto.RegisterEnum("michelangelo.api.v2.Notification_EventType", Notification_EventType_name, Notification_EventType_value)
	proto.RegisterEnum("michelangelo.api.v2.Notification_ResourceType", Notification_ResourceType_name, Notification_ResourceType_value)
	proto.RegisterType((*Notification)(nil), "michelangelo.api.v2.Notification")
}

func init() {
	proto.RegisterFile("michelangelo/api/v2/notification.proto", fileDescriptor_89ac3eaa9d840f74)
}

var fileDescriptor_89ac3eaa9d840f74 = []byte{
	// 581 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xc1, 0x4e, 0xdb, 0x40,
	0x10, 0x86, 0xbd, 0x09, 0xa4, 0x64, 0xa0, 0x68, 0x59, 0x54, 0x1a, 0xa8, 0xba, 0x8d, 0x42, 0x0b,
	0x69, 0x11, 0x41, 0x72, 0xfb, 0x02, 0x6e, 0xbc, 0xa0, 0x15, 0xae, 0x13, 0x6d, 0x1c, 0x24, 0x7a,
	0xb1, 0x5c, 0xb3, 0xb4, 0x16, 0xc1, 0xb6, 0x6c, 0x37, 0x12, 0xb7, 0x1e, 0xfa, 0x00, 0x7d, 0xac,
	0x1e, 0x39, 0x72, 0x2c, 0xe6, 0xd2, 0x23, 0x7d, 0x83, 0x2a, 0x86, 0xb6, 0x26, 0x44, 0x71, 0x6f,
	0x99, 0xf9, 0xbf, 0xff, 0xdf, 0xd9, 0xc9, 0xca, 0xb0, 0x71, 0xea, 0xb9, 0x9f, 0xe4, 0xc0, 0xf1,
	0x3f, 0xca, 0x41, 0xb0, 0xe3, 0x84, 0xde, 0xce, 0x50, 0xdd, 0xf1, 0x83, 0xc4, 0x3b, 0xf6, 0x5c,
	0x27, 0xf1, 0x02, 0xbf, 0x15, 0x46, 0x41, 0x12, 0x90, 0xe5, 0x3c, 0xd7, 0x72, 0x42, 0xaf, 0x35,
	0x54, 0x1b, 0xd7, 0x73, 0xb0, 0x60, 0xe6, 0x58, 0x62, 0xc3, 0x52, 0xde, 0x6b, 0x27, 0x67, 0xa1,
	0xac, 0xa1, 0x3a, 0x6a, 0x2e, 0xaa, 0x6a, 0x6b, 0x42, 0x42, 0x2b, 0xef, 0xbe, 0x53, 0x58, 0x67,
	0xa1, 0x14, 0xd8, 0x1f, 0xeb, 0x10, 0x03, 0xe6, 0xe5, 0x50, 0xfa, 0x49, 0x96, 0x1c, 0xd7, 0x4a,
	0xf5, 0x72, 0x73, 0x51, 0xdd, 0x2a, 0x8e, 0x66, 0x23, 0x53, 0x96, 0x09, 0xf2, 0xcf, 0xcf, 0x98,
	0xf4, 0xe0, 0x61, 0x24, 0xe3, 0xe0, 0x73, 0xe4, 0xca, 0x9b, 0x51, 0xcb, 0xd9, 0xa8, 0xad, 0xe2,
	0x3c, 0x71, 0x6b, 0xcb, 0x22, 0x17, 0xa2, 0x5c, 0x45, 0x56, 0xa0, 0x22, 0x4f, 0x1d, 0x6f, 0x10,
	0xd7, 0x66, 0xea, 0xe5, 0x66, 0x55, 0xdc, 0x56, 0x64, 0x1b, 0x48, 0x3c, 0x70, 0xdc, 0x13, 0xfb,
	0x48, 0xc6, 0x89, 0xe7, 0x67, 0x39, 0x71, 0x6d, 0x36, 0x63, 0x96, 0x32, 0x45, 0xcf, 0x09, 0x64,
	0x1b, 0x96, 0x5d, 0xcf, 0x8e, 0x64, 0x18, 0x05, 0x76, 0x22, 0xe3, 0xc4, 0x3e, 0xf6, 0xe4, 0xe0,
	0xa8, 0x56, 0xa9, 0xa3, 0x66, 0x55, 0x60, 0xd7, 0x13, 0x23, 0xc5, 0x92, 0x71, 0xb2, 0x3b, 0xea,
	0x37, 0x4e, 0x00, 0x8f, 0xaf, 0x8f, 0x3c, 0x85, 0x55, 0xb3, 0x63, 0xf1, 0x5d, 0xde, 0xd6, 0x2c,
	0xde, 0x31, 0x6d, 0xeb, 0xb0, 0xcb, 0x6c, 0x6e, 0x1e, 0x68, 0x06, 0xd7, 0xb1, 0x42, 0x9e, 0xc0,
	0xe3, 0xfb, 0x32, 0x7b, 0xa7, 0x71, 0x03, 0xa3, 0xc9, 0x62, 0xcf, 0xd0, 0xda, 0xfb, 0xb8, 0xd4,
	0xf8, 0x55, 0x86, 0xea, 0xdf, 0x8d, 0x92, 0x15, 0x20, 0xec, 0x80, 0x99, 0xd6, 0x78, 0xfe, 0x16,
	0x6c, 0xe6, 0xfa, 0x5d, 0xde, 0x65, 0x06, 0x37, 0x99, 0x2d, 0xfa, 0xa6, 0xdd, 0xb3, 0x34, 0x8b,
	0xd9, 0xbd, 0x7e, 0xbb, 0xcd, 0x98, 0xce, 0x74, 0x8c, 0x48, 0x13, 0x9e, 0x4f, 0x87, 0xf7, 0xb9,
	0x61, 0x30, 0x1d, 0x97, 0x8a, 0xc9, 0x5d, 0x8d, 0x8f, 0xc8, 0x32, 0x79, 0x09, 0x2f, 0x0a, 0x06,
	0xd8, 0xe7, 0xdd, 0x2e, 0xd3, 0xf1, 0x0c, 0xd9, 0x84, 0xf5, 0x1c, 0x6a, 0x09, 0xbe, 0xb7, 0xc7,
	0xc4, 0xfd, 0xd3, 0x67, 0x0b, 0xc1, 0xdb, 0xc3, 0x2b, 0xe4, 0x15, 0x6c, 0x4c, 0x05, 0xff, 0x5d,
	0xfe, 0x01, 0x59, 0x87, 0x67, 0x93, 0x06, 0xbd, 0x01, 0x05, 0xd3, 0xf4, 0x43, 0x3c, 0x37, 0x1d,
	0x62, 0x42, 0x74, 0x04, 0xae, 0x92, 0xed, 0xa2, 0x2b, 0x8b, 0xbe, 0x69, 0x72, 0x73, 0x0f, 0xc3,
	0x5a, 0x69, 0x0e, 0xfd, 0xc7, 0x86, 0x2c, 0x4d, 0x58, 0x4c, 0xc7, 0xf3, 0x8d, 0xaf, 0x08, 0x16,
	0xf2, 0xaf, 0x9e, 0xac, 0xc2, 0x23, 0xc1, 0x7a, 0x9d, 0xbe, 0x68, 0xb3, 0xf1, 0x7f, 0x9e, 0xc2,
	0xda, 0x5d, 0x29, 0x9f, 0x8c, 0xd1, 0xe8, 0x61, 0xde, 0xd5, 0x73, 0xeb, 0xc1, 0x25, 0xb2, 0x06,
	0x2b, 0x93, 0xed, 0xb8, 0xfc, 0xf6, 0xcd, 0xf9, 0x25, 0x55, 0x2e, 0x2e, 0xa9, 0x72, 0x7d, 0x49,
	0xd1, 0x97, 0x94, 0xa2, 0xef, 0x29, 0x45, 0xe7, 0x29, 0x45, 0x3f, 0x52, 0x8a, 0x7e, 0xa6, 0x54,
	0xb9, 0x4e, 0x29, 0xfa, 0x76, 0x45, 0x95, 0xf3, 0x2b, 0xaa, 0x5c, 0x5c, 0x51, 0xe5, 0x7d, 0x69,
	0xa8, 0x7e, 0xa8, 0x64, 0x1f, 0xb1, 0xd7, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x42, 0x83,
	0x84, 0xee, 0x04, 0x00, 0x00,
}

func (x Notification_NotificationType) String() string {
	s, ok := Notification_NotificationType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x Notification_EventType) String() string {
	s, ok := Notification_EventType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x Notification_ResourceType) String() string {
	s, ok := Notification_ResourceType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *Notification) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 10)
	s = append(s, "&v2.Notification{")
	s = append(s, "NotificationType: "+fmt.Sprintf("%#v", this.NotificationType)+",\n")
	s = append(s, "EventTypes: "+fmt.Sprintf("%#v", this.EventTypes)+",\n")
	s = append(s, "ResourceType: "+fmt.Sprintf("%#v", this.ResourceType)+",\n")
	s = append(s, "Emails: "+fmt.Sprintf("%#v", this.Emails)+",\n")
	s = append(s, "SlackDestinations: "+fmt.Sprintf("%#v", this.SlackDestinations)+",\n")
	s = append(s, "CiReproTestField: "+fmt.Sprintf("%#v", this.CiReproTestField)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringNotification(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *Notification) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Notification) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Notification) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CiReproTestField) > 0 {
		i -= len(m.CiReproTestField)
		copy(dAtA[i:], m.CiReproTestField)
		i = encodeVarintNotification(dAtA, i, uint64(len(m.CiReproTestField)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.SlackDestinations) > 0 {
		for iNdEx := len(m.SlackDestinations) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.SlackDestinations[iNdEx])
			copy(dAtA[i:], m.SlackDestinations[iNdEx])
			i = encodeVarintNotification(dAtA, i, uint64(len(m.SlackDestinations[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Emails) > 0 {
		for iNdEx := len(m.Emails) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Emails[iNdEx])
			copy(dAtA[i:], m.Emails[iNdEx])
			i = encodeVarintNotification(dAtA, i, uint64(len(m.Emails[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if m.ResourceType != 0 {
		i = encodeVarintNotification(dAtA, i, uint64(m.ResourceType))
		i--
		dAtA[i] = 0x18
	}
	if len(m.EventTypes) > 0 {
		dAtA2 := make([]byte, len(m.EventTypes)*10)
		var j1 int
		for _, num := range m.EventTypes {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintNotification(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x12
	}
	if m.NotificationType != 0 {
		i = encodeVarintNotification(dAtA, i, uint64(m.NotificationType))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintNotification(dAtA []byte, offset int, v uint64) int {
	offset -= sovNotification(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Notification) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NotificationType != 0 {
		n += 1 + sovNotification(uint64(m.NotificationType))
	}
	if len(m.EventTypes) > 0 {
		l = 0
		for _, e := range m.EventTypes {
			l += sovNotification(uint64(e))
		}
		n += 1 + sovNotification(uint64(l)) + l
	}
	if m.ResourceType != 0 {
		n += 1 + sovNotification(uint64(m.ResourceType))
	}
	if len(m.Emails) > 0 {
		for _, s := range m.Emails {
			l = len(s)
			n += 1 + l + sovNotification(uint64(l))
		}
	}
	if len(m.SlackDestinations) > 0 {
		for _, s := range m.SlackDestinations {
			l = len(s)
			n += 1 + l + sovNotification(uint64(l))
		}
	}
	l = len(m.CiReproTestField)
	if l > 0 {
		n += 1 + l + sovNotification(uint64(l))
	}
	return n
}

func sovNotification(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozNotification(x uint64) (n int) {
	return sovNotification(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Notification) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Notification{`,
		`NotificationType:` + fmt.Sprintf("%v", this.NotificationType) + `,`,
		`EventTypes:` + fmt.Sprintf("%v", this.EventTypes) + `,`,
		`ResourceType:` + fmt.Sprintf("%v", this.ResourceType) + `,`,
		`Emails:` + fmt.Sprintf("%v", this.Emails) + `,`,
		`SlackDestinations:` + fmt.Sprintf("%v", this.SlackDestinations) + `,`,
		`CiReproTestField:` + fmt.Sprintf("%v", this.CiReproTestField) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringNotification(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *Notification) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNotification
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Notification: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Notification: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NotificationType", wireType)
			}
			m.NotificationType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNotification
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NotificationType |= Notification_NotificationType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType == 0 {
				var v Notification_EventType
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowNotification
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= Notification_EventType(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.EventTypes = append(m.EventTypes, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowNotification
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthNotification
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthNotification
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				if elementCount != 0 && len(m.EventTypes) == 0 {
					m.EventTypes = make([]Notification_EventType, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v Notification_EventType
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowNotification
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= Notification_EventType(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.EventTypes = append(m.EventTypes, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field EventTypes", wireType)
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResourceType", wireType)
			}
			m.ResourceType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNotification
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ResourceType |= Notification_ResourceType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Emails", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNotification
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNotification
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNotification
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Emails = append(m.Emails, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlackDestinations", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNotification
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNotification
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNotification
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SlackDestinations = append(m.SlackDestinations, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CiReproTestField", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNotification
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNotification
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNotification
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CiReproTestField = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNotification(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNotification
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipNotification(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowNotification
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNotification
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNotification
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthNotification
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupNotification
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthNotification
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthNotification        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowNotification          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupNotification = fmt.Errorf("proto: unexpected end of group")
)
