// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: michelangelo/api/v2/pipeline_run_svc.proto

package v2

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	api "github.com/michelangelo-ai/michelangelo/proto-go/api"
	io "io"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CreatePipelineRunRequest struct {
	PipelineRun   *PipelineRun          `protobuf:"bytes,1,opt,name=pipeline_run,json=pipelineRun,proto3" json:"pipelineRun,omitempty"`
	CreateOptions *metav1.CreateOptions `protobuf:"bytes,2,opt,name=create_options,json=createOptions,proto3" json:"createOptions,omitempty"`
}

func (m *CreatePipelineRunRequest) Reset()      { *m = CreatePipelineRunRequest{} }
func (*CreatePipelineRunRequest) ProtoMessage() {}
func (*CreatePipelineRunRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a53f9b87794e3c8, []int{0}
}
func (m *CreatePipelineRunRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreatePipelineRunRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreatePipelineRunRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreatePipelineRunRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePipelineRunRequest.Merge(m, src)
}
func (m *CreatePipelineRunRequest) XXX_Size() int {
	return m.Size()
}
func (m *CreatePipelineRunRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePipelineRunRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePipelineRunRequest proto.InternalMessageInfo

func (m *CreatePipelineRunRequest) GetPipelineRun() *PipelineRun {
	if m != nil {
		return m.PipelineRun
	}
	return nil
}

func (m *CreatePipelineRunRequest) GetCreateOptions() *metav1.CreateOptions {
	if m != nil {
		return m.CreateOptions
	}
	return nil
}

type CreatePipelineRunResponse struct {
	PipelineRun *PipelineRun `protobuf:"bytes,1,opt,name=pipeline_run,json=pipelineRun,proto3" json:"pipelineRun,omitempty"`
}

func (m *CreatePipelineRunResponse) Reset()      { *m = CreatePipelineRunResponse{} }
func (*CreatePipelineRunResponse) ProtoMessage() {}
func (*CreatePipelineRunResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a53f9b87794e3c8, []int{1}
}
func (m *CreatePipelineRunResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreatePipelineRunResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreatePipelineRunResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreatePipelineRunResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePipelineRunResponse.Merge(m, src)
}
func (m *CreatePipelineRunResponse) XXX_Size() int {
	return m.Size()
}
func (m *CreatePipelineRunResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePipelineRunResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePipelineRunResponse proto.InternalMessageInfo

func (m *CreatePipelineRunResponse) GetPipelineRun() *PipelineRun {
	if m != nil {
		return m.PipelineRun
	}
	return nil
}

type GetPipelineRunRequest struct {
	Name       string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace  string             `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	GetOptions *metav1.GetOptions `protobuf:"bytes,3,opt,name=get_options,json=getOptions,proto3" json:"getOptions,omitempty"`
}

func (m *GetPipelineRunRequest) Reset()      { *m = GetPipelineRunRequest{} }
func (*GetPipelineRunRequest) ProtoMessage() {}
func (*GetPipelineRunRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a53f9b87794e3c8, []int{2}
}
func (m *GetPipelineRunRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetPipelineRunRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetPipelineRunRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetPipelineRunRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPipelineRunRequest.Merge(m, src)
}
func (m *GetPipelineRunRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetPipelineRunRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPipelineRunRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPipelineRunRequest proto.InternalMessageInfo

func (m *GetPipelineRunRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetPipelineRunRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *GetPipelineRunRequest) GetGetOptions() *metav1.GetOptions {
	if m != nil {
		return m.GetOptions
	}
	return nil
}

type GetPipelineRunResponse struct {
	PipelineRun *PipelineRun `protobuf:"bytes,1,opt,name=pipeline_run,json=pipelineRun,proto3" json:"pipelineRun,omitempty"`
}

func (m *GetPipelineRunResponse) Reset()      { *m = GetPipelineRunResponse{} }
func (*GetPipelineRunResponse) ProtoMessage() {}
func (*GetPipelineRunResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a53f9b87794e3c8, []int{3}
}
func (m *GetPipelineRunResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetPipelineRunResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetPipelineRunResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetPipelineRunResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPipelineRunResponse.Merge(m, src)
}
func (m *GetPipelineRunResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetPipelineRunResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPipelineRunResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPipelineRunResponse proto.InternalMessageInfo

func (m *GetPipelineRunResponse) GetPipelineRun() *PipelineRun {
	if m != nil {
		return m.PipelineRun
	}
	return nil
}

type UpdatePipelineRunRequest struct {
	PipelineRun   *PipelineRun          `protobuf:"bytes,1,opt,name=pipeline_run,json=pipelineRun,proto3" json:"pipelineRun,omitempty"`
	UpdateOptions *metav1.UpdateOptions `protobuf:"bytes,2,opt,name=update_options,json=updateOptions,proto3" json:"updateOptions,omitempty"`
}

func (m *UpdatePipelineRunRequest) Reset()      { *m = UpdatePipelineRunRequest{} }
func (*UpdatePipelineRunRequest) ProtoMessage() {}
func (*UpdatePipelineRunRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a53f9b87794e3c8, []int{4}
}
func (m *UpdatePipelineRunRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UpdatePipelineRunRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UpdatePipelineRunRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UpdatePipelineRunRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePipelineRunRequest.Merge(m, src)
}
func (m *UpdatePipelineRunRequest) XXX_Size() int {
	return m.Size()
}
func (m *UpdatePipelineRunRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePipelineRunRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePipelineRunRequest proto.InternalMessageInfo

func (m *UpdatePipelineRunRequest) GetPipelineRun() *PipelineRun {
	if m != nil {
		return m.PipelineRun
	}
	return nil
}

func (m *UpdatePipelineRunRequest) GetUpdateOptions() *metav1.UpdateOptions {
	if m != nil {
		return m.UpdateOptions
	}
	return nil
}

type UpdatePipelineRunResponse struct {
	PipelineRun *PipelineRun `protobuf:"bytes,1,opt,name=pipeline_run,json=pipelineRun,proto3" json:"pipelineRun,omitempty"`
}

func (m *UpdatePipelineRunResponse) Reset()      { *m = UpdatePipelineRunResponse{} }
func (*UpdatePipelineRunResponse) ProtoMessage() {}
func (*UpdatePipelineRunResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a53f9b87794e3c8, []int{5}
}
func (m *UpdatePipelineRunResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UpdatePipelineRunResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UpdatePipelineRunResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UpdatePipelineRunResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePipelineRunResponse.Merge(m, src)
}
func (m *UpdatePipelineRunResponse) XXX_Size() int {
	return m.Size()
}
func (m *UpdatePipelineRunResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePipelineRunResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePipelineRunResponse proto.InternalMessageInfo

func (m *UpdatePipelineRunResponse) GetPipelineRun() *PipelineRun {
	if m != nil {
		return m.PipelineRun
	}
	return nil
}

type DeletePipelineRunRequest struct {
	Name          string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	DeleteOptions *metav1.DeleteOptions `protobuf:"bytes,3,opt,name=delete_options,json=deleteOptions,proto3" json:"deleteOptions,omitempty"`
}

func (m *DeletePipelineRunRequest) Reset()      { *m = DeletePipelineRunRequest{} }
func (*DeletePipelineRunRequest) ProtoMessage() {}
func (*DeletePipelineRunRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a53f9b87794e3c8, []int{6}
}
func (m *DeletePipelineRunRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DeletePipelineRunRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DeletePipelineRunRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DeletePipelineRunRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePipelineRunRequest.Merge(m, src)
}
func (m *DeletePipelineRunRequest) XXX_Size() int {
	return m.Size()
}
func (m *DeletePipelineRunRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePipelineRunRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePipelineRunRequest proto.InternalMessageInfo

func (m *DeletePipelineRunRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeletePipelineRunRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *DeletePipelineRunRequest) GetDeleteOptions() *metav1.DeleteOptions {
	if m != nil {
		return m.DeleteOptions
	}
	return nil
}

type DeletePipelineRunResponse struct {
}

func (m *DeletePipelineRunResponse) Reset()      { *m = DeletePipelineRunResponse{} }
func (*DeletePipelineRunResponse) ProtoMessage() {}
func (*DeletePipelineRunResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a53f9b87794e3c8, []int{7}
}
func (m *DeletePipelineRunResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DeletePipelineRunResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DeletePipelineRunResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DeletePipelineRunResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePipelineRunResponse.Merge(m, src)
}
func (m *DeletePipelineRunResponse) XXX_Size() int {
	return m.Size()
}
func (m *DeletePipelineRunResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePipelineRunResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePipelineRunResponse proto.InternalMessageInfo

type DeletePipelineRunCollectionRequest struct {
	Namespace     string                `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	DeleteOptions *metav1.DeleteOptions `protobuf:"bytes,2,opt,name=delete_options,json=deleteOptions,proto3" json:"deleteOptions,omitempty"`
	ListOptions   *metav1.ListOptions   `protobuf:"bytes,3,opt,name=list_options,json=listOptions,proto3" json:"listOptions,omitempty"`
}

func (m *DeletePipelineRunCollectionRequest) Reset()      { *m = DeletePipelineRunCollectionRequest{} }
func (*DeletePipelineRunCollectionRequest) ProtoMessage() {}
func (*DeletePipelineRunCollectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a53f9b87794e3c8, []int{8}
}
func (m *DeletePipelineRunCollectionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DeletePipelineRunCollectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DeletePipelineRunCollectionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DeletePipelineRunCollectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePipelineRunCollectionRequest.Merge(m, src)
}
func (m *DeletePipelineRunCollectionRequest) XXX_Size() int {
	return m.Size()
}
func (m *DeletePipelineRunCollectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePipelineRunCollectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePipelineRunCollectionRequest proto.InternalMessageInfo

func (m *DeletePipelineRunCollectionRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *DeletePipelineRunCollectionRequest) GetDeleteOptions() *metav1.DeleteOptions {
	if m != nil {
		return m.DeleteOptions
	}
	return nil
}

func (m *DeletePipelineRunCollectionRequest) GetListOptions() *metav1.ListOptions {
	if m != nil {
		return m.ListOptions
	}
	return nil
}

type DeletePipelineRunCollectionResponse struct {
}

func (m *DeletePipelineRunCollectionResponse) Reset()      { *m = DeletePipelineRunCollectionResponse{} }
func (*DeletePipelineRunCollectionResponse) ProtoMessage() {}
func (*DeletePipelineRunCollectionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a53f9b87794e3c8, []int{9}
}
func (m *DeletePipelineRunCollectionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DeletePipelineRunCollectionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DeletePipelineRunCollectionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DeletePipelineRunCollectionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePipelineRunCollectionResponse.Merge(m, src)
}
func (m *DeletePipelineRunCollectionResponse) XXX_Size() int {
	return m.Size()
}
func (m *DeletePipelineRunCollectionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePipelineRunCollectionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePipelineRunCollectionResponse proto.InternalMessageInfo

type ListPipelineRunRequest struct {
	Namespace      string              `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ListOptions    *metav1.ListOptions `protobuf:"bytes,2,opt,name=list_options,json=listOptions,proto3" json:"listOptions,omitempty"`
	ListOptionsExt *api.ListOptionsExt `protobuf:"bytes,3,opt,name=list_options_ext,json=listOptionsExt,proto3" json:"listOptionsExt,omitempty"`
}

func (m *ListPipelineRunRequest) Reset()      { *m = ListPipelineRunRequest{} }
func (*ListPipelineRunRequest) ProtoMessage() {}
func (*ListPipelineRunRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a53f9b87794e3c8, []int{10}
}
func (m *ListPipelineRunRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListPipelineRunRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListPipelineRunRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListPipelineRunRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPipelineRunRequest.Merge(m, src)
}
func (m *ListPipelineRunRequest) XXX_Size() int {
	return m.Size()
}
func (m *ListPipelineRunRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPipelineRunRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPipelineRunRequest proto.InternalMessageInfo

func (m *ListPipelineRunRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ListPipelineRunRequest) GetListOptions() *metav1.ListOptions {
	if m != nil {
		return m.ListOptions
	}
	return nil
}

func (m *ListPipelineRunRequest) GetListOptionsExt() *api.ListOptionsExt {
	if m != nil {
		return m.ListOptionsExt
	}
	return nil
}

type ListPipelineRunResponse struct {
	PipelineRunList *PipelineRunList `protobuf:"bytes,1,opt,name=pipeline_run_list,json=pipelineRunList,proto3" json:"pipelineRunList,omitempty"`
}

func (m *ListPipelineRunResponse) Reset()      { *m = ListPipelineRunResponse{} }
func (*ListPipelineRunResponse) ProtoMessage() {}
func (*ListPipelineRunResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a53f9b87794e3c8, []int{11}
}
func (m *ListPipelineRunResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListPipelineRunResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListPipelineRunResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListPipelineRunResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPipelineRunResponse.Merge(m, src)
}
func (m *ListPipelineRunResponse) XXX_Size() int {
	return m.Size()
}
func (m *ListPipelineRunResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPipelineRunResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPipelineRunResponse proto.InternalMessageInfo

func (m *ListPipelineRunResponse) GetPipelineRunList() *PipelineRunList {
	if m != nil {
		return m.PipelineRunList
	}
	return nil
}

func init() {
	proto.RegisterType((*CreatePipelineRunRequest)(nil), "michelangelo.api.v2.CreatePipelineRunRequest")
	proto.RegisterType((*CreatePipelineRunResponse)(nil), "michelangelo.api.v2.CreatePipelineRunResponse")
	proto.RegisterType((*GetPipelineRunRequest)(nil), "michelangelo.api.v2.GetPipelineRunRequest")
	proto.RegisterType((*GetPipelineRunResponse)(nil), "michelangelo.api.v2.GetPipelineRunResponse")
	proto.RegisterType((*UpdatePipelineRunRequest)(nil), "michelangelo.api.v2.UpdatePipelineRunRequest")
	proto.RegisterType((*UpdatePipelineRunResponse)(nil), "michelangelo.api.v2.UpdatePipelineRunResponse")
	proto.RegisterType((*DeletePipelineRunRequest)(nil), "michelangelo.api.v2.DeletePipelineRunRequest")
	proto.RegisterType((*DeletePipelineRunResponse)(nil), "michelangelo.api.v2.DeletePipelineRunResponse")
	proto.RegisterType((*DeletePipelineRunCollectionRequest)(nil), "michelangelo.api.v2.DeletePipelineRunCollectionRequest")
	proto.RegisterType((*DeletePipelineRunCollectionResponse)(nil), "michelangelo.api.v2.DeletePipelineRunCollectionResponse")
	proto.RegisterType((*ListPipelineRunRequest)(nil), "michelangelo.api.v2.ListPipelineRunRequest")
	proto.RegisterType((*ListPipelineRunResponse)(nil), "michelangelo.api.v2.ListPipelineRunResponse")
}

func init() {
	proto.RegisterFile("michelangelo/api/v2/pipeline_run_svc.proto", fileDescriptor_2a53f9b87794e3c8)
}

var fileDescriptor_2a53f9b87794e3c8 = []byte{
	// 693 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xcb, 0x6e, 0xd3, 0x4c,
	0x14, 0xce, 0xe4, 0xff, 0x41, 0xea, 0x49, 0x49, 0xc9, 0x20, 0x4a, 0x9a, 0x22, 0xab, 0x32, 0x17,
	0xa1, 0x02, 0x63, 0x9a, 0x56, 0xa2, 0x6b, 0x0a, 0xaa, 0x84, 0x90, 0x28, 0x06, 0x36, 0x95, 0x50,
	0x30, 0xce, 0x51, 0x6a, 0xc5, 0xb1, 0x07, 0x7b, 0x62, 0x95, 0x1d, 0x8f, 0xd0, 0x07, 0xe0, 0x01,
	0x78, 0x07, 0x5e, 0x80, 0x65, 0x97, 0x5d, 0xb0, 0xa0, 0xee, 0x86, 0x65, 0x17, 0x3c, 0x00, 0xf2,
	0xa5, 0xa9, 0x13, 0x8f, 0x5b, 0x17, 0x85, 0x55, 0x7c, 0x66, 0xce, 0xe5, 0xfb, 0x3e, 0x9f, 0x73,
	0x1c, 0x58, 0x1e, 0x58, 0xe6, 0x0e, 0xda, 0x86, 0xd3, 0x43, 0xdb, 0xd5, 0x0c, 0x6e, 0x69, 0x41,
	0x5b, 0xe3, 0x16, 0x47, 0xdb, 0x72, 0xb0, 0xe3, 0x0d, 0x9d, 0x8e, 0x1f, 0x98, 0x8c, 0x7b, 0xae,
	0x70, 0xe9, 0xb5, 0xac, 0x2f, 0x33, 0xb8, 0xc5, 0x82, 0x76, 0x6b, 0xad, 0xbf, 0xee, 0x33, 0x2b,
	0x0e, 0x1d, 0x18, 0xe6, 0x8e, 0xe5, 0xa0, 0xf7, 0x49, 0xe3, 0xfd, 0x5e, 0x74, 0xe0, 0x6b, 0x03,
	0x14, 0x86, 0x16, 0xac, 0x68, 0x3d, 0x74, 0xd0, 0x33, 0x04, 0x76, 0x93, 0x54, 0xad, 0xc5, 0x5c,
	0x59, 0xdb, 0xf2, 0x45, 0x7a, 0x79, 0xf7, 0x3c, 0x4c, 0x89, 0x9f, 0xfa, 0x8d, 0x40, 0x73, 0xc3,
	0x43, 0x43, 0xe0, 0x56, 0x7a, 0xa9, 0x0f, 0x1d, 0x1d, 0x3f, 0x0e, 0xd1, 0x17, 0x74, 0x03, 0x66,
	0xb3, 0x21, 0x4d, 0xb2, 0x44, 0xee, 0xd5, 0xda, 0x4b, 0x4c, 0xc2, 0x81, 0x65, 0xc3, 0x6b, 0xfc,
	0xd4, 0xa0, 0xdb, 0x50, 0x37, 0xe3, 0x02, 0x1d, 0x97, 0x0b, 0xcb, 0x75, 0xfc, 0x66, 0x35, 0x4e,
	0xb3, 0xca, 0x12, 0xd6, 0x2c, 0xcb, 0x9a, 0xf1, 0x7e, 0x2f, 0x3a, 0xf0, 0x59, 0xc4, 0x9a, 0x05,
	0x2b, 0x2c, 0x01, 0xf7, 0x32, 0x09, 0xd5, 0xaf, 0x98, 0x59, 0x53, 0x7d, 0x0f, 0x0b, 0x12, 0xf0,
	0x3e, 0x77, 0x1d, 0x1f, 0xa7, 0x82, 0x5e, 0xfd, 0x42, 0xe0, 0xfa, 0x26, 0x0a, 0x89, 0x38, 0x14,
	0xfe, 0x77, 0x8c, 0x01, 0xc6, 0x69, 0x67, 0xf4, 0xf8, 0x99, 0xde, 0x84, 0x99, 0xe8, 0xd7, 0xe7,
	0x86, 0x89, 0x31, 0xcd, 0x19, 0xfd, 0xf4, 0x80, 0xbe, 0x82, 0x5a, 0x0f, 0xc5, 0x48, 0x86, 0xff,
	0x62, 0x3c, 0x8f, 0xca, 0xc9, 0xb0, 0x89, 0xe2, 0x44, 0x03, 0xe8, 0x8d, 0x9e, 0xd5, 0x77, 0x30,
	0x3f, 0x89, 0x6e, 0x9a, 0xec, 0xa3, 0xee, 0x78, 0xcb, 0xbb, 0xff, 0xb6, 0x3b, 0x86, 0x71, 0x81,
	0xbf, 0xeb, 0x8e, 0x04, 0xdc, 0xa8, 0x3b, 0x86, 0x59, 0x33, 0xea, 0x0e, 0x09, 0xf8, 0x69, 0xea,
	0xf3, 0x95, 0x40, 0xf3, 0x29, 0xda, 0x28, 0xd5, 0xe7, 0xe2, 0x0d, 0xb2, 0x0d, 0xf5, 0x6e, 0x9c,
	0x6d, 0xa2, 0x47, 0x4a, 0x8a, 0x91, 0x20, 0x19, 0x89, 0xd1, 0xcd, 0x9a, 0xea, 0x22, 0x2c, 0x48,
	0x90, 0x26, 0x62, 0xa8, 0xbf, 0x09, 0xa8, 0xb9, 0xdb, 0x0d, 0xd7, 0xb6, 0xd1, 0x8c, 0xa2, 0x4f,
	0x18, 0x8d, 0xa1, 0x27, 0xe7, 0xa3, 0xaf, 0x4e, 0x0b, 0x3d, 0x7d, 0x03, 0xb3, 0xd1, 0x72, 0x9b,
	0xd0, 0x65, 0xa5, 0x5c, 0xe6, 0x17, 0x96, 0x3f, 0x1a, 0x9e, 0x9a, 0x7d, 0x6a, 0xa8, 0x77, 0xe0,
	0xd6, 0x99, 0xac, 0x53, 0x75, 0x0e, 0x08, 0xcc, 0x47, 0x39, 0x24, 0xef, 0xf8, 0x6c, 0x45, 0x26,
	0x51, 0x57, 0xa7, 0x81, 0x9a, 0x3e, 0x87, 0xab, 0xd9, 0xac, 0x1d, 0xdc, 0x15, 0xa9, 0x1e, 0x92,
	0xee, 0xcd, 0x64, 0x79, 0xb6, 0x2b, 0xf4, 0xba, 0x3d, 0x66, 0xab, 0x7d, 0xb8, 0x91, 0x63, 0x96,
	0x0e, 0xc8, 0x16, 0x34, 0xc6, 0xbe, 0x61, 0x51, 0x64, 0x3a, 0x25, 0xb7, 0xcf, 0x9b, 0x92, 0x28,
	0xa7, 0x3e, 0xc7, 0xc7, 0x0f, 0xda, 0x3f, 0x2e, 0x01, 0xcd, 0x38, 0xbd, 0x46, 0x2f, 0xb0, 0x4c,
	0xa4, 0x1e, 0x34, 0x72, 0x4b, 0x9c, 0x3e, 0x94, 0x96, 0x28, 0xfa, 0x52, 0xb5, 0x58, 0x59, 0xf7,
	0x94, 0x9c, 0x05, 0xf5, 0xf1, 0xbd, 0x49, 0x97, 0xa5, 0x19, 0xa4, 0xab, 0xbf, 0x75, 0xbf, 0x94,
	0x6f, 0x5a, 0xca, 0x83, 0x46, 0x6e, 0x0b, 0x15, 0xd0, 0x2b, 0x5a, 0xb5, 0x05, 0xf4, 0x8a, 0x97,
	0x9b, 0x07, 0x8d, 0x5c, 0x63, 0x17, 0xd4, 0x2c, 0x5a, 0x5f, 0x05, 0x35, 0x0b, 0x77, 0x08, 0xdd,
	0x23, 0xb0, 0x78, 0xc6, 0x34, 0xd1, 0xc7, 0xe5, 0xf2, 0xe5, 0xb6, 0x4e, 0x6b, 0xfd, 0xe2, 0x81,
	0x29, 0x24, 0x1b, 0xe6, 0x26, 0xba, 0x9b, 0xca, 0x5f, 0x9d, 0x7c, 0xba, 0x5b, 0x0f, 0xca, 0x39,
	0x27, 0xd5, 0x9e, 0xac, 0xed, 0x1f, 0x2a, 0x95, 0x83, 0x43, 0xa5, 0x72, 0x7c, 0xa8, 0x90, 0xcf,
	0xa1, 0x42, 0xbe, 0x87, 0x0a, 0xd9, 0x0f, 0x15, 0xf2, 0x33, 0x54, 0xc8, 0xaf, 0x50, 0xa9, 0x1c,
	0x87, 0x0a, 0xd9, 0x3b, 0x52, 0x2a, 0xfb, 0x47, 0x4a, 0xe5, 0xe0, 0x48, 0xa9, 0x6c, 0x57, 0x83,
	0xf6, 0x87, 0xcb, 0xf1, 0xff, 0xb0, 0xd5, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x39, 0xbe, 0x63,
	0xa9, 0x45, 0x0a, 0x00, 0x00,
}

func (this *CreatePipelineRunRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&v2.CreatePipelineRunRequest{")
	if this.PipelineRun != nil {
		s = append(s, "PipelineRun: "+fmt.Sprintf("%#v", this.PipelineRun)+",\n")
	}
	if this.CreateOptions != nil {
		s = append(s, "CreateOptions: "+fmt.Sprintf("%#v", this.CreateOptions)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *CreatePipelineRunResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&v2.CreatePipelineRunResponse{")
	if this.PipelineRun != nil {
		s = append(s, "PipelineRun: "+fmt.Sprintf("%#v", this.PipelineRun)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GetPipelineRunRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&v2.GetPipelineRunRequest{")
	s = append(s, "Name: "+fmt.Sprintf("%#v", this.Name)+",\n")
	s = append(s, "Namespace: "+fmt.Sprintf("%#v", this.Namespace)+",\n")
	if this.GetOptions != nil {
		s = append(s, "GetOptions: "+fmt.Sprintf("%#v", this.GetOptions)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GetPipelineRunResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&v2.GetPipelineRunResponse{")
	if this.PipelineRun != nil {
		s = append(s, "PipelineRun: "+fmt.Sprintf("%#v", this.PipelineRun)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *UpdatePipelineRunRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&v2.UpdatePipelineRunRequest{")
	if this.PipelineRun != nil {
		s = append(s, "PipelineRun: "+fmt.Sprintf("%#v", this.PipelineRun)+",\n")
	}
	if this.UpdateOptions != nil {
		s = append(s, "UpdateOptions: "+fmt.Sprintf("%#v", this.UpdateOptions)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *UpdatePipelineRunResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&v2.UpdatePipelineRunResponse{")
	if this.PipelineRun != nil {
		s = append(s, "PipelineRun: "+fmt.Sprintf("%#v", this.PipelineRun)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *DeletePipelineRunRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&v2.DeletePipelineRunRequest{")
	s = append(s, "Name: "+fmt.Sprintf("%#v", this.Name)+",\n")
	s = append(s, "Namespace: "+fmt.Sprintf("%#v", this.Namespace)+",\n")
	if this.DeleteOptions != nil {
		s = append(s, "DeleteOptions: "+fmt.Sprintf("%#v", this.DeleteOptions)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *DeletePipelineRunResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 4)
	s = append(s, "&v2.DeletePipelineRunResponse{")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *DeletePipelineRunCollectionRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&v2.DeletePipelineRunCollectionRequest{")
	s = append(s, "Namespace: "+fmt.Sprintf("%#v", this.Namespace)+",\n")
	if this.DeleteOptions != nil {
		s = append(s, "DeleteOptions: "+fmt.Sprintf("%#v", this.DeleteOptions)+",\n")
	}
	if this.ListOptions != nil {
		s = append(s, "ListOptions: "+fmt.Sprintf("%#v", this.ListOptions)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *DeletePipelineRunCollectionResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 4)
	s = append(s, "&v2.DeletePipelineRunCollectionResponse{")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ListPipelineRunRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&v2.ListPipelineRunRequest{")
	s = append(s, "Namespace: "+fmt.Sprintf("%#v", this.Namespace)+",\n")
	if this.ListOptions != nil {
		s = append(s, "ListOptions: "+fmt.Sprintf("%#v", this.ListOptions)+",\n")
	}
	if this.ListOptionsExt != nil {
		s = append(s, "ListOptionsExt: "+fmt.Sprintf("%#v", this.ListOptionsExt)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ListPipelineRunResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&v2.ListPipelineRunResponse{")
	if this.PipelineRunList != nil {
		s = append(s, "PipelineRunList: "+fmt.Sprintf("%#v", this.PipelineRunList)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringPipelineRunSvc(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *CreatePipelineRunRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreatePipelineRunRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreatePipelineRunRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CreateOptions != nil {
		{
			size, err := m.CreateOptions.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPipelineRunSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.PipelineRun != nil {
		{
			size, err := m.PipelineRun.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPipelineRunSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CreatePipelineRunResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreatePipelineRunResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreatePipelineRunResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PipelineRun != nil {
		{
			size, err := m.PipelineRun.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPipelineRunSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetPipelineRunRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetPipelineRunRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetPipelineRunRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.GetOptions != nil {
		{
			size, err := m.GetOptions.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPipelineRunSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Namespace) > 0 {
		i -= len(m.Namespace)
		copy(dAtA[i:], m.Namespace)
		i = encodeVarintPipelineRunSvc(dAtA, i, uint64(len(m.Namespace)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintPipelineRunSvc(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetPipelineRunResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetPipelineRunResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetPipelineRunResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PipelineRun != nil {
		{
			size, err := m.PipelineRun.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPipelineRunSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *UpdatePipelineRunRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UpdatePipelineRunRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UpdatePipelineRunRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UpdateOptions != nil {
		{
			size, err := m.UpdateOptions.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPipelineRunSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.PipelineRun != nil {
		{
			size, err := m.PipelineRun.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPipelineRunSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *UpdatePipelineRunResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UpdatePipelineRunResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UpdatePipelineRunResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PipelineRun != nil {
		{
			size, err := m.PipelineRun.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPipelineRunSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DeletePipelineRunRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeletePipelineRunRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DeletePipelineRunRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DeleteOptions != nil {
		{
			size, err := m.DeleteOptions.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPipelineRunSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Namespace) > 0 {
		i -= len(m.Namespace)
		copy(dAtA[i:], m.Namespace)
		i = encodeVarintPipelineRunSvc(dAtA, i, uint64(len(m.Namespace)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintPipelineRunSvc(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DeletePipelineRunResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeletePipelineRunResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DeletePipelineRunResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *DeletePipelineRunCollectionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeletePipelineRunCollectionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DeletePipelineRunCollectionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ListOptions != nil {
		{
			size, err := m.ListOptions.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPipelineRunSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.DeleteOptions != nil {
		{
			size, err := m.DeleteOptions.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPipelineRunSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Namespace) > 0 {
		i -= len(m.Namespace)
		copy(dAtA[i:], m.Namespace)
		i = encodeVarintPipelineRunSvc(dAtA, i, uint64(len(m.Namespace)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DeletePipelineRunCollectionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeletePipelineRunCollectionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DeletePipelineRunCollectionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *ListPipelineRunRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListPipelineRunRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListPipelineRunRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ListOptionsExt != nil {
		{
			size, err := m.ListOptionsExt.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPipelineRunSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.ListOptions != nil {
		{
			size, err := m.ListOptions.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPipelineRunSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Namespace) > 0 {
		i -= len(m.Namespace)
		copy(dAtA[i:], m.Namespace)
		i = encodeVarintPipelineRunSvc(dAtA, i, uint64(len(m.Namespace)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ListPipelineRunResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListPipelineRunResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListPipelineRunResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PipelineRunList != nil {
		{
			size, err := m.PipelineRunList.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPipelineRunSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPipelineRunSvc(dAtA []byte, offset int, v uint64) int {
	offset -= sovPipelineRunSvc(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CreatePipelineRunRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PipelineRun != nil {
		l = m.PipelineRun.Size()
		n += 1 + l + sovPipelineRunSvc(uint64(l))
	}
	if m.CreateOptions != nil {
		l = m.CreateOptions.Size()
		n += 1 + l + sovPipelineRunSvc(uint64(l))
	}
	return n
}

func (m *CreatePipelineRunResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PipelineRun != nil {
		l = m.PipelineRun.Size()
		n += 1 + l + sovPipelineRunSvc(uint64(l))
	}
	return n
}

func (m *GetPipelineRunRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovPipelineRunSvc(uint64(l))
	}
	l = len(m.Namespace)
	if l > 0 {
		n += 1 + l + sovPipelineRunSvc(uint64(l))
	}
	if m.GetOptions != nil {
		l = m.GetOptions.Size()
		n += 1 + l + sovPipelineRunSvc(uint64(l))
	}
	return n
}

func (m *GetPipelineRunResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PipelineRun != nil {
		l = m.PipelineRun.Size()
		n += 1 + l + sovPipelineRunSvc(uint64(l))
	}
	return n
}

func (m *UpdatePipelineRunRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PipelineRun != nil {
		l = m.PipelineRun.Size()
		n += 1 + l + sovPipelineRunSvc(uint64(l))
	}
	if m.UpdateOptions != nil {
		l = m.UpdateOptions.Size()
		n += 1 + l + sovPipelineRunSvc(uint64(l))
	}
	return n
}

func (m *UpdatePipelineRunResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PipelineRun != nil {
		l = m.PipelineRun.Size()
		n += 1 + l + sovPipelineRunSvc(uint64(l))
	}
	return n
}

func (m *DeletePipelineRunRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovPipelineRunSvc(uint64(l))
	}
	l = len(m.Namespace)
	if l > 0 {
		n += 1 + l + sovPipelineRunSvc(uint64(l))
	}
	if m.DeleteOptions != nil {
		l = m.DeleteOptions.Size()
		n += 1 + l + sovPipelineRunSvc(uint64(l))
	}
	return n
}

func (m *DeletePipelineRunResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *DeletePipelineRunCollectionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Namespace)
	if l > 0 {
		n += 1 + l + sovPipelineRunSvc(uint64(l))
	}
	if m.DeleteOptions != nil {
		l = m.DeleteOptions.Size()
		n += 1 + l + sovPipelineRunSvc(uint64(l))
	}
	if m.ListOptions != nil {
		l = m.ListOptions.Size()
		n += 1 + l + sovPipelineRunSvc(uint64(l))
	}
	return n
}

func (m *DeletePipelineRunCollectionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *ListPipelineRunRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Namespace)
	if l > 0 {
		n += 1 + l + sovPipelineRunSvc(uint64(l))
	}
	if m.ListOptions != nil {
		l = m.ListOptions.Size()
		n += 1 + l + sovPipelineRunSvc(uint64(l))
	}
	if m.ListOptionsExt != nil {
		l = m.ListOptionsExt.Size()
		n += 1 + l + sovPipelineRunSvc(uint64(l))
	}
	return n
}

func (m *ListPipelineRunResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PipelineRunList != nil {
		l = m.PipelineRunList.Size()
		n += 1 + l + sovPipelineRunSvc(uint64(l))
	}
	return n
}

func sovPipelineRunSvc(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPipelineRunSvc(x uint64) (n int) {
	return sovPipelineRunSvc(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *CreatePipelineRunRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CreatePipelineRunRequest{`,
		`PipelineRun:` + strings.Replace(fmt.Sprintf("%v", this.PipelineRun), "PipelineRun", "PipelineRun", 1) + `,`,
		`CreateOptions:` + strings.Replace(fmt.Sprintf("%v", this.CreateOptions), "CreateOptions", "v1.CreateOptions", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *CreatePipelineRunResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CreatePipelineRunResponse{`,
		`PipelineRun:` + strings.Replace(fmt.Sprintf("%v", this.PipelineRun), "PipelineRun", "PipelineRun", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GetPipelineRunRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GetPipelineRunRequest{`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`Namespace:` + fmt.Sprintf("%v", this.Namespace) + `,`,
		`GetOptions:` + strings.Replace(fmt.Sprintf("%v", this.GetOptions), "GetOptions", "v1.GetOptions", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GetPipelineRunResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GetPipelineRunResponse{`,
		`PipelineRun:` + strings.Replace(fmt.Sprintf("%v", this.PipelineRun), "PipelineRun", "PipelineRun", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *UpdatePipelineRunRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&UpdatePipelineRunRequest{`,
		`PipelineRun:` + strings.Replace(fmt.Sprintf("%v", this.PipelineRun), "PipelineRun", "PipelineRun", 1) + `,`,
		`UpdateOptions:` + strings.Replace(fmt.Sprintf("%v", this.UpdateOptions), "UpdateOptions", "v1.UpdateOptions", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *UpdatePipelineRunResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&UpdatePipelineRunResponse{`,
		`PipelineRun:` + strings.Replace(fmt.Sprintf("%v", this.PipelineRun), "PipelineRun", "PipelineRun", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *DeletePipelineRunRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DeletePipelineRunRequest{`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`Namespace:` + fmt.Sprintf("%v", this.Namespace) + `,`,
		`DeleteOptions:` + strings.Replace(fmt.Sprintf("%v", this.DeleteOptions), "DeleteOptions", "v1.DeleteOptions", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *DeletePipelineRunResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DeletePipelineRunResponse{`,
		`}`,
	}, "")
	return s
}
func (this *DeletePipelineRunCollectionRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DeletePipelineRunCollectionRequest{`,
		`Namespace:` + fmt.Sprintf("%v", this.Namespace) + `,`,
		`DeleteOptions:` + strings.Replace(fmt.Sprintf("%v", this.DeleteOptions), "DeleteOptions", "v1.DeleteOptions", 1) + `,`,
		`ListOptions:` + strings.Replace(fmt.Sprintf("%v", this.ListOptions), "ListOptions", "v1.ListOptions", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *DeletePipelineRunCollectionResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DeletePipelineRunCollectionResponse{`,
		`}`,
	}, "")
	return s
}
func (this *ListPipelineRunRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ListPipelineRunRequest{`,
		`Namespace:` + fmt.Sprintf("%v", this.Namespace) + `,`,
		`ListOptions:` + strings.Replace(fmt.Sprintf("%v", this.ListOptions), "ListOptions", "v1.ListOptions", 1) + `,`,
		`ListOptionsExt:` + strings.Replace(fmt.Sprintf("%v", this.ListOptionsExt), "ListOptionsExt", "api.ListOptionsExt", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ListPipelineRunResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ListPipelineRunResponse{`,
		`PipelineRunList:` + strings.Replace(fmt.Sprintf("%v", this.PipelineRunList), "PipelineRunList", "PipelineRunList", 1) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringPipelineRunSvc(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *CreatePipelineRunRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPipelineRunSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreatePipelineRunRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreatePipelineRunRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PipelineRun", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPipelineRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PipelineRun == nil {
				m.PipelineRun = &PipelineRun{}
			}
			if err := m.PipelineRun.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreateOptions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPipelineRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CreateOptions == nil {
				m.CreateOptions = &metav1.CreateOptions{}
			}
			if err := m.CreateOptions.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPipelineRunSvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreatePipelineRunResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPipelineRunSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreatePipelineRunResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreatePipelineRunResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PipelineRun", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPipelineRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PipelineRun == nil {
				m.PipelineRun = &PipelineRun{}
			}
			if err := m.PipelineRun.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPipelineRunSvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetPipelineRunRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPipelineRunSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetPipelineRunRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetPipelineRunRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPipelineRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Namespace", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPipelineRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Namespace = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GetOptions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPipelineRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.GetOptions == nil {
				m.GetOptions = &metav1.GetOptions{}
			}
			if err := m.GetOptions.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPipelineRunSvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetPipelineRunResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPipelineRunSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetPipelineRunResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetPipelineRunResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PipelineRun", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPipelineRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PipelineRun == nil {
				m.PipelineRun = &PipelineRun{}
			}
			if err := m.PipelineRun.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPipelineRunSvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UpdatePipelineRunRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPipelineRunSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UpdatePipelineRunRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UpdatePipelineRunRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PipelineRun", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPipelineRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PipelineRun == nil {
				m.PipelineRun = &PipelineRun{}
			}
			if err := m.PipelineRun.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdateOptions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPipelineRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UpdateOptions == nil {
				m.UpdateOptions = &metav1.UpdateOptions{}
			}
			if err := m.UpdateOptions.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPipelineRunSvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UpdatePipelineRunResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPipelineRunSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UpdatePipelineRunResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UpdatePipelineRunResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PipelineRun", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPipelineRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PipelineRun == nil {
				m.PipelineRun = &PipelineRun{}
			}
			if err := m.PipelineRun.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPipelineRunSvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeletePipelineRunRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPipelineRunSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeletePipelineRunRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeletePipelineRunRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPipelineRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Namespace", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPipelineRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Namespace = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeleteOptions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPipelineRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DeleteOptions == nil {
				m.DeleteOptions = &metav1.DeleteOptions{}
			}
			if err := m.DeleteOptions.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPipelineRunSvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeletePipelineRunResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPipelineRunSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeletePipelineRunResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeletePipelineRunResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipPipelineRunSvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeletePipelineRunCollectionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPipelineRunSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeletePipelineRunCollectionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeletePipelineRunCollectionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Namespace", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPipelineRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Namespace = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeleteOptions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPipelineRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DeleteOptions == nil {
				m.DeleteOptions = &metav1.DeleteOptions{}
			}
			if err := m.DeleteOptions.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListOptions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPipelineRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ListOptions == nil {
				m.ListOptions = &metav1.ListOptions{}
			}
			if err := m.ListOptions.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPipelineRunSvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeletePipelineRunCollectionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPipelineRunSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeletePipelineRunCollectionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeletePipelineRunCollectionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipPipelineRunSvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListPipelineRunRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPipelineRunSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListPipelineRunRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListPipelineRunRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Namespace", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPipelineRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Namespace = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListOptions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPipelineRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ListOptions == nil {
				m.ListOptions = &metav1.ListOptions{}
			}
			if err := m.ListOptions.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListOptionsExt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPipelineRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ListOptionsExt == nil {
				m.ListOptionsExt = &api.ListOptionsExt{}
			}
			if err := m.ListOptionsExt.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPipelineRunSvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListPipelineRunResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPipelineRunSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListPipelineRunResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListPipelineRunResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PipelineRunList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPipelineRunSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PipelineRunList == nil {
				m.PipelineRunList = &PipelineRunList{}
			}
			if err := m.PipelineRunList.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPipelineRunSvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPipelineRunSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPipelineRunSvc(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPipelineRunSvc
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPipelineRunSvc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPipelineRunSvc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPipelineRunSvc
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPipelineRunSvc
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPipelineRunSvc
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPipelineRunSvc        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPipelineRunSvc          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPipelineRunSvc = fmt.Errorf("proto: unexpected end of group")
)
