// Code generated by protoc-gen-validation. DO NOT EDIT.

package v2

import (
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"reflect"
	"regexp"
	"strconv"
	"strings"

	"github.com/google/uuid"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = reflect.ValueOf
var _ = regexp.MatchString
var _ = uuid.Parse
var _ = mail.ParseAddress
var _ = strings.Contains
var _ = net.ParseIP
var _ = mail.ParseAddress
var _ = url.ParseRequestURI
var _ = codes.InvalidArgument
var _ = status.Error
var _ = strconv.Itoa

// createProjectRequestValidateExt is an extension hook for additional validation logic
var createProjectRequestValidateExt func(*CreateProjectRequest, string) error

func (this *CreateProjectRequest) Validate(prefix string) error {

	{
		v := this.GetProject()
		n := `project`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetCreateOptions()
		n := `create_options`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if createProjectRequestValidateExt != nil {
		if err := createProjectRequestValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterCreateProjectRequestValidateExt registers an extension validation function
func RegisterCreateProjectRequestValidateExt(f func(*CreateProjectRequest, string) error) {
	createProjectRequestValidateExt = f
}

// createProjectResponseValidateExt is an extension hook for additional validation logic
var createProjectResponseValidateExt func(*CreateProjectResponse, string) error

func (this *CreateProjectResponse) Validate(prefix string) error {

	{
		v := this.GetProject()
		n := `project`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if createProjectResponseValidateExt != nil {
		if err := createProjectResponseValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterCreateProjectResponseValidateExt registers an extension validation function
func RegisterCreateProjectResponseValidateExt(f func(*CreateProjectResponse, string) error) {
	createProjectResponseValidateExt = f
}

// getProjectRequestValidateExt is an extension hook for additional validation logic
var getProjectRequestValidateExt func(*GetProjectRequest, string) error

func (this *GetProjectRequest) Validate(prefix string) error {

	{
		v := this.GetGetOptions()
		n := `get_options`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if getProjectRequestValidateExt != nil {
		if err := getProjectRequestValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterGetProjectRequestValidateExt registers an extension validation function
func RegisterGetProjectRequestValidateExt(f func(*GetProjectRequest, string) error) {
	getProjectRequestValidateExt = f
}

// getProjectResponseValidateExt is an extension hook for additional validation logic
var getProjectResponseValidateExt func(*GetProjectResponse, string) error

func (this *GetProjectResponse) Validate(prefix string) error {

	{
		v := this.GetProject()
		n := `project`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if getProjectResponseValidateExt != nil {
		if err := getProjectResponseValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterGetProjectResponseValidateExt registers an extension validation function
func RegisterGetProjectResponseValidateExt(f func(*GetProjectResponse, string) error) {
	getProjectResponseValidateExt = f
}

// updateProjectRequestValidateExt is an extension hook for additional validation logic
var updateProjectRequestValidateExt func(*UpdateProjectRequest, string) error

func (this *UpdateProjectRequest) Validate(prefix string) error {

	{
		v := this.GetProject()
		n := `project`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetUpdateOptions()
		n := `update_options`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if updateProjectRequestValidateExt != nil {
		if err := updateProjectRequestValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterUpdateProjectRequestValidateExt registers an extension validation function
func RegisterUpdateProjectRequestValidateExt(f func(*UpdateProjectRequest, string) error) {
	updateProjectRequestValidateExt = f
}

// updateProjectResponseValidateExt is an extension hook for additional validation logic
var updateProjectResponseValidateExt func(*UpdateProjectResponse, string) error

func (this *UpdateProjectResponse) Validate(prefix string) error {

	{
		v := this.GetProject()
		n := `project`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if updateProjectResponseValidateExt != nil {
		if err := updateProjectResponseValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterUpdateProjectResponseValidateExt registers an extension validation function
func RegisterUpdateProjectResponseValidateExt(f func(*UpdateProjectResponse, string) error) {
	updateProjectResponseValidateExt = f
}

// deleteProjectRequestValidateExt is an extension hook for additional validation logic
var deleteProjectRequestValidateExt func(*DeleteProjectRequest, string) error

func (this *DeleteProjectRequest) Validate(prefix string) error {

	{
		v := this.GetDeleteOptions()
		n := `delete_options`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if deleteProjectRequestValidateExt != nil {
		if err := deleteProjectRequestValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterDeleteProjectRequestValidateExt registers an extension validation function
func RegisterDeleteProjectRequestValidateExt(f func(*DeleteProjectRequest, string) error) {
	deleteProjectRequestValidateExt = f
}

// deleteProjectResponseValidateExt is an extension hook for additional validation logic
var deleteProjectResponseValidateExt func(*DeleteProjectResponse, string) error

func (this *DeleteProjectResponse) Validate(prefix string) error {

	// Call extension validation if registered
	if deleteProjectResponseValidateExt != nil {
		if err := deleteProjectResponseValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterDeleteProjectResponseValidateExt registers an extension validation function
func RegisterDeleteProjectResponseValidateExt(f func(*DeleteProjectResponse, string) error) {
	deleteProjectResponseValidateExt = f
}

// deleteProjectCollectionRequestValidateExt is an extension hook for additional validation logic
var deleteProjectCollectionRequestValidateExt func(*DeleteProjectCollectionRequest, string) error

func (this *DeleteProjectCollectionRequest) Validate(prefix string) error {

	{
		v := this.GetDeleteOptions()
		n := `delete_options`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetListOptions()
		n := `list_options`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if deleteProjectCollectionRequestValidateExt != nil {
		if err := deleteProjectCollectionRequestValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterDeleteProjectCollectionRequestValidateExt registers an extension validation function
func RegisterDeleteProjectCollectionRequestValidateExt(f func(*DeleteProjectCollectionRequest, string) error) {
	deleteProjectCollectionRequestValidateExt = f
}

// deleteProjectCollectionResponseValidateExt is an extension hook for additional validation logic
var deleteProjectCollectionResponseValidateExt func(*DeleteProjectCollectionResponse, string) error

func (this *DeleteProjectCollectionResponse) Validate(prefix string) error {

	// Call extension validation if registered
	if deleteProjectCollectionResponseValidateExt != nil {
		if err := deleteProjectCollectionResponseValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterDeleteProjectCollectionResponseValidateExt registers an extension validation function
func RegisterDeleteProjectCollectionResponseValidateExt(f func(*DeleteProjectCollectionResponse, string) error) {
	deleteProjectCollectionResponseValidateExt = f
}

// listProjectRequestValidateExt is an extension hook for additional validation logic
var listProjectRequestValidateExt func(*ListProjectRequest, string) error

func (this *ListProjectRequest) Validate(prefix string) error {

	{
		v := this.GetListOptions()
		n := `list_options`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	{
		v := this.GetListOptionsExt()
		n := `list_options_ext`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if listProjectRequestValidateExt != nil {
		if err := listProjectRequestValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterListProjectRequestValidateExt registers an extension validation function
func RegisterListProjectRequestValidateExt(f func(*ListProjectRequest, string) error) {
	listProjectRequestValidateExt = f
}

// listProjectResponseValidateExt is an extension hook for additional validation logic
var listProjectResponseValidateExt func(*ListProjectResponse, string) error

func (this *ListProjectResponse) Validate(prefix string) error {

	{
		v := this.GetProjectList()
		n := `project_list`
		var i interface{}
		if reflect.ValueOf(v).Kind() == reflect.Ptr {
			i = reflect.ValueOf(v).Interface()
			if reflect.ValueOf(v).IsNil() {
				i = nil
			}
		} else {
			i = reflect.ValueOf(&v).Interface()
		}
		validate, hasValidate := i.(interface{ Validate(string) error })
		if hasValidate {
			if err := validate.Validate(prefix + n + "."); err != nil {
				return err
			}
		}
	}
	// Call extension validation if registered
	if listProjectResponseValidateExt != nil {
		if err := listProjectResponseValidateExt(this, prefix); err != nil {
			return err
		}
	}
	return nil
}

// RegisterListProjectResponseValidateExt registers an extension validation function
func RegisterListProjectResponseValidateExt(f func(*ListProjectResponse, string) error) {
	listProjectResponseValidateExt = f
}
