// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: michelangelo/api/v2/revision_svc.proto

package v2

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	api "github.com/michelangelo-ai/michelangelo/proto-go/api"
	io "io"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CreateRevisionRequest struct {
	Revision      *Revision             `protobuf:"bytes,1,opt,name=revision,proto3" json:"revision,omitempty"`
	CreateOptions *metav1.CreateOptions `protobuf:"bytes,2,opt,name=create_options,json=createOptions,proto3" json:"createOptions,omitempty"`
}

func (m *CreateRevisionRequest) Reset()      { *m = CreateRevisionRequest{} }
func (*CreateRevisionRequest) ProtoMessage() {}
func (*CreateRevisionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_188c9015a47059fe, []int{0}
}
func (m *CreateRevisionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateRevisionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateRevisionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreateRevisionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRevisionRequest.Merge(m, src)
}
func (m *CreateRevisionRequest) XXX_Size() int {
	return m.Size()
}
func (m *CreateRevisionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRevisionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRevisionRequest proto.InternalMessageInfo

func (m *CreateRevisionRequest) GetRevision() *Revision {
	if m != nil {
		return m.Revision
	}
	return nil
}

func (m *CreateRevisionRequest) GetCreateOptions() *metav1.CreateOptions {
	if m != nil {
		return m.CreateOptions
	}
	return nil
}

type CreateRevisionResponse struct {
	Revision *Revision `protobuf:"bytes,1,opt,name=revision,proto3" json:"revision,omitempty"`
}

func (m *CreateRevisionResponse) Reset()      { *m = CreateRevisionResponse{} }
func (*CreateRevisionResponse) ProtoMessage() {}
func (*CreateRevisionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_188c9015a47059fe, []int{1}
}
func (m *CreateRevisionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateRevisionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateRevisionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreateRevisionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRevisionResponse.Merge(m, src)
}
func (m *CreateRevisionResponse) XXX_Size() int {
	return m.Size()
}
func (m *CreateRevisionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRevisionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRevisionResponse proto.InternalMessageInfo

func (m *CreateRevisionResponse) GetRevision() *Revision {
	if m != nil {
		return m.Revision
	}
	return nil
}

type GetRevisionRequest struct {
	Name       string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace  string             `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	GetOptions *metav1.GetOptions `protobuf:"bytes,3,opt,name=get_options,json=getOptions,proto3" json:"getOptions,omitempty"`
}

func (m *GetRevisionRequest) Reset()      { *m = GetRevisionRequest{} }
func (*GetRevisionRequest) ProtoMessage() {}
func (*GetRevisionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_188c9015a47059fe, []int{2}
}
func (m *GetRevisionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetRevisionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetRevisionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetRevisionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRevisionRequest.Merge(m, src)
}
func (m *GetRevisionRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetRevisionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRevisionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRevisionRequest proto.InternalMessageInfo

func (m *GetRevisionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetRevisionRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *GetRevisionRequest) GetGetOptions() *metav1.GetOptions {
	if m != nil {
		return m.GetOptions
	}
	return nil
}

type GetRevisionResponse struct {
	Revision *Revision `protobuf:"bytes,1,opt,name=revision,proto3" json:"revision,omitempty"`
}

func (m *GetRevisionResponse) Reset()      { *m = GetRevisionResponse{} }
func (*GetRevisionResponse) ProtoMessage() {}
func (*GetRevisionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_188c9015a47059fe, []int{3}
}
func (m *GetRevisionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetRevisionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetRevisionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetRevisionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRevisionResponse.Merge(m, src)
}
func (m *GetRevisionResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetRevisionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRevisionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRevisionResponse proto.InternalMessageInfo

func (m *GetRevisionResponse) GetRevision() *Revision {
	if m != nil {
		return m.Revision
	}
	return nil
}

type UpdateRevisionRequest struct {
	Revision      *Revision             `protobuf:"bytes,1,opt,name=revision,proto3" json:"revision,omitempty"`
	UpdateOptions *metav1.UpdateOptions `protobuf:"bytes,2,opt,name=update_options,json=updateOptions,proto3" json:"updateOptions,omitempty"`
}

func (m *UpdateRevisionRequest) Reset()      { *m = UpdateRevisionRequest{} }
func (*UpdateRevisionRequest) ProtoMessage() {}
func (*UpdateRevisionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_188c9015a47059fe, []int{4}
}
func (m *UpdateRevisionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UpdateRevisionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UpdateRevisionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UpdateRevisionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRevisionRequest.Merge(m, src)
}
func (m *UpdateRevisionRequest) XXX_Size() int {
	return m.Size()
}
func (m *UpdateRevisionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRevisionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRevisionRequest proto.InternalMessageInfo

func (m *UpdateRevisionRequest) GetRevision() *Revision {
	if m != nil {
		return m.Revision
	}
	return nil
}

func (m *UpdateRevisionRequest) GetUpdateOptions() *metav1.UpdateOptions {
	if m != nil {
		return m.UpdateOptions
	}
	return nil
}

type UpdateRevisionResponse struct {
	Revision *Revision `protobuf:"bytes,1,opt,name=revision,proto3" json:"revision,omitempty"`
}

func (m *UpdateRevisionResponse) Reset()      { *m = UpdateRevisionResponse{} }
func (*UpdateRevisionResponse) ProtoMessage() {}
func (*UpdateRevisionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_188c9015a47059fe, []int{5}
}
func (m *UpdateRevisionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UpdateRevisionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UpdateRevisionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UpdateRevisionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRevisionResponse.Merge(m, src)
}
func (m *UpdateRevisionResponse) XXX_Size() int {
	return m.Size()
}
func (m *UpdateRevisionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRevisionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRevisionResponse proto.InternalMessageInfo

func (m *UpdateRevisionResponse) GetRevision() *Revision {
	if m != nil {
		return m.Revision
	}
	return nil
}

type DeleteRevisionRequest struct {
	Name          string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	DeleteOptions *metav1.DeleteOptions `protobuf:"bytes,3,opt,name=delete_options,json=deleteOptions,proto3" json:"deleteOptions,omitempty"`
}

func (m *DeleteRevisionRequest) Reset()      { *m = DeleteRevisionRequest{} }
func (*DeleteRevisionRequest) ProtoMessage() {}
func (*DeleteRevisionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_188c9015a47059fe, []int{6}
}
func (m *DeleteRevisionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DeleteRevisionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DeleteRevisionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DeleteRevisionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRevisionRequest.Merge(m, src)
}
func (m *DeleteRevisionRequest) XXX_Size() int {
	return m.Size()
}
func (m *DeleteRevisionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRevisionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRevisionRequest proto.InternalMessageInfo

func (m *DeleteRevisionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeleteRevisionRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *DeleteRevisionRequest) GetDeleteOptions() *metav1.DeleteOptions {
	if m != nil {
		return m.DeleteOptions
	}
	return nil
}

type DeleteRevisionResponse struct {
}

func (m *DeleteRevisionResponse) Reset()      { *m = DeleteRevisionResponse{} }
func (*DeleteRevisionResponse) ProtoMessage() {}
func (*DeleteRevisionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_188c9015a47059fe, []int{7}
}
func (m *DeleteRevisionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DeleteRevisionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DeleteRevisionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DeleteRevisionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRevisionResponse.Merge(m, src)
}
func (m *DeleteRevisionResponse) XXX_Size() int {
	return m.Size()
}
func (m *DeleteRevisionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRevisionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRevisionResponse proto.InternalMessageInfo

type DeleteRevisionCollectionRequest struct {
	Namespace     string                `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	DeleteOptions *metav1.DeleteOptions `protobuf:"bytes,2,opt,name=delete_options,json=deleteOptions,proto3" json:"deleteOptions,omitempty"`
	ListOptions   *metav1.ListOptions   `protobuf:"bytes,3,opt,name=list_options,json=listOptions,proto3" json:"listOptions,omitempty"`
}

func (m *DeleteRevisionCollectionRequest) Reset()      { *m = DeleteRevisionCollectionRequest{} }
func (*DeleteRevisionCollectionRequest) ProtoMessage() {}
func (*DeleteRevisionCollectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_188c9015a47059fe, []int{8}
}
func (m *DeleteRevisionCollectionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DeleteRevisionCollectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DeleteRevisionCollectionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DeleteRevisionCollectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRevisionCollectionRequest.Merge(m, src)
}
func (m *DeleteRevisionCollectionRequest) XXX_Size() int {
	return m.Size()
}
func (m *DeleteRevisionCollectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRevisionCollectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRevisionCollectionRequest proto.InternalMessageInfo

func (m *DeleteRevisionCollectionRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *DeleteRevisionCollectionRequest) GetDeleteOptions() *metav1.DeleteOptions {
	if m != nil {
		return m.DeleteOptions
	}
	return nil
}

func (m *DeleteRevisionCollectionRequest) GetListOptions() *metav1.ListOptions {
	if m != nil {
		return m.ListOptions
	}
	return nil
}

type DeleteRevisionCollectionResponse struct {
}

func (m *DeleteRevisionCollectionResponse) Reset()      { *m = DeleteRevisionCollectionResponse{} }
func (*DeleteRevisionCollectionResponse) ProtoMessage() {}
func (*DeleteRevisionCollectionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_188c9015a47059fe, []int{9}
}
func (m *DeleteRevisionCollectionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DeleteRevisionCollectionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DeleteRevisionCollectionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DeleteRevisionCollectionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRevisionCollectionResponse.Merge(m, src)
}
func (m *DeleteRevisionCollectionResponse) XXX_Size() int {
	return m.Size()
}
func (m *DeleteRevisionCollectionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRevisionCollectionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRevisionCollectionResponse proto.InternalMessageInfo

type ListRevisionRequest struct {
	Namespace      string              `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ListOptions    *metav1.ListOptions `protobuf:"bytes,2,opt,name=list_options,json=listOptions,proto3" json:"listOptions,omitempty"`
	ListOptionsExt *api.ListOptionsExt `protobuf:"bytes,3,opt,name=list_options_ext,json=listOptionsExt,proto3" json:"listOptionsExt,omitempty"`
}

func (m *ListRevisionRequest) Reset()      { *m = ListRevisionRequest{} }
func (*ListRevisionRequest) ProtoMessage() {}
func (*ListRevisionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_188c9015a47059fe, []int{10}
}
func (m *ListRevisionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListRevisionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListRevisionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListRevisionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRevisionRequest.Merge(m, src)
}
func (m *ListRevisionRequest) XXX_Size() int {
	return m.Size()
}
func (m *ListRevisionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRevisionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRevisionRequest proto.InternalMessageInfo

func (m *ListRevisionRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ListRevisionRequest) GetListOptions() *metav1.ListOptions {
	if m != nil {
		return m.ListOptions
	}
	return nil
}

func (m *ListRevisionRequest) GetListOptionsExt() *api.ListOptionsExt {
	if m != nil {
		return m.ListOptionsExt
	}
	return nil
}

type ListRevisionResponse struct {
	RevisionList *RevisionList `protobuf:"bytes,1,opt,name=revision_list,json=revisionList,proto3" json:"revisionList,omitempty"`
}

func (m *ListRevisionResponse) Reset()      { *m = ListRevisionResponse{} }
func (*ListRevisionResponse) ProtoMessage() {}
func (*ListRevisionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_188c9015a47059fe, []int{11}
}
func (m *ListRevisionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListRevisionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListRevisionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListRevisionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRevisionResponse.Merge(m, src)
}
func (m *ListRevisionResponse) XXX_Size() int {
	return m.Size()
}
func (m *ListRevisionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRevisionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRevisionResponse proto.InternalMessageInfo

func (m *ListRevisionResponse) GetRevisionList() *RevisionList {
	if m != nil {
		return m.RevisionList
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateRevisionRequest)(nil), "michelangelo.api.v2.CreateRevisionRequest")
	proto.RegisterType((*CreateRevisionResponse)(nil), "michelangelo.api.v2.CreateRevisionResponse")
	proto.RegisterType((*GetRevisionRequest)(nil), "michelangelo.api.v2.GetRevisionRequest")
	proto.RegisterType((*GetRevisionResponse)(nil), "michelangelo.api.v2.GetRevisionResponse")
	proto.RegisterType((*UpdateRevisionRequest)(nil), "michelangelo.api.v2.UpdateRevisionRequest")
	proto.RegisterType((*UpdateRevisionResponse)(nil), "michelangelo.api.v2.UpdateRevisionResponse")
	proto.RegisterType((*DeleteRevisionRequest)(nil), "michelangelo.api.v2.DeleteRevisionRequest")
	proto.RegisterType((*DeleteRevisionResponse)(nil), "michelangelo.api.v2.DeleteRevisionResponse")
	proto.RegisterType((*DeleteRevisionCollectionRequest)(nil), "michelangelo.api.v2.DeleteRevisionCollectionRequest")
	proto.RegisterType((*DeleteRevisionCollectionResponse)(nil), "michelangelo.api.v2.DeleteRevisionCollectionResponse")
	proto.RegisterType((*ListRevisionRequest)(nil), "michelangelo.api.v2.ListRevisionRequest")
	proto.RegisterType((*ListRevisionResponse)(nil), "michelangelo.api.v2.ListRevisionResponse")
}

func init() {
	proto.RegisterFile("michelangelo/api/v2/revision_svc.proto", fileDescriptor_188c9015a47059fe)
}

var fileDescriptor_188c9015a47059fe = []byte{
	// 678 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcf, 0x4f, 0xd4, 0x50,
	0x10, 0xde, 0xb7, 0xfe, 0x88, 0xcc, 0xc2, 0x6a, 0x1e, 0x42, 0x36, 0xab, 0x3e, 0xb1, 0x07, 0x45,
	0x4d, 0x5e, 0x65, 0xc1, 0x44, 0xaf, 0xa2, 0x92, 0x18, 0x13, 0x75, 0xd1, 0x0b, 0x07, 0xb1, 0x76,
	0x27, 0xcb, 0x0b, 0xdd, 0xb6, 0xf6, 0x3d, 0x1a, 0xbc, 0x79, 0xf3, 0xea, 0xd5, 0xb3, 0xf1, 0xea,
	0xdf, 0xe1, 0x91, 0x8b, 0x09, 0x47, 0x59, 0x2e, 0x1e, 0xf1, 0x3f, 0x30, 0xfd, 0x41, 0x69, 0xbb,
	0x2d, 0x14, 0xe1, 0xb4, 0x9d, 0xbe, 0x99, 0x6f, 0xbe, 0x6f, 0xe6, 0xcd, 0x74, 0xe1, 0xe6, 0x40,
	0x98, 0x6b, 0x68, 0x19, 0x76, 0x1f, 0x2d, 0x47, 0x37, 0x5c, 0xa1, 0xfb, 0x1d, 0xdd, 0x43, 0x5f,
	0x48, 0xe1, 0xd8, 0xab, 0xd2, 0x37, 0xb9, 0xeb, 0x39, 0xca, 0xa1, 0x93, 0x69, 0x3f, 0x6e, 0xb8,
	0x82, 0xfb, 0x9d, 0xf6, 0xc2, 0xfa, 0x03, 0xc9, 0x45, 0x18, 0x36, 0x30, 0xcc, 0x35, 0x61, 0xa3,
	0xf7, 0x51, 0x77, 0xd7, 0xfb, 0xc1, 0x0b, 0xa9, 0x0f, 0x50, 0x19, 0xba, 0x3f, 0xa7, 0xf7, 0xd1,
	0x46, 0xcf, 0x50, 0xd8, 0x8b, 0xa0, 0xda, 0x57, 0x46, 0x52, 0x5a, 0x42, 0xaa, 0xf8, 0x50, 0x3b,
	0x8c, 0x4f, 0xe4, 0xa3, 0xfd, 0x20, 0x30, 0xb5, 0xe8, 0xa1, 0xa1, 0xb0, 0x1b, 0x1f, 0x74, 0xf1,
	0xc3, 0x06, 0x4a, 0x45, 0x1f, 0xc2, 0x85, 0x7d, 0xdf, 0x16, 0x99, 0x21, 0xb3, 0x8d, 0xce, 0x35,
	0x5e, 0x40, 0x9c, 0x27, 0x71, 0x89, 0x3b, 0x5d, 0x81, 0xa6, 0x19, 0x62, 0xae, 0x3a, 0xae, 0x12,
	0x8e, 0x2d, 0x5b, 0xf5, 0x10, 0x60, 0x9e, 0x47, 0x22, 0x79, 0x5a, 0x24, 0x77, 0xd7, 0xfb, 0xc1,
	0x0b, 0xc9, 0x03, 0x91, 0xdc, 0x9f, 0xe3, 0x11, 0x9f, 0x17, 0x51, 0x68, 0x77, 0xc2, 0x4c, 0x9b,
	0xda, 0x32, 0x4c, 0xe7, 0xf9, 0x4a, 0xd7, 0xb1, 0x25, 0x9e, 0x80, 0xb0, 0xf6, 0x95, 0x00, 0x5d,
	0x42, 0x95, 0x2f, 0x01, 0x85, 0xb3, 0xb6, 0x31, 0xc0, 0x10, 0x6d, 0xac, 0x1b, 0x3e, 0xd3, 0xab,
	0x30, 0x16, 0xfc, 0x4a, 0xd7, 0x30, 0x31, 0x94, 0x35, 0xd6, 0x3d, 0x78, 0x41, 0x5f, 0x41, 0xa3,
	0x8f, 0x2a, 0x91, 0x7d, 0x26, 0xa4, 0x71, 0xaf, 0x9a, 0xec, 0x25, 0x54, 0xfb, 0x9a, 0xa1, 0x9f,
	0x3c, 0x6b, 0x2f, 0x61, 0x32, 0x43, 0xed, 0xe4, 0x6a, 0x83, 0x9e, 0xbf, 0x71, 0x7b, 0xa7, 0xde,
	0xf3, 0x8d, 0x10, 0xf3, 0xff, 0x7a, 0x1e, 0xf1, 0x49, 0x7a, 0xbe, 0x91, 0x36, 0x83, 0x9e, 0xe7,
	0xf9, 0x9e, 0xbc, 0x0a, 0xdf, 0x09, 0x4c, 0x3d, 0x46, 0x0b, 0x47, 0xab, 0x70, 0xfc, 0xb6, 0xaf,
	0x40, 0xb3, 0x17, 0x42, 0xe5, 0x3a, 0x5f, 0x51, 0x7c, 0x44, 0x23, 0x11, 0xdf, 0x4b, 0x9b, 0x5a,
	0x0b, 0xa6, 0xf3, 0x34, 0x23, 0xf1, 0xda, 0x5f, 0x02, 0xd7, 0xb3, 0x47, 0x8b, 0x8e, 0x65, 0xa1,
	0xa9, 0x52, 0x5a, 0x32, 0xbc, 0xc9, 0xd1, 0xbc, 0xeb, 0xa7, 0xc5, 0x9b, 0xbe, 0x86, 0xf1, 0x60,
	0x17, 0xe5, 0x2a, 0x32, 0x57, 0x0d, 0xf9, 0xb9, 0x90, 0xc9, 0x30, 0x34, 0xac, 0x03, 0x43, 0xd3,
	0x60, 0xa6, 0x5c, 0x72, 0x5c, 0x97, 0x5f, 0x04, 0x26, 0x03, 0x80, 0x7c, 0x5f, 0x0f, 0xaf, 0x45,
	0x9e, 0x6f, 0xfd, 0x34, 0xf8, 0xd2, 0x67, 0x70, 0x29, 0x8d, 0xba, 0x8a, 0x9b, 0x2a, 0xae, 0xc4,
	0xcc, 0xe8, 0x45, 0x4d, 0xa1, 0x3c, 0xd9, 0x54, 0xdd, 0xa6, 0x95, 0xb1, 0xb5, 0xb7, 0x70, 0x39,
	0x2b, 0x2b, 0x1e, 0x82, 0xa7, 0x30, 0x91, 0x7c, 0x65, 0x82, 0x90, 0x78, 0x12, 0x6e, 0x1c, 0x3a,
	0x09, 0x21, 0xd2, 0xb8, 0x97, 0xb2, 0x3a, 0xdf, 0xce, 0xc1, 0xc5, 0xfd, 0xe3, 0x65, 0xf4, 0x7c,
	0x61, 0x22, 0x15, 0xd0, 0xcc, 0xae, 0x5b, 0x7a, 0xa7, 0x10, 0xb6, 0xf0, 0x1b, 0xd2, 0xbe, 0x5b,
	0xc9, 0x37, 0x96, 0xf1, 0x0e, 0x1a, 0xa9, 0x45, 0x47, 0x6f, 0x15, 0xc6, 0x8e, 0x6e, 0xe9, 0xf6,
	0xec, 0xd1, 0x8e, 0x71, 0x06, 0x01, 0xcd, 0xec, 0x1e, 0x29, 0x11, 0x53, 0xb8, 0x1c, 0x4b, 0xc4,
	0x94, 0x2c, 0x26, 0x01, 0xcd, 0xec, 0x3d, 0x2d, 0x49, 0x55, 0xb8, 0x81, 0x4a, 0x52, 0x15, 0xaf,
	0x01, 0xfa, 0x99, 0x40, 0xab, 0x6c, 0x26, 0xe8, 0x42, 0x05, 0xa4, 0x91, 0xad, 0xd1, 0xbe, 0x7f,
	0xcc, 0xa8, 0x98, 0x89, 0x09, 0xe3, 0xe9, 0x0b, 0x4a, 0x8b, 0x3b, 0x53, 0x30, 0x9a, 0xed, 0xdb,
	0x15, 0x3c, 0xa3, 0x24, 0x8f, 0x16, 0xb6, 0x76, 0x58, 0x6d, 0x7b, 0x87, 0xd5, 0xf6, 0x76, 0x18,
	0xf9, 0x34, 0x64, 0xe4, 0xe7, 0x90, 0x91, 0xad, 0x21, 0x23, 0xbf, 0x87, 0x8c, 0xfc, 0x19, 0xb2,
	0xda, 0xde, 0x90, 0x91, 0x2f, 0xbb, 0xac, 0xb6, 0xb5, 0xcb, 0x6a, 0xdb, 0xbb, 0xac, 0xb6, 0x52,
	0xf7, 0x3b, 0xef, 0xcf, 0x87, 0x7f, 0x77, 0xe6, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x1d, 0x6a,
	0x19, 0x27, 0xa4, 0x09, 0x00, 0x00,
}

func (this *CreateRevisionRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&v2.CreateRevisionRequest{")
	if this.Revision != nil {
		s = append(s, "Revision: "+fmt.Sprintf("%#v", this.Revision)+",\n")
	}
	if this.CreateOptions != nil {
		s = append(s, "CreateOptions: "+fmt.Sprintf("%#v", this.CreateOptions)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *CreateRevisionResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&v2.CreateRevisionResponse{")
	if this.Revision != nil {
		s = append(s, "Revision: "+fmt.Sprintf("%#v", this.Revision)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GetRevisionRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&v2.GetRevisionRequest{")
	s = append(s, "Name: "+fmt.Sprintf("%#v", this.Name)+",\n")
	s = append(s, "Namespace: "+fmt.Sprintf("%#v", this.Namespace)+",\n")
	if this.GetOptions != nil {
		s = append(s, "GetOptions: "+fmt.Sprintf("%#v", this.GetOptions)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GetRevisionResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&v2.GetRevisionResponse{")
	if this.Revision != nil {
		s = append(s, "Revision: "+fmt.Sprintf("%#v", this.Revision)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *UpdateRevisionRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&v2.UpdateRevisionRequest{")
	if this.Revision != nil {
		s = append(s, "Revision: "+fmt.Sprintf("%#v", this.Revision)+",\n")
	}
	if this.UpdateOptions != nil {
		s = append(s, "UpdateOptions: "+fmt.Sprintf("%#v", this.UpdateOptions)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *UpdateRevisionResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&v2.UpdateRevisionResponse{")
	if this.Revision != nil {
		s = append(s, "Revision: "+fmt.Sprintf("%#v", this.Revision)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *DeleteRevisionRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&v2.DeleteRevisionRequest{")
	s = append(s, "Name: "+fmt.Sprintf("%#v", this.Name)+",\n")
	s = append(s, "Namespace: "+fmt.Sprintf("%#v", this.Namespace)+",\n")
	if this.DeleteOptions != nil {
		s = append(s, "DeleteOptions: "+fmt.Sprintf("%#v", this.DeleteOptions)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *DeleteRevisionResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 4)
	s = append(s, "&v2.DeleteRevisionResponse{")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *DeleteRevisionCollectionRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&v2.DeleteRevisionCollectionRequest{")
	s = append(s, "Namespace: "+fmt.Sprintf("%#v", this.Namespace)+",\n")
	if this.DeleteOptions != nil {
		s = append(s, "DeleteOptions: "+fmt.Sprintf("%#v", this.DeleteOptions)+",\n")
	}
	if this.ListOptions != nil {
		s = append(s, "ListOptions: "+fmt.Sprintf("%#v", this.ListOptions)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *DeleteRevisionCollectionResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 4)
	s = append(s, "&v2.DeleteRevisionCollectionResponse{")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ListRevisionRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&v2.ListRevisionRequest{")
	s = append(s, "Namespace: "+fmt.Sprintf("%#v", this.Namespace)+",\n")
	if this.ListOptions != nil {
		s = append(s, "ListOptions: "+fmt.Sprintf("%#v", this.ListOptions)+",\n")
	}
	if this.ListOptionsExt != nil {
		s = append(s, "ListOptionsExt: "+fmt.Sprintf("%#v", this.ListOptionsExt)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ListRevisionResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&v2.ListRevisionResponse{")
	if this.RevisionList != nil {
		s = append(s, "RevisionList: "+fmt.Sprintf("%#v", this.RevisionList)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringRevisionSvc(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *CreateRevisionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateRevisionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreateRevisionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CreateOptions != nil {
		{
			size, err := m.CreateOptions.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRevisionSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Revision != nil {
		{
			size, err := m.Revision.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRevisionSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CreateRevisionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateRevisionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreateRevisionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Revision != nil {
		{
			size, err := m.Revision.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRevisionSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetRevisionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetRevisionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetRevisionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.GetOptions != nil {
		{
			size, err := m.GetOptions.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRevisionSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Namespace) > 0 {
		i -= len(m.Namespace)
		copy(dAtA[i:], m.Namespace)
		i = encodeVarintRevisionSvc(dAtA, i, uint64(len(m.Namespace)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintRevisionSvc(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetRevisionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetRevisionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetRevisionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Revision != nil {
		{
			size, err := m.Revision.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRevisionSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *UpdateRevisionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UpdateRevisionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UpdateRevisionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UpdateOptions != nil {
		{
			size, err := m.UpdateOptions.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRevisionSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Revision != nil {
		{
			size, err := m.Revision.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRevisionSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *UpdateRevisionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UpdateRevisionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UpdateRevisionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Revision != nil {
		{
			size, err := m.Revision.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRevisionSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DeleteRevisionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeleteRevisionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DeleteRevisionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DeleteOptions != nil {
		{
			size, err := m.DeleteOptions.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRevisionSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Namespace) > 0 {
		i -= len(m.Namespace)
		copy(dAtA[i:], m.Namespace)
		i = encodeVarintRevisionSvc(dAtA, i, uint64(len(m.Namespace)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintRevisionSvc(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DeleteRevisionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeleteRevisionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DeleteRevisionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *DeleteRevisionCollectionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeleteRevisionCollectionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DeleteRevisionCollectionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ListOptions != nil {
		{
			size, err := m.ListOptions.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRevisionSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.DeleteOptions != nil {
		{
			size, err := m.DeleteOptions.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRevisionSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Namespace) > 0 {
		i -= len(m.Namespace)
		copy(dAtA[i:], m.Namespace)
		i = encodeVarintRevisionSvc(dAtA, i, uint64(len(m.Namespace)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DeleteRevisionCollectionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeleteRevisionCollectionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DeleteRevisionCollectionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *ListRevisionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListRevisionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListRevisionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ListOptionsExt != nil {
		{
			size, err := m.ListOptionsExt.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRevisionSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.ListOptions != nil {
		{
			size, err := m.ListOptions.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRevisionSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Namespace) > 0 {
		i -= len(m.Namespace)
		copy(dAtA[i:], m.Namespace)
		i = encodeVarintRevisionSvc(dAtA, i, uint64(len(m.Namespace)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ListRevisionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListRevisionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListRevisionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RevisionList != nil {
		{
			size, err := m.RevisionList.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRevisionSvc(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintRevisionSvc(dAtA []byte, offset int, v uint64) int {
	offset -= sovRevisionSvc(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CreateRevisionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Revision != nil {
		l = m.Revision.Size()
		n += 1 + l + sovRevisionSvc(uint64(l))
	}
	if m.CreateOptions != nil {
		l = m.CreateOptions.Size()
		n += 1 + l + sovRevisionSvc(uint64(l))
	}
	return n
}

func (m *CreateRevisionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Revision != nil {
		l = m.Revision.Size()
		n += 1 + l + sovRevisionSvc(uint64(l))
	}
	return n
}

func (m *GetRevisionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovRevisionSvc(uint64(l))
	}
	l = len(m.Namespace)
	if l > 0 {
		n += 1 + l + sovRevisionSvc(uint64(l))
	}
	if m.GetOptions != nil {
		l = m.GetOptions.Size()
		n += 1 + l + sovRevisionSvc(uint64(l))
	}
	return n
}

func (m *GetRevisionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Revision != nil {
		l = m.Revision.Size()
		n += 1 + l + sovRevisionSvc(uint64(l))
	}
	return n
}

func (m *UpdateRevisionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Revision != nil {
		l = m.Revision.Size()
		n += 1 + l + sovRevisionSvc(uint64(l))
	}
	if m.UpdateOptions != nil {
		l = m.UpdateOptions.Size()
		n += 1 + l + sovRevisionSvc(uint64(l))
	}
	return n
}

func (m *UpdateRevisionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Revision != nil {
		l = m.Revision.Size()
		n += 1 + l + sovRevisionSvc(uint64(l))
	}
	return n
}

func (m *DeleteRevisionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovRevisionSvc(uint64(l))
	}
	l = len(m.Namespace)
	if l > 0 {
		n += 1 + l + sovRevisionSvc(uint64(l))
	}
	if m.DeleteOptions != nil {
		l = m.DeleteOptions.Size()
		n += 1 + l + sovRevisionSvc(uint64(l))
	}
	return n
}

func (m *DeleteRevisionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *DeleteRevisionCollectionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Namespace)
	if l > 0 {
		n += 1 + l + sovRevisionSvc(uint64(l))
	}
	if m.DeleteOptions != nil {
		l = m.DeleteOptions.Size()
		n += 1 + l + sovRevisionSvc(uint64(l))
	}
	if m.ListOptions != nil {
		l = m.ListOptions.Size()
		n += 1 + l + sovRevisionSvc(uint64(l))
	}
	return n
}

func (m *DeleteRevisionCollectionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *ListRevisionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Namespace)
	if l > 0 {
		n += 1 + l + sovRevisionSvc(uint64(l))
	}
	if m.ListOptions != nil {
		l = m.ListOptions.Size()
		n += 1 + l + sovRevisionSvc(uint64(l))
	}
	if m.ListOptionsExt != nil {
		l = m.ListOptionsExt.Size()
		n += 1 + l + sovRevisionSvc(uint64(l))
	}
	return n
}

func (m *ListRevisionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RevisionList != nil {
		l = m.RevisionList.Size()
		n += 1 + l + sovRevisionSvc(uint64(l))
	}
	return n
}

func sovRevisionSvc(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozRevisionSvc(x uint64) (n int) {
	return sovRevisionSvc(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *CreateRevisionRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CreateRevisionRequest{`,
		`Revision:` + strings.Replace(fmt.Sprintf("%v", this.Revision), "Revision", "Revision", 1) + `,`,
		`CreateOptions:` + strings.Replace(fmt.Sprintf("%v", this.CreateOptions), "CreateOptions", "v1.CreateOptions", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *CreateRevisionResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CreateRevisionResponse{`,
		`Revision:` + strings.Replace(fmt.Sprintf("%v", this.Revision), "Revision", "Revision", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GetRevisionRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GetRevisionRequest{`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`Namespace:` + fmt.Sprintf("%v", this.Namespace) + `,`,
		`GetOptions:` + strings.Replace(fmt.Sprintf("%v", this.GetOptions), "GetOptions", "v1.GetOptions", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GetRevisionResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GetRevisionResponse{`,
		`Revision:` + strings.Replace(fmt.Sprintf("%v", this.Revision), "Revision", "Revision", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *UpdateRevisionRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&UpdateRevisionRequest{`,
		`Revision:` + strings.Replace(fmt.Sprintf("%v", this.Revision), "Revision", "Revision", 1) + `,`,
		`UpdateOptions:` + strings.Replace(fmt.Sprintf("%v", this.UpdateOptions), "UpdateOptions", "v1.UpdateOptions", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *UpdateRevisionResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&UpdateRevisionResponse{`,
		`Revision:` + strings.Replace(fmt.Sprintf("%v", this.Revision), "Revision", "Revision", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *DeleteRevisionRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DeleteRevisionRequest{`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`Namespace:` + fmt.Sprintf("%v", this.Namespace) + `,`,
		`DeleteOptions:` + strings.Replace(fmt.Sprintf("%v", this.DeleteOptions), "DeleteOptions", "v1.DeleteOptions", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *DeleteRevisionResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DeleteRevisionResponse{`,
		`}`,
	}, "")
	return s
}
func (this *DeleteRevisionCollectionRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DeleteRevisionCollectionRequest{`,
		`Namespace:` + fmt.Sprintf("%v", this.Namespace) + `,`,
		`DeleteOptions:` + strings.Replace(fmt.Sprintf("%v", this.DeleteOptions), "DeleteOptions", "v1.DeleteOptions", 1) + `,`,
		`ListOptions:` + strings.Replace(fmt.Sprintf("%v", this.ListOptions), "ListOptions", "v1.ListOptions", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *DeleteRevisionCollectionResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DeleteRevisionCollectionResponse{`,
		`}`,
	}, "")
	return s
}
func (this *ListRevisionRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ListRevisionRequest{`,
		`Namespace:` + fmt.Sprintf("%v", this.Namespace) + `,`,
		`ListOptions:` + strings.Replace(fmt.Sprintf("%v", this.ListOptions), "ListOptions", "v1.ListOptions", 1) + `,`,
		`ListOptionsExt:` + strings.Replace(fmt.Sprintf("%v", this.ListOptionsExt), "ListOptionsExt", "api.ListOptionsExt", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ListRevisionResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ListRevisionResponse{`,
		`RevisionList:` + strings.Replace(fmt.Sprintf("%v", this.RevisionList), "RevisionList", "RevisionList", 1) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringRevisionSvc(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *CreateRevisionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRevisionSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateRevisionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateRevisionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Revision", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRevisionSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Revision == nil {
				m.Revision = &Revision{}
			}
			if err := m.Revision.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreateOptions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRevisionSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CreateOptions == nil {
				m.CreateOptions = &metav1.CreateOptions{}
			}
			if err := m.CreateOptions.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRevisionSvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateRevisionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRevisionSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateRevisionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateRevisionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Revision", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRevisionSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Revision == nil {
				m.Revision = &Revision{}
			}
			if err := m.Revision.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRevisionSvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetRevisionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRevisionSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetRevisionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetRevisionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRevisionSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Namespace", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRevisionSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Namespace = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GetOptions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRevisionSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.GetOptions == nil {
				m.GetOptions = &metav1.GetOptions{}
			}
			if err := m.GetOptions.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRevisionSvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetRevisionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRevisionSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetRevisionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetRevisionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Revision", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRevisionSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Revision == nil {
				m.Revision = &Revision{}
			}
			if err := m.Revision.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRevisionSvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UpdateRevisionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRevisionSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UpdateRevisionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UpdateRevisionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Revision", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRevisionSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Revision == nil {
				m.Revision = &Revision{}
			}
			if err := m.Revision.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdateOptions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRevisionSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UpdateOptions == nil {
				m.UpdateOptions = &metav1.UpdateOptions{}
			}
			if err := m.UpdateOptions.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRevisionSvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UpdateRevisionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRevisionSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UpdateRevisionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UpdateRevisionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Revision", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRevisionSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Revision == nil {
				m.Revision = &Revision{}
			}
			if err := m.Revision.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRevisionSvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeleteRevisionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRevisionSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeleteRevisionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeleteRevisionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRevisionSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Namespace", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRevisionSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Namespace = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeleteOptions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRevisionSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DeleteOptions == nil {
				m.DeleteOptions = &metav1.DeleteOptions{}
			}
			if err := m.DeleteOptions.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRevisionSvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeleteRevisionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRevisionSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeleteRevisionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeleteRevisionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipRevisionSvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeleteRevisionCollectionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRevisionSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeleteRevisionCollectionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeleteRevisionCollectionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Namespace", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRevisionSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Namespace = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeleteOptions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRevisionSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DeleteOptions == nil {
				m.DeleteOptions = &metav1.DeleteOptions{}
			}
			if err := m.DeleteOptions.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListOptions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRevisionSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ListOptions == nil {
				m.ListOptions = &metav1.ListOptions{}
			}
			if err := m.ListOptions.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRevisionSvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeleteRevisionCollectionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRevisionSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeleteRevisionCollectionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeleteRevisionCollectionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipRevisionSvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListRevisionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRevisionSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListRevisionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListRevisionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Namespace", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRevisionSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Namespace = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListOptions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRevisionSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ListOptions == nil {
				m.ListOptions = &metav1.ListOptions{}
			}
			if err := m.ListOptions.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListOptionsExt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRevisionSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ListOptionsExt == nil {
				m.ListOptionsExt = &api.ListOptionsExt{}
			}
			if err := m.ListOptionsExt.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRevisionSvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListRevisionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRevisionSvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListRevisionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListRevisionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RevisionList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRevisionSvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RevisionList == nil {
				m.RevisionList = &RevisionList{}
			}
			if err := m.RevisionList.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRevisionSvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRevisionSvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRevisionSvc(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRevisionSvc
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRevisionSvc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRevisionSvc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthRevisionSvc
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupRevisionSvc
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthRevisionSvc
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthRevisionSvc        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRevisionSvc          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupRevisionSvc = fmt.Errorf("proto: unexpected end of group")
)
