// Code generated by protoc-gen-kubeyarpc. DO NOT EDIT.

package v2

import (
	"context"

	"go.uber.org/fx"

	apipb "github.com/michelangelo-ai/michelangelo/proto-go/api"
	"github.com/michelangelo-ai/michelangelo/go/api"
	authapi "github.com/michelangelo-ai/michelangelo/go/auth"
	"github.com/michelangelo-ai/michelangelo/go/logging"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"github.com/uber-go/tally"
)

type FxTriggerRunServiceHandlerParams struct {
	fx.In

	Handler      api.Handler
	MetricsScope tally.Scope
	Auth         authapi.Auth
	AuditLog     logging.AuditLog
}

var triggerRunApiHooks []TriggerRunAPIHook

// RegisterTriggerRunAPIHook registers a new TriggerRunAPIHook to be called by the TriggerRunServiceHandler.
func RegisterTriggerRunAPIHook(hook TriggerRunAPIHook) {
	triggerRunApiHooks = append(triggerRunApiHooks, hook)
}

// GetTriggerRunAPIHooks returns the list of registered TriggerRunAPIHooks.
func GetTriggerRunAPIHooks() []TriggerRunAPIHook {
	return triggerRunApiHooks
}

// ClearTriggerRunAPIHooks clears the registered TriggerRunAPIHooks.
func ClearTriggerRunAPIHooks() {
	triggerRunApiHooks = []TriggerRunAPIHook{}
}

func NewTriggerRunServiceHandler(params FxTriggerRunServiceHandlerParams) TriggerRunServiceYARPCServer {
	return &triggerRunServiceHandler{
		apiHandler:      params.Handler,
		MetricsScope:    params.MetricsScope.SubScope(logging.MichelangeloAPIScopeName),
		auth:            params.Auth,
		auditLogEmitter: params.AuditLog,
	}
}

type triggerRunServiceHandler struct {
	apiHandler      api.Handler
	MetricsScope    tally.Scope
	auth            authapi.Auth
	auditLogEmitter logging.AuditLog
}

// TriggerRunAPIHook allows API developers to hook the standard CRUD methods,
// before the request is sent to K8s API server, or before the response is returned to the client.
type TriggerRunAPIHook interface {
	// BeforeCreate is called before a CreateTriggerRunRequest is sent to the K8s API server.
	//
	// This method can be used to validate or modify the CreateTriggerRunRequest, before it's sent to the k8s API
	// server. If this method returns an error, the CreateTriggerRunRequest will not be sent to the K8s API server
	// and the error is returned to the gRPC client.
	//
	// API developer may use this method to store some fields of TriggerRun into another storage system, instead of
	// K8s / ETCD. In the modified CreateTriggerRunRequest, those fields may be set to nil or empty or the key / uri
	// of the actual data. If eventually K8s fails to create the TriggerRun, it's the API developer's responsibility
	// to remove the orphan data (e.g. with a garbage collection job).
	BeforeCreate(context.Context, *CreateTriggerRunRequest) error

	// BeforeUpdate is called before a UpdateTriggerRunRequest is sent to the K8s API server.
	//
	// This method can be used to validate or modify the UpdateTriggerRunRequest, before it's sent to the k8s API
	// server. If this method returns an error, the UpdateTriggerRunRequest will not be sent to the K8s API server
	// and the error is returned to the gRPC client.
	//
	// API developer may use this method to store some fields of TriggerRun into another storage system, instead of
	// K8s / ETCD. In the modified UpdateTriggerRunRequest, those fields may be set to nil or empty or the key / uri
	// of the actual data.  If eventually K8s fails to update the TriggerRun, it's the API developer's responsibility
	// to remove the orphan data (e.g. with a garbage collection job).
	BeforeUpdate(context.Context, *UpdateTriggerRunRequest) error

	// OnGetSuccess is called after a successful K8s get, before the result is returned to the client.
	//
	// API developer may use the method to retrieve the data that was stored in another storage system (by BeforeCreate
	// and BeforeUpdate), and fill back to the original fields in TriggerRun.
	//
	// If this method returns an error, the GetTriggerRun gRPC call will return the error to the client.
	OnGetSuccess(context.Context, *TriggerRun) error

	// OnListSuccess is called after a successful K8s list, before the result is returned to the client.
	//
	// API developer may use this method to retrieve the data that was stored in another storage system (by BeforeCreate
	// and BeforeUpdate), and fill back to the original fields in TriggerRun.
	//
	// If this method returns an error, the ListTriggerRun gRPC call will return the error to the client.
	OnListSuccess(context.Context, *ListTriggerRunRequest, *TriggerRunList) error

	// BeforeDelete is called before a DeleteTriggerRunRequest is sent to the K8s API server.
	//
	// This method can be used to validate or modify the DeleteTriggerRunRequest, before it's sent to the k8s API
	// server. If this method returns an error, the DeleteTriggerRunRequest will not be sent to the K8s API server
	// and the error is returned to the gRPC client.
	BeforeDelete(context.Context, *DeleteTriggerRunRequest) error

	// OnDeleteSuccess is called after a successful K8s delete, before the result is returned to the client.
	//
	// API developer may use this method to delete the data stored in another storage system. Since the TriggerRun
	// is already successfully deleted in K8s, even if the data in the other storage system cannot be removed, the gRPC
	// call DeleteTriggerRun still returns success (error = nil). It's the API developer's responsibility to remove
	// the orphan data (e.g. with a garbage collection job).
	OnDeleteSuccess(context.Context, *DeleteTriggerRunRequest)

	// BeforeDeleteCollection is called before a DeleteTriggerRunCollectionRequest is sent to the K8s API server.
	//
	// This method can be used to validate or modify the DeleteTriggerRunCollectionRequest, before it's sent to the k8s API
	// server. If this method returns an error, the DeleteTriggerRunCollectionRequest will not be sent to the K8s API server
	// and the error is returned to the gRPC client.
	BeforeDeleteCollection(context.Context, *DeleteTriggerRunCollectionRequest) error

	// OnDeleteCollectionSuccess is called after a successful K8s delete, before the result is returned to the client.
	//
	// API developer may use this method to delete the data stored in another storage system. Since the collection of
	// TriggerRun is already successfully deleted in K8s, even if the data in the other storage system cannot be
	// removed, the gRPC call DeleteTriggerRun still returns success (error = nil). It's the API developer's
	// responsibility to remove the orphan data (e.g. with a garbage collection job).
	OnDeleteCollectionSuccess(context.Context, *DeleteTriggerRunCollectionRequest)
}

// NoopTriggerRunAPIHook is a no-op implementation of TriggerRunAPIHook, which can be embedded in a
// TriggerRunAPIHook struct to implement only the methods that are needed.
type NoopTriggerRunAPIHook struct{}

func (n NoopTriggerRunAPIHook) BeforeCreate(context.Context, *CreateTriggerRunRequest) error {
	return nil
}

func (n NoopTriggerRunAPIHook) BeforeUpdate(context.Context, *UpdateTriggerRunRequest) error {
	return nil
}

func (n NoopTriggerRunAPIHook) OnGetSuccess(context.Context, *TriggerRun) error {
	return nil
}

func (n NoopTriggerRunAPIHook) OnListSuccess(
	context.Context,
	*ListTriggerRunRequest,
	*TriggerRunList) error {
	return nil
}

func (n NoopTriggerRunAPIHook) BeforeDelete(context.Context, *DeleteTriggerRunRequest) error {
	return nil
}

func (n NoopTriggerRunAPIHook) OnDeleteSuccess(context.Context, *DeleteTriggerRunRequest) {}

func (n NoopTriggerRunAPIHook) BeforeDeleteCollection(context.Context, *DeleteTriggerRunCollectionRequest) error {
	return nil
}

func (n NoopTriggerRunAPIHook) OnDeleteCollectionSuccess(context.Context, *DeleteTriggerRunCollectionRequest) {
}

func (c triggerRunServiceHandler) CreateTriggerRun(
	ctx context.Context, request *CreateTriggerRunRequest) (resp *CreateTriggerRunResponse, err error) {
	logger := logging.GetLogrLoggerOrPanic()

	requestJSON := logging.MarshalToString(request)

	logger = logger.WithValues("request", requestJSON, "context", ctx)
	logger.Info("CreateTriggerRun Request Called")

	metric := c.MetricsScope.Tagged(map[string]string{
		logging.APIProcedureTag: "CreateTriggerRun",
		logging.NamespaceTag:    request.TriggerRun.ObjectMeta.Namespace,
		logging.EntityNameTag:   request.TriggerRun.ObjectMeta.Name,
	})

	defer c.auditLogEmitter.Emit(ctx, c.buildTriggerRunAuditLogEventForCreate(
		ctx,
		request,
		resp,
		err,
	),
	)

	// Authentication
	userAuthenticated, err := c.auth.UserAuthenticated(ctx)
	if !userAuthenticated {
		logger.Error(err, "User is not authenticated")
		metric.Counter("unauthenticated").Inc(1)
		return nil, err
	}

	// Authorization
	projectName := request.TriggerRun.Namespace
	userAuthorized, err := c.auth.UserAuthorized(ctx, projectName, authapi.Create, "TriggerRun")

	if !userAuthorized {
		logger.Error(err, "User is not authorized")
		metric.Counter("unauthorized").Inc(1)
		return nil, err
	}

	createOptions := &metav1.CreateOptions{}
	if request.CreateOptions != nil {
		createOptions = request.CreateOptions
	}

	if err = api.Validate(request.TriggerRun); err != nil {
		metric.Counter("fail").Inc(1)
		return nil, err
	}

	for _, hook := range triggerRunApiHooks {
		if err = hook.BeforeCreate(ctx, request); err != nil {
			logger.Error(err, "Error in BeforeCreate API hook", "error", err, "api_msg_tag", "CreateTriggerRun")
			metric.Counter("fail").Inc(1)
			return nil, err
		}
	}

	err = c.apiHandler.Create(ctx, request.TriggerRun, createOptions)

	if err != nil {
		logger.Error(err, "API Handler failed to create TriggerRun", "error", err, "api_msg_tag", "CreateTriggerRun")
		metric.Counter("fail").Inc(1)
		return nil, err
	}

	logger.Info("CreateTriggerRun Request Successfully Completed.", "api_msg_tag", "CreateTriggerRun")

	metric.Counter("success").Inc(1)
	return &CreateTriggerRunResponse{TriggerRun: request.TriggerRun}, err
}

func (c triggerRunServiceHandler) GetTriggerRun(
	ctx context.Context, request *GetTriggerRunRequest) (resp *GetTriggerRunResponse, err error) {
	logger := logging.GetLogrLoggerOrPanic()
	requestJSON := logging.MarshalToString(request)

	logger = logger.WithValues("request", requestJSON, "context", ctx)
	logger.Info("GetTriggerRun Request Called")

	metric := c.MetricsScope.Tagged(map[string]string{
		logging.APIProcedureTag: "GetTriggerRun",
		logging.NamespaceTag:    request.Namespace,
		logging.EntityNameTag:   request.Name,
	})

	getOptions := &metav1.GetOptions{}
	if request.GetOptions != nil {
		getOptions = request.GetOptions
	}

	result := &TriggerRun{}
	err = c.apiHandler.Get(ctx, request.Namespace, request.Name, getOptions, result)

	defer c.auditLogEmitter.Emit(ctx, c.buildTriggerRunAuditLogEventForGet(
		ctx,
		request,
		resp,
		err,
	),
	)

	if err != nil {
		logger.Error(err, "Cannot get TriggerRun request info from k8s/ETCD", "error", err, "api_msg_tag", "GetTriggerRun")
		metric.Counter("fail").Inc(1)
		return nil, err
	}

	// There's a bug in k8s client's Get() method where TypeMeta is not returned
	// https://github.com/kubernetes-sigs/controller-runtime/issues/1517
	// Therefore fill it manually
	result.APIVersion = GroupVersion.String()
	result.Kind = "TriggerRun"

	for _, hook := range triggerRunApiHooks {
		if err = hook.OnGetSuccess(ctx, result); err != nil {
			logger.Error(err, "Error in OnGetSuccess API hook", "error", err, "api_msg_tag", "GetTriggerRun")
			metric.Counter("fail").Inc(1)
			return nil, err
		}
	}

	logger.Info("GetTriggerRun Request Successfully Completed.", "api_msg_tag", "GetTriggerRun")

	metric.Counter("success").Inc(1)

	// Michelangelo Unifed API currently doesn't use ManagedFields, so we need to remove it from the response
	result.ManagedFields = nil
	return &GetTriggerRunResponse{TriggerRun: result}, nil
}

func (c triggerRunServiceHandler) UpdateTriggerRun(
	ctx context.Context, request *UpdateTriggerRunRequest) (resp *UpdateTriggerRunResponse, err error) {
	logger := logging.GetLogrLoggerOrPanic()
	requestJSON := logging.MarshalToString(request)

	logger = logger.WithValues("request", requestJSON, "context", ctx)
	logger.Info("UpdateTriggerRun Request Called")

	metric := c.MetricsScope.Tagged(map[string]string{
		logging.APIProcedureTag: "UpdateTriggerRun",
		logging.NamespaceTag:    request.TriggerRun.ObjectMeta.Namespace,
		logging.EntityNameTag:   request.TriggerRun.ObjectMeta.Name,
	})

	defer c.auditLogEmitter.Emit(ctx, c.buildTriggerRunAuditLogEventForUpdate(
		ctx,
		request,
		resp,
		err,
	),
	)

	// Authentication
	userAuthenticated, err := c.auth.UserAuthenticated(ctx)
	if !userAuthenticated {
		logger.Error(err, "User is not authenticated")
		metric.Counter("unauthenticated").Inc(1)
		return nil, err
	}

	// Authorization
	projectName := request.TriggerRun.Namespace
	userAuthorized, err := c.auth.UserAuthorized(ctx, projectName, authapi.Update, "TriggerRun")

	if !userAuthorized {
		logger.Error(err, "User is not authorized")
		metric.Counter("unauthorized").Inc(1)
		return nil, err
	}

	updateOptions := &metav1.UpdateOptions{}
	if request.UpdateOptions != nil {
		updateOptions = request.UpdateOptions
	}

	if err = api.Validate(request.TriggerRun); err != nil {
		metric.Counter("fail").Inc(1)
		return nil, err
	}

	for _, hook := range triggerRunApiHooks {
		if err = hook.BeforeUpdate(ctx, request); err != nil {
			logger.Error(err, "Error in BeforeUpdate API hook", "error", err, "api_msg_tag", "UpdateTriggerRun")
			metric.Counter("fail").Inc(1)
			return nil, err
		}
	}

	err = c.apiHandler.Update(ctx, request.TriggerRun, updateOptions)

	if err != nil {
		logger.Error(err, "API Handler failed to update TriggerRun", "error", err, "api_msg_tag", "UpdateTriggerRun")
		metric.Counter("fail").Inc(1)
		return nil, err
	}

	logger.Info("UpdateTriggerRun Request Successfully Completed.", "api_msg_tag", "UpdateTriggerRun")

	metric.Counter("success").Inc(1)
	return &UpdateTriggerRunResponse{TriggerRun: request.TriggerRun}, err
}

func (c triggerRunServiceHandler) DeleteTriggerRun(
	ctx context.Context, request *DeleteTriggerRunRequest) (resp *DeleteTriggerRunResponse, err error) {
	logger := logging.GetLogrLoggerOrPanic()
	requestJSON := logging.MarshalToString(request)

	logger = logger.WithValues("request", requestJSON, "context", ctx)
	logger.Info("DeleteTriggerRun Request Called")

	metric := c.MetricsScope.Tagged(map[string]string{
		logging.APIProcedureTag: "DeleteTriggerRun",
		logging.NamespaceTag:    request.Namespace,
		logging.EntityNameTag:   request.Name,
	})

	defer c.auditLogEmitter.Emit(ctx, c.buildTriggerRunAuditLogEventForDelete(
		ctx,
		request,
		resp,
		err,
	),
	)

	// Authentication
	userAuthenticated, err := c.auth.UserAuthenticated(ctx)
	if !userAuthenticated {
		logger.Error(err, "User is not authenticated")
		metric.Counter("unauthenticated").Inc(1)
		return nil, err
	}

	// Authorization
	projectName := request.Namespace
	userAuthorized, err := c.auth.UserAuthorized(ctx, projectName, authapi.Delete, "TriggerRun")

	if !userAuthorized {
		logger.Error(err, "User is not authorized")
		metric.Counter("unauthorized").Inc(1)
		return nil, err
	}

	deleteOptions := &metav1.DeleteOptions{}
	if request.DeleteOptions != nil {
		deleteOptions = request.DeleteOptions
	}

	deleteObj := &TriggerRun{
		ObjectMeta: metav1.ObjectMeta{Namespace: request.Namespace, Name: request.Name}}

	for _, hook := range triggerRunApiHooks {
		if err = hook.BeforeDelete(ctx, request); err != nil {
			logger.Error(err, "Error in BeforeDelete API hook", "error", err, "api_msg_tag", "DeleteTriggerRun")
			metric.Counter("fail").Inc(1)
			return nil, err
		}
	}

	err = c.apiHandler.Delete(ctx, deleteObj, deleteOptions)

	if err != nil {
		logger.Error(err, "Cannot delete TriggerRun from either ETCD or MySQL", "error", err, "api_msg_tag", "DeleteTriggerRun")
		metric.Counter("fail").Inc(1)
		return nil, err
	}

	for _, hook := range triggerRunApiHooks {
		hook.OnDeleteSuccess(ctx, request)
	}

	logger.Info("DeleteTriggerRun Request Successfully Completed.", "api_msg_tag", "DeleteTriggerRun")

	metric.Counter("success").Inc(1)
	return &DeleteTriggerRunResponse{}, nil
}

func (c triggerRunServiceHandler) DeleteTriggerRunCollection(
	ctx context.Context, request *DeleteTriggerRunCollectionRequest) (resp *DeleteTriggerRunCollectionResponse, err error) {
	logger := logging.GetLogrLoggerOrPanic()
	requestJSON := logging.MarshalToString(request)

	logger = logger.WithValues("request", requestJSON, "context", ctx)
	logger.Info("DeleteTriggerRunCollection Request Called")

	metric := c.MetricsScope.Tagged(map[string]string{
		logging.APIProcedureTag: "DeleteTriggerRunCollection",
		logging.NamespaceTag:    request.Namespace,
	})

	defer c.auditLogEmitter.Emit(ctx, c.buildTriggerRunAuditLogEventForDeleteCollection(
		ctx,
		request,
		resp,
		err,
	),
	)

	// Authentication
	userAuthenticated, err := c.auth.UserAuthenticated(ctx)
	if !userAuthenticated {
		logger.Error(err, "User is not authenticated")
		metric.Counter("unauthenticated").Inc(1)
		return nil, err
	}

	// Authorization
	projectName := request.Namespace
	userAuthorized, err := c.auth.UserAuthorized(ctx, projectName, authapi.DeleteCollection, "TriggerRun")

	if !userAuthorized {
		logger.Error(err, "User is not authorized")
		metric.Counter("unauthorized").Inc(1)
		return nil, err
	}

	deleteOptions := &metav1.DeleteOptions{}
	if request.DeleteOptions != nil {
		deleteOptions = request.DeleteOptions
	}

	listOptions := &metav1.ListOptions{}
	if request.ListOptions != nil {
		listOptions = request.ListOptions
	}

	for _, hook := range triggerRunApiHooks {
		if err = hook.BeforeDeleteCollection(ctx, request); err != nil {
			logger.Error(err, "Error in BeforeDeleteCollection", "error", err, "api_msg_tag", "DeleteTriggerRunCollection")
			metric.Counter("fail").Inc(1)
			return nil, err
		}
	}

	err = c.apiHandler.DeleteCollection(ctx, &TriggerRun{}, request.Namespace, deleteOptions, listOptions)

	if err != nil {
		logger.Error(err, "API Handler failed to Delete TriggerRun Collection", "error", err, "api_msg_tag", "DeleteTriggerRunCollection")
		metric.Counter("fail").Inc(1)
		return nil, err
	}

	for _, hook := range triggerRunApiHooks {
		hook.OnDeleteCollectionSuccess(ctx, request)
	}

	logger.Info("DeleteTriggerRunCollection Request Successfully Completed.", "api_msg_tag", "DeleteTriggerRunCollection")

	metric.Counter("success").Inc(1)
	return &DeleteTriggerRunCollectionResponse{}, nil
}

func (c triggerRunServiceHandler) ListTriggerRun(
	ctx context.Context, request *ListTriggerRunRequest) (resp *ListTriggerRunResponse, err error) {

	logger := logging.GetLogrLoggerOrPanic()
	requestJSON := logging.MarshalToString(request)

	logger = logger.WithValues("request", requestJSON, "context", ctx)
	logger.Info("ListTriggerRun Request Called")

	metric := c.MetricsScope.Tagged(map[string]string{
		logging.APIProcedureTag: "ListTriggerRun",
		logging.NamespaceTag:    request.Namespace,
	})

	result := &TriggerRunList{}
	listOptions := &metav1.ListOptions{}
	if request.ListOptions != nil {
		listOptions = request.ListOptions
	}
	listOptionsExt := &apipb.ListOptionsExt{}
	if request.ListOptionsExt != nil {
		listOptionsExt = request.ListOptionsExt
	}
	err = c.apiHandler.List(ctx, request.Namespace, listOptions, listOptionsExt, result)

	defer c.auditLogEmitter.Emit(ctx, c.buildTriggerRunAuditLogEventForList(
		ctx,
		request,
		resp,
		err,
	),
	)

	if err != nil {
		logger.Error(err, "API Handler failed to List TriggerRun", "error", err, "api_msg_tag", "ListTriggerRun")
		metric.Counter("fail").Inc(1)
		return nil, err
	}

	for _, hook := range triggerRunApiHooks {
		if err = hook.OnListSuccess(ctx, request, result); err != nil {
			logger.Error(err, "Error in OnListSuccess API hook", "error", err, "api_msg_tag", "GetTriggerRun")
			metric.Counter("fail").Inc(1)
			return nil, err
		}
	}

	logger.Info("ListTriggerRun Request Successfully Completed.", "api_msg_tag", "ListTriggerRun")

	metric.Counter("success").Inc(1)

	// Michelangelo Unifed API currently doesn't use ManagedFields, so we need to remove it from the response
	for _, item := range result.Items {
		item.ManagedFields = nil
	}

	resp = &ListTriggerRunResponse{TriggerRunList: result}
	return resp, err
}

func (c triggerRunServiceHandler) buildAuditLogEvent(
	ctx context.Context, procedure string, entityType string, requestNamespace string, requestName string, request interface{}, response interface{}, grpcErr error) *logging.AuditLogEvent {
	requestJSON := logging.MarshalToString(request)
	responseJSON := logging.MarshalToString(response)
	errMsg := ""
	if grpcErr != nil {
		errMsg = grpcErr.Error()
	}

	event := &logging.AuditLogEvent{
		Namespace:  requestNamespace,
		EntityType: entityType,
		EntityName: requestName,
		Procedure:  procedure,
		Request:    requestJSON,
		Response:   responseJSON,
		Error:      errMsg,
	}

	return event
}

func (c triggerRunServiceHandler) buildTriggerRunAuditLogEventForCreate(
	ctx context.Context,
	request *CreateTriggerRunRequest,
	response *CreateTriggerRunResponse,
	grpcErr error) *logging.AuditLogEvent {
	requestNamespace := request.TriggerRun.ObjectMeta.Namespace
	requestName := request.TriggerRun.ObjectMeta.Name
	entityType := "TriggerRun"
	procedure := "CreateTriggerRun"
	return c.buildAuditLogEvent(ctx, procedure, entityType, requestNamespace, requestName, request, response, grpcErr)
}

func (c triggerRunServiceHandler) buildTriggerRunAuditLogEventForGet(
	ctx context.Context, request *GetTriggerRunRequest,
	response *GetTriggerRunResponse, grpcErr error) *logging.AuditLogEvent {
	requestNamespace := request.Namespace
	requestName := request.Name
	entityType := "TriggerRun"
	procedure := "GetTriggerRun"
	return c.buildAuditLogEvent(ctx, procedure, entityType, requestNamespace, requestName, request, response, grpcErr)

}

func (c triggerRunServiceHandler) buildTriggerRunAuditLogEventForUpdate(
	ctx context.Context, request *UpdateTriggerRunRequest,
	response *UpdateTriggerRunResponse, grpcErr error) *logging.AuditLogEvent {
	requestNamespace := request.TriggerRun.ObjectMeta.Namespace
	requestName := request.TriggerRun.ObjectMeta.Name
	entityType := "TriggerRun"
	procedure := "UpdateTriggerRun"

	event := c.buildAuditLogEvent(ctx, procedure, entityType, requestNamespace, requestName, request, response, grpcErr)

	preCRD := ""
	getOptions := &metav1.GetOptions{
		TypeMeta: metav1.TypeMeta{
			Kind: "TriggerRun",
		},
	}

	result := &TriggerRun{}
	err := c.apiHandler.Get(ctx, requestNamespace, requestName, getOptions, result)

	if err == nil {
		preCRD = logging.MarshalToString(result)
	}

	event.PreCRD = preCRD

	return event
}

func (c triggerRunServiceHandler) buildTriggerRunAuditLogEventForDelete(
	ctx context.Context, request *DeleteTriggerRunRequest,
	response *DeleteTriggerRunResponse, grpcErr error) *logging.AuditLogEvent {
	requestNamespace := request.Namespace
	requestName := request.Name
	entityType := "TriggerRun"
	procedure := "DeleteTriggerRun"
	event := c.buildAuditLogEvent(ctx, procedure, entityType, requestNamespace, requestName, request, response, grpcErr)

	preCRD := ""
	getOptions := &metav1.GetOptions{
		TypeMeta: metav1.TypeMeta{
			Kind: "TriggerRun",
		},
	}

	result := &TriggerRun{}
	err := c.apiHandler.Get(ctx, requestNamespace, requestName, getOptions, result)

	if err == nil {
		preCRD = logging.MarshalToString(result)
	}

	event.PreCRD = preCRD

	return event

}

func (c triggerRunServiceHandler) buildTriggerRunAuditLogEventForDeleteCollection(
	ctx context.Context, request *DeleteTriggerRunCollectionRequest,
	response *DeleteTriggerRunCollectionResponse, grpcErr error) *logging.AuditLogEvent {
	requestNamespace := request.Namespace
	requestName := ""
	entityType := "TriggerRun"
	procedure := "DeleteTriggerRunCollection"
	return c.buildAuditLogEvent(ctx, procedure, entityType, requestNamespace, requestName, request, response, grpcErr)
}

func (c triggerRunServiceHandler) buildTriggerRunAuditLogEventForList(
	ctx context.Context, request *ListTriggerRunRequest,
	response *ListTriggerRunResponse, grpcErr error) *logging.AuditLogEvent {
	requestNamespace := request.Namespace
	requestName := ""
	entityType := "TriggerRun"
	procedure := "ListTriggerRun"
	event := c.buildAuditLogEvent(ctx, procedure, entityType, requestNamespace, requestName, request, response, grpcErr)

	responseList := ""
	if grpcErr != nil {
		for _, item := range response.GetTriggerRunList().GetItems() {
			responseList = responseList + item.GetName() + ","
		}
	}

	event.Response = responseList

	return event
}

var TriggerRunSvcModule = fx.Provide(
	NewTriggerRunServiceHandler,
	NewFxTriggerRunServiceYARPCProcedures(),
)
