name: Python Ruff Lint & Format

on:
  pull_request:
    branches: [main]

jobs:

  
  ruff:
    name: Python Run Ruff on Changed Files
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write   # For commenting on PRs
      contents: read

    defaults:
      run:
        working-directory: ./python

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 50      # Fetch 50 max commits in single PR

      - name: Fetch main branch
        run: git fetch origin main 

      - name: Check branch list
        run: git branch -av

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      #----------------------------------------------
      #  install deps
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: .venv
          installer-parallel: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root -E dev
      - name: Install project
        run: poetry install --no-interaction -E dev

      #----------------------------------------------
      # Run ruff on changed files
      #----------------------------------------------
      - name: Get base SHA for comparison
        id: get-base-sha
        run: |
          BASE_SHA=$(git merge-base origin/${{ github.base_ref }} HEAD)
          echo "BASE_SHA=$BASE_SHA" >> $GITHUB_ENV

      - name: Get changed files
        id: changed-files
        run: |
          echo "Comparing changes from $BASE_SHA to HEAD"
          CHANGED_FILES_PRE=$(git diff --name-only $BASE_SHA HEAD | grep -E '\.py$' || true)
          echo "Raw Changed files:"
          echo "$CHANGED_FILES_PRE"

          # Check if there are any changed files
          if [ -z "$CHANGED_FILES_PRE" ]; then
              CHANGED_FILES=""
          else
              # Filter out files in michelangelo/gen/
              CHANGED_FILES=$(echo "$CHANGED_FILES_PRE" | grep -vE '^python/michelangelo/gen/' | awk '
              {
                  if ($0 ~ /^python\//) {
                      sub(/^python\//, "", $0);
                      print $0;
                  } else {
                      print "../"$0;
                  }
              }')
          fi

          echo "Filtered Changed files:"
          echo "$CHANGED_FILES"
          echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
          echo "$CHANGED_FILES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Run ruff format check (without applying)
        if: env.CHANGED_FILES != ''
        id: ruff-format
        run: |
          output=$(poetry run ruff format --diff $CHANGED_FILES || true)
          echo "$output" | tee ruff_format_output.txt
          echo "RUFF_FORMAT_OUTPUT<<EOF" >> $GITHUB_ENV
          echo "$output" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Run ruff lint on changed files
        if: env.CHANGED_FILES != ''
        id: ruff-lint
        run: |
          output=$(poetry run ruff check $CHANGED_FILES || true)
          echo "$output" | tee ruff_lint_output.txt
          echo "RUFF_LINT_OUTPUT<<EOF" >> $GITHUB_ENV
          echo "$output" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Comment on PR with Ruff results
        uses: actions/github-script@v6
        if: env.CHANGED_FILES != ''
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const formatOutput = process.env.RUFF_FORMAT_OUTPUT.trim();
            const lintOutput = process.env.RUFF_LINT_OUTPUT.trim();
            const pr_number = context.payload.pull_request.number;
            let body = "### 🛠 Ruff Check & Format Results\n";

            if (formatOutput) {
              body += "\n#### ⚠️ Format Issues Detected\n```\n" + formatOutput + "\n```\n";
              body += "📌 Please run `poetry run ruff format .` locally to fix formatting issues.\n\n";
            }

            if (lintOutput) {
              body += "\n#### 🚨 Lint Issues Detected\n```\n" + lintOutput + "\n```\n";
            }

            if (formatOutput || lintOutput) {
              body += "\n🛠 Run `poetry install -E dev` to set up pre-commit hooks and apply fixes locally. (or run `poetry run pre-commit` before run git commit)";
              github.rest.issues.createComment({
                issue_number: pr_number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: body
              });
            }
