name: Python Ruff Lint & Format

on:
  pull_request:
    branches: [main]

jobs:
  ruff:
    name: Python Run Ruff on Changed Files
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      #----------------------------------------------
      #  install deps
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: .venv
          installer-parallel: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root -E dev
      - name: Install project
        run: poetry install --no-interaction

      #----------------------------------------------
      # Run ruff on changed files
      #----------------------------------------------
      - name: Get changed files (excluding specific directories)
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }} | grep -E '\.py$' || true)
          echo "$CHANGED_FILES"
          echo "FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Run ruff format on changed files
        if: env.FILES != ''
        run: |
          ruff format $FILES
          echo "Ruff Format applied."

      - name: Run ruff lint on changed files
        if: env.FILES != ''
        id: ruff-lint
        run: |
          output=$(ruff check $FILES || true)
          echo "$output" | tee ruff_lint_output.txt
          echo "RUFF_LINT_OUTPUT<<EOF" >> $GITHUB_ENV
          echo "$output" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Comment on PR with Ruff results
        uses: actions/github-script@v6
        if: env.FILES != ''
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = process.env.RUFF_LINT_OUTPUT;
            const pr_number = context.payload.pull_request.number;
            if (output.trim() !== "") {
              github.rest.issues.createComment({
                issue_number: pr_number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: "### 🛠 Ruff Check & Format Results\n```\n" + output + "\n\n Please run `poetry install -E dev` to run pre-commit hook on your local.\n```"
              });
            }
