name: Bazel Test

# Trigger the workflow on push and pull request events for the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  bazel-build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Cache Bazel outputs
      - name: Cache Bazel Outputs
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/bazel
          key: bazel_cache_root
          restore-keys: |
            bazel_cache_root

      # Run Bazel tests
      - name: Run Bazel Test
        run: ./tools/bazel test ...


  python-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Poetry and Run Tests
        run: |
          pip install poetry
          cd python
          poetry install
          poetry run pytest
